### ISSUE TITLE
Starting point

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-ui#1]
Not an issue but information:

An attempt to make things more consistent between Cozy apps was to provide this stylesheet in every application. https://github.com/cozy/cozy-files/blob/master/client/app/views/styles/_cozy.styl
That way we made all the cozy buttons behave the same way. They are not really pretty but it makes easier for users to learn the Cozy apps.

**Comment by m4dz** [comment]
Yep, I've seen this stylesheet. My first idea is to provide a set of tools (stylesheets, plugins…) that can be easily reusable between apps. I'll take this one as a starting point :wink:.
