### ISSUE TITLE
Multi-step modal

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1000]
In banks, we have some flows that open a modal, which can open another modal, etc. Maybe we should think about a multi-step modal to avoid stacking multiple modals of top of each other.

I think the implementation of cozy-banks' [`PopupSelect`](https://github.com/cozy/cozy-banks/blob/master/src/components/PopupSelect/index.jsx#L42) can be used a good base.

**Comment by Crash--** [comment]
We can also take a look at the `Stepper` component from m-ui https://material-ui.com/demos/steppers/

**Comment by ptbrowne** [comment]
I guess we can close now that we have the ViewStack that can be used for this ?

**Comment by drazik** [comment]
Yep
