### ISSUE TITLE
Add bill proptypes

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1013]
In banks, we pass some `io.cozy.bills` document through React components props. This would be good to have the corresponding proptypes in cozy-ui as suggested by @ptbrowne here: https://github.com/cozy/cozy-banks/pull/1216#discussion_r288040181

**Comment by y-lohse** [comment]
Wouldn't it make more sense to have this in `cozy-doctypes` ?

**Comment by ptbrowne** [comment]
cozy-doctypes will die. So no new code should be there IMHO. proptypes for documents could be in cozy-client or cozy-ui. cozy-client will surely at some point gain core doctypes schemas so I think we should be safe if we put them in cozy-client.

**Comment by y-lohse** [comment]
Right, and the doctypes / models will end up in cozy-client too. I think these proptypes are more related to the models than UI components.

**Comment by Crash--** [comment]
I'm closing this issue right now. We're thinking about having schemas in cozy-client.
