### ISSUE TITLE
Radio button has issues with fastclick

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1027]
We have to add 

```
label > * { pointer-events: none }
```

to make Radio button work correctly when using fastclick.

Should we have pointer-events: none for children of label rendered by radio ?

**Comment by y-lohse** [comment]
> to make Radio button work correctly when using fastclick.

What happens without it?

> Should we have pointer-events: none for children of label rendered by radio ?

Here's the code in question:
https://github.com/cozy/cozy-ui/blob/master/react/Radio/index.jsx#L9-L27

I don't see a problem with disabling pointer events on the `<input />`, but I'm less sure about the label. Wouldn't that make the text non-selectable for example?

**Comment by GoOz** [comment]
> We have to add
> 
> ```
> label > * { pointer-events: none }
> ```
> 
> to make Radio button work correctly when using fastclick.
> 
> Should we have pointer-events: none for children of label rendered by radio ?

If you do that you lose the cursor and hover state on the whole thing. :/

**Comment by ptbrowne** [comment]
Without it, when you click on the text in the span, the input is not selected.

> but I'm less sure about the label.

The label still has pointer-events, it's the children of the `<label>` that will not have any pointer-events.

**Comment by y-lohse** [comment]
Sorry, I meant the `<span>` that contains the label text, and that is a child of the actual `<label>` element.

**Comment by ptbrowne** [comment]
> Wouldn't that make the text non-selectable for example?

Yes the text will not be selectable.

> If you do that you lose the cursor and hover state on the whole thing. :/

Mmh yes you're right.

--- 

As I am not a fan of disabling pointer events altogether, I will try to see if it is possible to disable fastclick for this.

**Comment by y-lohse** [comment]
Or would `label > input { pointer-events: none }` work for fastclick, instead of disabling it on all children?

**Comment by JF-Cozy** [comment]
These Radio are now deprecated, please use `react/Radios` instead
