### ISSUE TITLE
Migrate the icons in the styleguide

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#1073]
We made a breaking change with the icons, but we miiiiight have forgotten to migrate our own code. As a result, some component demos that  use icons are broken, see https://docs.cozy.io/cozy-ui/react/#button for example.

**Comment by GoOz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(S) Migrate the icons in the styleguide](https://trello.com/c/p6jQkMHd/1585-s-migrate-the-icons-in-the-styleguide)
