### ISSUE TITLE
Button: Need to manage line-height

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#1074]
In cozy-harvest-lib, we need to set explicitely the line-height of our "Synchronize" button. See https://github.com/cozy/cozy-libs/pull/537#discussion_r298070682. This specific line-height allow us to make a correct horizontal alignement between button and informations on its left.

We should offer a way to set this line-height without using the `style` attribute, either with an utility class or a Button dedicated prop

**Comment by GoOz** [comment]
Not sure the dedicated prop is relevant. I think the `Button` component has quite enough props as it is. Also this could be something that other component needs so I think a utility class is the way to go.

**Comment by y-lohse** [comment]
I also think a utility class in the app is the way to go, this seems like a very specific use case.

**Comment by ptbrowne** [comment]
Can you post a screenshot of where it's needed ?

**Comment by ptbrowne** [comment]
ping ?

**Comment by GoOz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter des classes utilitaires pour le line-height](https://trello.com/c/CQHirY57/1604-ajouter-des-classes-utilitaires-pour-le-line-height)

**Comment by gregorylegarec** [comment]
@ptbrowne Sorry I missed your ping.

This is what it looks like with a 1.4 line-height on the button on the right. Without it, the button is not aligned with the text on the left.
![Capture d’écran 2019-07-04 à 10 56 00](https://user-images.githubusercontent.com/776764/60653694-d46a1000-9e4a-11e9-8e85-1b989d6016b8.png)

**Comment by ptbrowne** [comment]
J'ai essayé de reproduire le soucis dans un codesandbox pour mieux comprendre, je suis pas sur qu'on ait vraiment besoin de line-height ici, est ce qu'utiliser Media ne suffirait pas ?

https://codesandbox.io/s/fast-tdd-e147o

**Comment by gregorylegarec** [comment]
It's not exactly the markup we have in the [`LaunchTriggerCard` component](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx#L28).

Moreover this part is responsive; on small screen the button is below the two texts.
