### ISSUE TITLE
BodyScrollLock is broken on iOS mobile

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#1089]
When opening an Overlay, we lock the scroll using https://github.com/willmcpo/body-scroll-lock.

Unfortunately this doesn't work as expected anymore on mobile iOS devices, neither does it in the component styleguidist in mobile resolution.

For the styleguidist, it's because the defautl theme has an `overflow` rule on the body element which interferes with body-scroll-lock, but it's not a big deal.

The real problem is with iOS devices. [These lines](https://github.com/cozy/cozy-ui/blob/master/react/Overlay/index.jsx#L24-L27) are executed, but the scroll still isn't prevented.

**Comment by GoOz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🚫 [UI] 📱 scroll modale full screen sur safari mobile](https://trello.com/c/9ZYrKnZR/1157-%F0%9F%9A%AB-ui-%F0%9F%93%B1-scroll-modale-full-screen-sur-safari-mobile)

**Comment by JF-Cozy** [comment]
Nous n'utilisons plus cette lib sur cozy-ui
