### ISSUE TITLE
Stack layout

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1096]
Following the https://every-layout.dev/layouts/stack/ article, I was wondering if it would make sense to have some components/utility classes for stacks.

```
.stack > * + * {
  margin-top: 1rem
}

.stack--dense > * + * {
  margin-top: 0.5rem
}

.stack--sparse > * + * {
  margin-top: 1.5rem
}
```

and their responsive companions.

**Comment by ptbrowne** [comment]
Ping @joel-costa

**Comment by GoOz** [comment]
It would, yes. This is meant to be some kind of utility classes, right?
Althought there should be a complete documentation to highlight the strict DOM that is needed for this to work as expected.

**Comment by drazik** [comment]
A component like the one we have in banks (https://github.com/cozy/cozy-banks/blob/master/src/components/Stack/index.jsx) would be great yes!

**Comment by y-lohse** [comment]
Do you see a use case that the {Material-UI List](https://docs.cozy.io/cozy-ui/react/#list-1) component doesn't solve? It also has this concept of dense for example.

**Comment by GoOz** [comment]
@y-lohse yeah but the List component comes with some styles (visually I mean). I think what @ptbrowne needs is a "transparent" component that just acts as a layout, in order to apply a consistent spacing on all its children.
