### ISSUE TITLE
Infos style should be more overridable

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1161]
In Banks we have designs where the Info

- takes all the width
- have no borders

See https://github.com/cozy/cozy-banks/pull/1573

For the width, I think we could remove the u-maw-6 class and let the user
of this component apply this class.

For the borders I think it should
be set in a stylus file, otherwise it is difficult to override for example with
an utility class, since the order of classes do no matter (only the order of
classes in the CSS).

**Comment by y-lohse** [comment]
> For the width, I think we could remove the u-maw-6 class and let the user of this component apply this class.

Yep, no problem for me as long as we set the equivalent of `u-maw-6` in the Info stylus file (sio it's not a breaking change, but can be overriden).

> For the borders I think it should be set in a stylus file

👍

**Comment by ptbrowne** [comment]
Fixed in #1162
