### ISSUE TITLE
Support generateUniversalLink in konnectors without overriding

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1173]
2 problems make it difficult to use generateUniversalLink and generateWebLink
in konnectors (for example, when sending emails).

## Imports

In konnectors, we want to be able to access generateUniversalLink
and generateWebLink. This is impossible for now since cozy-ui ships
in es6 modules. konnector execution in development is done directly
with node, so `import` are not supported.

- Should we ship an es5 version of cozy-ui along with the dist/ ?
- Should this functions be in cozy-client and cozy-ui relies on cozy-client
to render the AppLinker

## Overrides

The way to have a different domain here is to override the native.config.js
file. This means we would have to ship different konnector bundles for every
context (:orange:).

I think this is not suitable, we could tackle this problem with a mapping
from context to universalLinkDomain.

**Comment by y-lohse** [comment]
> Should this functions be in cozy-client and cozy-ui relies on cozy-client
to render the AppLinker

I think this is the better option for the import problem. These functions have proven useful even outside of the `AppLinker` component, it would make sense to decouple them from the rest of cozy-ui.

>I think this is not suitable, we could tackle this problem with a mapping
from context to universalLinkDomain.

What do you mean by "mapping
from context to universalLinkDomain"?

**Comment by ptbrowne** [comment]
> What do you mean by "mapping from context to universalLinkDomain"?

```
const contextToULDomain = {
  defaults: 'links.cozycloud.cc',
  orange: 'linksorange.cozycloud.cc
}
```

**Comment by JF-Cozy** [comment]
generateWebLink a implémenté dans cozy-client.
Cette issue ne semble plus être un sujet aujourd'hui
