### ISSUE TITLE
BannerClient seems broken ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1187]
In Argos, the BannerClient has weird margins, is it normal ? See https://www.argos-ci.com/cozy/cozy-ui/builds/55431

**Comment by y-lohse** [comment]
Had a quick look with the devtools, it seems coded that way… so I think it's normal, but I can't remember why right now, I'd need to investigate that. Is it causing problems in argos ?

**Comment by ptbrowne** [comment]
No, it is not causing problems, but it seems weird to have this in the styleguidist.

**Comment by Crash--** [comment]
I'm closing this issue since this component has been refactored and now well displayed even in argos
