### ISSUE TITLE
Argos / Component viewPort mobile

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1206]
Some component need to be tested on mobile. ATM argos only set the viewport to desktop resolution.

This issue is here to discuss how we can implement automatic screenshot on mobile viewport for a few components.  (for instance https://www.argos-ci.com/cozy/cozy-ui/builds/55995) 

We currently go to the page : https://github.com/cozy/cozy-ui/blob/master/scripts/screenshots.js#L30 and take the screenshot 

If we put an information in this page saying "take a mobile screenshot", we should be able to read it from `page` and set the viewport accordingly. 

We can have for instance:
Readme.md : 
``
#### MobileOnly
```jsx
...
```
```

OR we can have a argos/config/ComponentName.json to tell which viewport we want to use for each component?

**Comment by ptbrowne** [comment]
Fixed in https://github.com/cozy/cozy-ui/pull/1356
