### ISSUE TITLE
Using CSS variables in MuiCozyTheme makes apps tests crash

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1214]
Since our MUI theme is based on CSS variables values (see https://github.com/cozy/cozy-ui/blob/5ee244b818cde619a8b9d0836226550b69b9fd44/react/MuiCozyTheme/theme.js#L8-L37), when we use it in an app, we have to mock `getCssVariableValue` in `transpiled/react/utils/color.js` to make it work, otherwise it returns an empty string and `createMuiTheme` crashes, making tests crash too.

We have a workaround, but we end with a mock like the following in various apps:

```js
jest.mock('cozy-ui/transpiled/react/color', () => ({
  getCssVariableValue: () => '#fff'
}))
```

I was wondering if we have another solution to make it work without having to mock this function everytime we use the MUI theme.

**Comment by ptbrowne** [comment]
Maybe getCssVariableValue should have defaults for primaryColor etc... ?

**Comment by Crash--** [comment]
also, `getCssVariableValue` is crashing when it is used in an hidden iframe on firefox since it's based on getComputedStyle. 

I second @ptbrowne, you should test if the var is there, and return a default value if not 
https://github.com/cozy/cozy-ui/blob/master/react/utils/color.js#L3-L7

**Comment by ptbrowne** [comment]
@drazik Would you be interested in tackling this issue ?

**Comment by drazik** [comment]
Yes.

**Comment by ptbrowne** [comment]
Other alternatives:

- Detect in cozy-ui that we are in tests (via NODE_ENV == 'test')
- Is it possible to have an auto mock in cozy-ui ?
