### ISSUE TITLE
Get a ref on the modal

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#122]
In cozy-edf, I needed to get a ref on the `.coz-modal` part of the Modal to display the inter-app modal in it. Since there is no way to attach a ref callback in the `Modal`, I had to replicate the structure of the `Modal`.

https://gitlab.cozycloud.cc/labs/cozy-edf/blob/master/src/components/IntentModal.jsx

What do you think of a `modalRef` prop to be added to `<Modal />` ?

**Comment by gregorylegarec** [comment]
It feels pretty natural to me, but I am just asking how is it compatible with the 'React' philosophy. What @goldoraf and @enguerran are thinking about it ?

**Comment by ptbrowne** [comment]
To me it is a necessary bridge since cozy-client-js is not working in the React philosophy (targeting directly a DOM node).

**Comment by enguerran** [comment]
I would like to know what it is the need for. Maybe there is a more component-style workaround for your needs.

What do you mean by:

> necessary bridge since cozy-client-js is not working in the React philosophy

What I understand when you say *"to display the inter-app modal in it"* is that you need to add children to the `<Modal />` component, not an access to the underlying DOM node.

**Comment by ptbrowne** [comment]
The API of `cozy-client-js` for inter-app is : 

```
intent.start(domNode)
```

and then cozy-client-js creates the iframe inside the DOM node.

I think I see a way to do that without this ref though.

**Comment by ptbrowne** [comment]
```
import Modal from 'cozy-ui/react/Modal'
import React, { Component } from 'react'

class IntentIframe extends Component {
  componentDidMount () {
    this.intent = this.props.intent
      .start(this.base)
      .then(this.props.onIntentSuccess)
      .catch(err => this.props.onIntentError(err))
  }

  render () {
    return <div />
  }
}

export default class IntentModal extends Component {
  render ({ style, className, intent, onIntentError, onIntentSuccess }) {
    return <Modal
      className={className} withCross={false}>
        <IntentIframe
          intent={ intent }
          onIntentError={ onIntentError }
          onIntentSuccess={ onIntentSuccess } />
    </Modal>
  }
}
```

By adding another component and using `this.base` instead of a ref, it works. There is an extra div though. So yes in this case, the ref is not strictly needed. I think it can be useful for other needs though (animation comes to mind).

Thanks @enguerran !

**Comment by goldoraf** [comment]
This is definitively a better solution @ptbrowne ! :+1:

**Comment by enguerran** [comment]
TIL 

> "As with any component that reference is simply called this.base, and corresponds to the root JSX Element that was returned from render()." — https://preactjs.com/guide/external-dom-mutations#technique

**Comment by gregorylegarec** [comment]
Great to learn things every day with you guys ! 👍
