### ISSUE TITLE
Enhance icon codemod

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1227]
If one day we want to rename again our icons...

ATM, we only check for `<Icon>` usage (https://github.com/cozy/cozy-ui/blob/master/codemods/new-icons.js#L66) , but we should look for : 
- `<Button icon="">`
- SelectionBar action https://github.com/cozy/cozy-ui/blob/master/react/SelectionBar/index.jsx#L55

**Comment by ptbrowne** [comment]
I am not sure we can do something for the SelectionBar actions, we'd have to change the actions array and I think it is too complicated and not so used. I think it is already a bit brittle to use the actionName as the identifier for the icon, a mapping actionName -> iconName inside the component would be less brittle and easier to change IMHO.

Ok for the Button ;)

**Comment by ptbrowne** [comment]
Cna we close @Crash-- ?

**Comment by Crash--** [comment]
Yep thanks
