### ISSUE TITLE
Radio proptypes are too strict ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1332]
We sometimes use the Radio component outside of forms, purely as
a UI feedback. In this cases, it can be cumbersome to provide a
value and name. I think we could relax the required on those
proptypes.

Example:

In Banks, we display a Modal with selection rows, those rows each
have a Radio button. They are implemented with `ModalRow`s with the
`hasRadio` attribute. Since the ModalRow is not aware of the value/name,
it cannot pass it to the underlying Radio button.

https://github.com/cozy/cozy-banks/blob/master/src/ducks/settings/CategoryAlerts/AccountGroupChoice.jsx#L41
https://github.com/cozy/cozy-banks/blob/master/src/components/Row/index.jsx#L37

**Comment by drazik** [comment]
These attributes are not required on the HTML element, so I think since we don't do anything special with it, it shouldn't be required on our component.

**Comment by ptbrowne** [comment]
Fixed in https://github.com/cozy/cozy-ui/pull/1337
