### ISSUE TITLE
Need webpack to import cozy-ui ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#139]
We need to have `webpack.config.cozy-ui.js` files. I think it should not be the responsibility of an application to know how cozy-ui is coded so that it should know which loaders are necessary.

One solution would be to ship a built version on npm.

It would then be hard for people hacking on `cozy-ui` through another application to use it since they would have to build each time they make a change. Maybe `cozy-ui` should have a webpack file ready for people `linking` directly and wanting to hack on `cozy-ui` while they develop their application. This way, a user wanting to hack on `cozy-ui` could do:

```js
const webpackConfig = merge(
  ...,
  ...,
  require(`cozy-ui/webpack`)
)
```

temporarily in their file ?

What do you think ?

Discussion about that : https://github.com/webpack/webpack/issues/378

**Comment by gregorylegarec** [comment]
I need to make some tests. I am curious about @m4dz and @GoOz opinions.

**Comment by GoOz** [comment]
@ptbrowne do have a point. I don't know about this particular solution as i'm no expert with Webpack but it seems pretty simple and effective to me.

**Comment by CPatchane** [comment]
Seems to be a good point for me, that's also a good way to push a config update only related to cozy-ui through a cozy-ui release. 👍

**Comment by ptbrowne** [comment]
This will be done in a cozy-webpack.
