### ISSUE TITLE
Add a "mixed" state for checkboxes

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-ui#14]
We should add a `aria-checked` support for the 3 defined values `true`, `false`, `mixed` (see https://www.w3.org/TR/wai-aria/states_and_properties#aria-checked) here : https://github.com/cozy/cozy-ui/blob/master/src/stylus/cozy-ui/app/forms.styl#L73-L84.

This way, we can support the checkbox as well as the aria-checked state.

Tip: this one shuld be converted to webcomponent when we add support for them.

**Comment by poupotte** [comment]
@m4dz :  Is this issue still relevant ?

**Comment by m4dz** [comment]
It's done, thanks to #19 :+1:
