### ISSUE TITLE
tests failed: No output has been received

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1413]
It seems that since the puppeteer upgrade (from v1 to v2), we have sometimes a failure "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself." 

A workaround is to relaunch the test

**Comment by ptbrowne** [comment]
Je viens d'essayer https://github.com/cozy/cozy-ui/commit/c0c5e2a1340ed5c02e08610c99c140bb03e583d2 , on verra si ca règle le problème.

**Comment by ptbrowne** [comment]
Toujours pas :/ https://travis-ci.org/github/cozy/cozy-ui/builds/667624006?utm_source=github_status&utm_medium=notification

**Comment by y-lohse** [comment]
Je ne sais pas si ca arrive toujours au meme moment ou pas, la dernière fois que ca m'est arrivé:

```
The command "yarn screenshots --viewport desktop" exited with 0.
$ yarn screenshots --no-empty-screenshot-dir --viewport 300x600
yarn run v1.15.2
$ node scripts/screenshots.js --screenshot-dir ./screenshots --styleguide-dir ./build/react --no-empty-screenshot-dir --viewport 300x600
Browser opened and set up
Opening page file:///home/travis/build/cozy/cozy-ui/build/react/index.html
Extracting links
Screenshotting components
Screenshotting BarButton at 300x600
```

**Comment by ptbrowne** [comment]
This should be reopened right ? From https://github.com/cozy/cozy-ui/pull/1425#issuecomment-608342971 I think we are still failing, GitHub closed the PR because of the "fix" mention in the PR.

**Comment by ptbrowne** [comment]
Ca fait longtemps qu on a pas eu ca non ? On ferme ?

**Comment by y-lohse** [comment]
Effectivement 🤞
