### ISSUE TITLE
ActionMenu placement improvements

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#1430]
From #1424 and https://github.com/cozy/cozy-ui/pull/1424#pullrequestreview-386308526 : The ActionMenu needs a special prop when it is rendered in a modal for example, but the component user should not have to think of that.

The proposed solution is to expose a PopperContext, used by ActionMenu to set the `containerElRef`, and the ref would be set in the PopperContext by the Modal for example.

**Comment by ptbrowne** [comment]
This has been fixed by https://github.com/cozy/cozy-ui/commit/53ef6da1b99df6a4e4fd7fa20327fb3ee9890167 🎉
