### ISSUE TITLE
Tabs should grow on mobile

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1444]
At the moment, tabs are not growing on mobile, they should.

Here is a mockup of the expected behavior :  https://jsbin.com/wadolep/edit?html,css,js,output

- On desktop, tab size is controlled by content. Tabs will not stretch.
- On mobile tab size is the same for all tabs, and they will stretch to fill all the space

**Comment by joel-costa** [comment]
lgtm

**Comment by ptbrowne** [comment]
They do grow on mobile now. See #1472
