### ISSUE TITLE
Doc: Le viewer n'affiche pas l'image

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1490]
https://docs.cozy.io/cozy-ui/react/#/Special?id=viewer

Logiquement on a une image dans les fichiers à afficher, là on se prend une erreur de network. J'imagine qu'un des mocks de CozyClient a du sauter avec les majs de version ? 

(issue à compléter, pense bête pour le moment)

**Comment by JF-Cozy** [comment]
@Crash-- il s'agissait de https://docs.cozy.io/cozy-ui/react/#/Viewer ? C'est maintenant corrigé :)
