### ISSUE TITLE
Remove non transpiled cozy-ui from dist package

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1492]
Our apps now should now use the transpiled version of cozy-ui.
If they are not using it, it is a mistake that should be
known and fixed.

I think it is time now to remove the non transpiled "react"
folder from what's shipped on npm.

What do you think ? When this is done we will be able to remove
the cozy-ui specific config from cozy-scripts.

**Comment by y-lohse** [comment]
I think it would be worth checking our most used projects and make sure at least they are using the transpiled version, before making the breaking change. Of course they should have switched a long time ago, but we  should still scope out the extend of the breaking change before comiting to it.

**Comment by ptbrowne** [comment]
- Banks OK
- Home OK (already has an alias from cozy-ui/react to cozy-ui/transpiled/react)
- Store OK (no reference to cozy-ui/react)
- Harvest lib OK (no reference to cozy-ui/react)
- Contacts (6 references to cozy-ui/react, 72 to cozy-ui/transpiled/react), should be OK to migrate
- Settings (Lots of references to cozy-ui/react, PR [here](https://github.com/cozy/cozy-ui/issues/1492))
- Drive (please edit to put the status here)
- cozy-authenticate
- cozy-sharings

**Comment by JF-Cozy** [comment]
Je ferme, Contacts est ok et c'est un sujet maintenant bien connu
