### ISSUE TITLE
Warning for ActionMenu using placement props

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1524]
There is a deprecation warning when using the placement
props for the ActionMenu component.

```
<ActionMenu placement /> is deprecated, use <ActionMenu popperOptions={{ placement }} /> instead
```

The problem is that there is defaultProps.placement which
means the warning is there even if the user has not used
the placement props.

Can you take a look @y-lhose ?

**Comment by y-lohse** [comment]
Yep, sure! Where are you seeing the warning though? Unless I'm missing something I don't have it in the docs for example.

**Comment by ptbrowne** [comment]
In cozy-libs tests.

**Comment by ptbrowne** [comment]
I also have it in the docs.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/465582/91048148-7cc4d000-e61b-11ea-8be0-0b6a4bbaeaec.png">

**Comment by y-lohse** [comment]
Thanks, got it! Not sure why it wasn't there beforehand.
