### ISSUE TITLE
Bold component should not use u-title-h4

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1527]
https://github.com/cozy/cozy-ui/pull/1525#discussion_r475584423

> I think it's a mistake for bold to use title-h4 in the first place though. It shouldn't be coupled to a title class,

**Comment by ptbrowne** [comment]
We should use Typography components now, Bold should not be used anymore. [This codemod](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-codemods/src/transforms/transform-typography.js) can be used to automatically migrate Text components to Typography components.
