### ISSUE TITLE
Add utility classes

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1555]
- [x] u-card : giving a silver outline
- [x] u-stack-{s,m,l,xl}
- [x] u-elevation-1: uses the raised-12 box-shadow

https://github.com/cozy/cozy-stack/pull/2634/files

**Comment by nono** [comment]
* Add documentation for `u-stack-m` on https://docs.cozy.io/cozy-ui/styleguide/section-utilities.html
