### ISSUE TITLE
On the stack example page, fields are not correctly rendered

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1580]
### Context

Thanks to https://github.com/cozy/cozy-ui/pull/1579, we now have
a screenshot of one of the page used by the stack.

### Problem

The text field used on this page is using custom CSS classes from
the stack; since those classes are not present in this repo, the field
looks broken.

### Solution

- [ ] Re-implement the example with classes from cozy-ui
- [ ] Use those classes in cozy-stack so that cozy-ui and cozy-stack
  use the same code

**Comment by nono** [comment]
Cozy-stack now uses cozy-bootstrap for styling its pages, not cozy-ui. Let's close this issue.
