### ISSUE TITLE
SelectBox should be able to have options with and without actions

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#1587]
For now, when we pass a particular "option" component to SelectBox, all options are impacted in the same way.
We may need to have actions only on some options, not all of them. We should therefore for example be able to pass `<Options />` or `<ActionsOption />`.

**Comment by ptbrowne** [comment]
Can you share an example of usage ?

Is it not possible to achieve with a simple wrapper ? 

```
const EnhancedOption = props => {
  return shouldShowActionOption(props) ? <ActionOptions {...props} /> : <Options {...props} />
}

<SelectBox components={{ Option: EnhancedOption }} />
```

**Comment by Crash--** [comment]
@JF-Cozy can we close this issue ? Since the solution proposed by @ptbrowne is implemented here https://github.com/cozy/cozy-contacts/blob/master/src/components/GroupsSelect/SelectBox/Option.jsx#L32-L37 ?
