### ISSUE TITLE
RemoveScrollLock / Body Scroll Lock

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1599]
Aujourd'hui on lock le scroll sur Body quand on display un Overlay dont le contenu est plus grand que le viewport. 
https://github.com/cozy/cozy-ui/blob/414af1d18fb7161602755af610b58839eb1b0a11/react/Overlay/index.jsx#L24-L27

Ça ne fait pas sens de le faire à ce niveau là car : 
- Un overlay peut avoir un enfant petit (un bottomDrawer dans le cadre d'un ActionMenu sur mobile) et dans ce cas on veut aussi blocker le scroll (donc on se retrouve à avoir ce check dans OVerlay mais à blocker le scroll dans bottomdrawer) 
- Nos Dialogs ne passent plus par Overlay et de ce fait, ne sont pas blockés 

Au final, ça devrait être aux composants plus bas dans l'arbre de savoir s'ils doivent blocker le scroll ou non. Pas à Overlay  

J'ai pas enlevé ce comportement dans https://github.com/cozy/cozy-ui/pull/1597 car je vais prendre le temps de passer sur l'ensemble des composants pour voir s'il faut locker ou pas.

**Comment by JF-Cozy** [comment]
Overlay est déprécié au profit de Backdrop de MUi
