### ISSUE TITLE
Lets dialogs be more flexibles

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-ui#16]
Dialogs are constraint to ()vh (https://github.com/cozy/cozy-ui/blob/095af2a3292cc7e4bd231f1ab6ee3abc64086738/src/stylus/cozy-ui/components/dialog.styl#L29). We probably want to let them grow as long as the content need it.

**Comment by GoOz** [comment]
Not relevant anymore, as the v3 brings a new modal.
