### ISSUE TITLE
Overflow in iOS

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#161]
When you scroll from the bar at the bottom, you can scroll the html container and then the layout is broken.

![bug-ios-scroll](https://user-images.githubusercontent.com/465582/29771149-9a88aca0-8bf2-11e7-95b1-2dbaa30db14b.gif)

**Comment by y-lohse** [comment]
Thanks, @GoOz is actually working on this atm :)

**Comment by ptbrowne** [comment]
I reopen because the layout no longer stays broken thanks to https://github.com/cozy/cozy-ui/pull/162 but you still have the elastic scroll behavior that is weird.

@GoOz Can you confirm that you are aware of the problem ? Are you working on this at the moment ?

**Comment by GoOz** [comment]
@ptbrowne Absolutely not. :(
What do you mean by elastic scroll?

**Comment by ptbrowne** [comment]
![bug-ios](https://user-images.githubusercontent.com/465582/30063531-54cc613a-924f-11e7-9929-19f4dc7c8233.gif)

**Comment by ptbrowne** [comment]
Est ce que t'as une idée pour ça ?

**Comment by GoOz** [comment]
Nope. 😞 
Apparently,
```css
html,
body {
    width: 100%;
    height: 100%;
    overflow: hidden;
}
```
should fix the elastic scroll but since those two elements already have those properties, I guess it doesn't. I have no clue…

**Comment by GoOz** [comment]
The easier way would be to redo the layout but it's still not considered at this point.

**Comment by GoOz** [comment]
New layout for mobile is merged. 🎉
