### ISSUE TITLE
Dialog example improvements

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1611]
- rajouter checkbox pour forcer le fullscreen a false en mobile
- rajouter la possibilité de voir les différentes tailles possibles de modale
- rajouter le footer
- rajouter les deux comportements de scroll

**Comment by JF-Cozy** [comment]
@ptbrowne cette issue est toujours d'actualité ou on peut fermer ?

**Comment by ptbrowne** [comment]
On peut fermer vu qu'on a les nouveaux exemples 🎉
