### ISSUE TITLE
Dialog - Exemples de cas complexes

### ISSUE THREAD

**Issue by joel-costa** [cozy/cozy-ui#1628]
Vu avec @ptbrowne : Mettre en place des exemples de Dialogs complexes dans CozyUI comme :
- La dialog de partage :
![image](https://user-images.githubusercontent.com/36403934/97729163-b100b500-1ad2-11eb-9d45-ddf58ac6884e.png)
- La dialog d'harvest :
![image](https://user-images.githubusercontent.com/36403934/97729398-fcb35e80-1ad2-11eb-970c-b8dc16005bf6.png)

Les exemples peuvent être retrouvés dans le zeplin : https://zpl.io/bAMRBj8

**Comment by JF-Cozy** [comment]
Fait au fil de l'eau, on a rajouté par exemple le BottomSheet et les Dialog imbriquées
