### ISSUE TITLE
Banner - Recettage

### ISSUE THREAD

**Issue by joel-costa** [cozy/cozy-ui#1629]
Les boutons sont trop espacés. Cela est du à 2 facteurs :
- Nos boutons ont des margin à "0 0.25rem". Se serait légitime si on avait des boutons sur fond bleu ou à contours gris mais comme ici on ne compte utiliser que des boutons textuels, passons à une marge de "0"
- Nos boutons ont un min-width de "7rem". Pour corriger ça, 2 solution : Ou bien on passe nos boutons textuels (et seulement les textuels) à une min-width de "3rem" (les 48px minimaux d'une zone de clic confortable au doigt), ou bien on passe TOUS nos boutons à une min-width de "4rem" (ce que fait MUI).

Dans les cas de textes de bouton trop longs, on se retrouve avec des boutons les uns par dessus les autres :
![image](https://user-images.githubusercontent.com/36403934/97733604-5ff3bf80-1ad8-11eb-9236-7dc416c1e023.png)
Est-ce qu'il y a moyen dans ce cas de faire passer automatiquement les boutons en dessous du texte ? (jy crois pas trop ^^)

La banner avec une seule ligne de texte est un peu trop haute (104px). J'ai un gros container qui a un padding à "16px 8px 16px 16px". Il faudrait déjà tout lui passer à "0". Une fois cela fait, j'arrive à une banner qui fait environ 72px de haut (c'est ce qu'il m'avait semblé voir en démo donc quid de ce container que j'ai évoqué juste avant ?). Après il faudrait :
- Passer l'image de gauche à une dimension de 32/32px au lieu de 40/40px
- Passer le text en body2 à la place de body1
- Passer le padding top et bottom du container du texte à 12px au lieu de 8px
- définir une min-height de 56px à la banner
- En desktop, passer le padding gauche et droite de la banner à 32px au lieu de 16px (garder les 16px en mobile) et passer son padding top et bottom à 0px au lieu de 16px
- Mettre un margin: -16px au container des boutons pour les décaler sur la droite

Vu avec @Crash-- : Dans le cas d'un lien dans le texte de la banner, ne pas passer par un bouton mais plutôt par un simple lien

Dans l'exemple mis en place dans Cozy UI, plutôt mettre "no, thanks" ou "later" à la place de "close"

Ca fait beaucoup, je suis dispo si celui qui va traiter l'issue veut voir ça en visio avec moi ^^ désolé

**Comment by ptbrowne** [comment]
s/Synhcroniser/Synchroniser
