### ISSUE TITLE
Exports from react

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#163]
At the moment in my app, I have: 

```js
import Modal, {ModalContent} from 'cozy-ui/react/Modal'
import Button from 'cozy-ui/react/Button'
import {Tabs, TabPanels, TabPanel, TabList, Tab} from 'cozy-ui/react/Tabs'
```

I think it would be better if we could do : 

```js
import {
   Modal, ModalContent,
   Tabs, TabPanels, TabPanel, TabList, Tab,
   Button
} from 'cozy-ui/react'
```

This way we hide the internal structure of `cozy-ui`.

**Comment by ptbrowne** [comment]
I would be even happier with `from 'cozy-ui'` :)

**Comment by GoOz** [comment]
Sure, seems legit, but I don't see what needs to be done to achieve what you want exactly.

**Comment by ptbrowne** [comment]
Exporting the components from react/index.js

I can do the PR.
