### ISSUE TITLE
Better theming support

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1690]
@joel

- Sortir la palette normale en Zeplin correspondant à ce qui est affiché sur [MUI dans default theme](https://material-ui.com/customization/default-theme/)
- Sortir la palette inversée

@ptbrowne 

- [ ] Intégrer la palette normale 
- [x] Intégrer les shadows
- [ ] Intégrer la palette inversée
- [x] Capacité à changer le thème dans le styleguide cozy-ui
- [ ] Capacité des boutons à prendre une couleur d'intent

@JF-Cozy 
- [ ] Déplacer `CozyTheme--normal` dans le style de CozyTheme avec `CozyTheme--inverted`

**Comment by joel-costa** [comment]
Palette :
- Colors : zpl://screen?sid=5fe4a990533d91a50fcf6223&pid=584a6f4e838090371f59518f
- Text : zpl://screen?pid=584a6f4e838090371f59518f&sid=5fe4a98c147d5d95156a0fc4
- Background : zpl://screen?pid=584a6f4e838090371f59518f&sid=5fe4a98c38aa5da09819ae37
- Action : zpl://screen?pid=584a6f4e838090371f59518f&sid=5fe4a99035d909a81b890edd

Shadows :
- zpl://screen?pid=584a6f4e838090371f59518f&sid=5fe4a99035d909a81b890edd

Typography :
- zpl://screen?pid=584a6f4e838090371f59518f&sid=5f847db6ddbc522f0623da20

**Comment by ptbrowne** [comment]
Pour info, les liens ne fonctionnaient pas, re-regarde https://guides.github.com/features/mastering-markdown/#syntax "Links".

**Comment by ptbrowne** [comment]
Dans le readme du plugin, plusieurs liens intéressants dont OpenColor http://opencolor.tools/learn.html

**Comment by ptbrowne** [comment]
Pour les ombres, y-a-t il un moyen simple de me les partager autrement que par un Zeplin, c'est pas pratique d'extraire les styles depuis Zeplin.

**Comment by joel-costa** [comment]
Concernant l'utilisation des couleurs, je t'ai ajouté l'équivalent de cette page MUI : https://material-ui.com/system/palette/
- Color : https://zpl.io/aXllYqM
- Background Color : https://zpl.io/brdd1OW

J'utilise la notion de "main" mais contrairement à MUI, nous n'avons pas de "dark", "main" et "light" mais tout un dégradé de "50", "100", "200" etc. Est-ce que ça vaudrait le coup de rajouter cette notion de "main" en plus pour désigner la couleur principale parmi le dégradé ?
À noter aussi que contrairement à MUI, je fais varier la couleur principale en dark mode (comme préconisé sur material.io : https://material.io/design/color/dark-theme.html#ui-application )
"text.primary", "text.secondary" et "text.disabled" reprennent cette spec : https://zpl.io/VOl5nl1 (je me suis permis d'ajuster  l'opacité par rapport à ce que je t'avais linké avant les vacances, ça colle mieux avec notre existent)
Autre question, qu'est-ce qu'on fait de info.main ?

Je t'ajoute aussi l'équivalent du composant d'alert de MUI : https://material-ui.com/components/alert/#alert
- https://zpl.io/V177M1m
MUI permet déjà la variation de couleur entre le light-mode et le dark-mode pour ce composant.

**Comment by ptbrowne** [comment]
Il faut bien qu'on différencie la notion de teintes qu'on a et la notion de palette. Via material ui pour un thème, il faut obligatoirement avoir par intention, au moins la variante `main` et possible `light` et `dark`.

> As in the example above, if the intention object contains custom colors using any of the "main", "light", "dark" or "contrastText" keys, these map as follows:

    If the "dark" and / or "light" keys are omitted, their value(s) will be calculated from "main", according to the "tonalOffset" value.
    If "contrastText" is omitted, its value will be calculated to contrast with "main", according to the "contrastThreshold" value.
 
> Est-ce que ça vaudrait le coup de rajouter cette notion de "main" en plus pour désigner la couleur principale parmi le dégradé ?

Oui il faudrait, par thème, savoir quelle est le main / dark / light par "intention"

>  À noter aussi que contrairement à MUI, je fais varier la couleur principale en dark mode (comme préconisé sur material.io : material.io/design/color/dark-theme.html#ui-application )

OK, ca revient à choisir une teinte différente pour primary.main dans le thème dark, pas de soucis.

>  Autre question, qu'est-ce qu'on fait de info.main ?

Je ne comprends pas la question.

**Comment by JF-Cozy** [comment]
Nous avons fait un lourd travail depuis pour la gestion des thèmes. Tous les composants réagissent correctement au normal / inverted. Il y a un certains nombres d'outils cités (zepplin, sketch) que nous n'utilisons plus (au profit de Figma).

Reste à gérer le dark mode, qui n'est pas encore implémenté.
