### ISSUE TITLE
Dépréciations et améliorations sur le thème

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1692]
Composants à améliorer vis à vis du thème inversé

- [x] HistoryRow
- [x] UploadQueue
- Chip (utiliser material ui chip, déprécier le notre)
- Checkbox
- Field (celui Cozy)
- SelectBox
- Radio
- InfosCarrousel
- Sidebar
- Stepper (exemple)
- Banner
- ContactsList

Composants à déprécier et à mettre dans une section dédiée "Déprécié".

- [x] InlineCard (utiliser Paper)
- [x] ThresholdBar
- [x] Well
- [x] BaseText
- [x] ContextHeader
- [x] BannerClient
- OrderedList
- UnorderedList
- Overlay

**Comment by ptbrowne** [comment]
from @JF-Cozy 

Quelques éléments que j'ai noté sur le theme inversé :

    la couleur error est un espèce de rose pâle, est-ce normal ?
    les icones dans les bagdes disparaissent
    les icones / textes qui étaient bleus sur fond clair (gris ou bleu pâle) deviennent blanc sans que le fond ne change de couleur => problème de lisibilité
    Progress linear est blanc sur fond blanc
    ProgressionBanner n'a plus son bottom border
    Circle est bleu sur fond bleu
    ActionMenu ne bascule pas en theme inversé

**Comment by JF-Cozy** [comment]
Tout est maintenant correctement géré
