### ISSUE TITLE
Better Empty Component

### ISSUE THREAD

**Issue by flohhhh** [cozy/cozy-ui#1701]
Have the possibility to hide Icon in Empty Component

Change Also Empty PropType :
 - icon: iconPropType.isRequire => icon: iconPropType

**Comment by JF-Cozy** [comment]
@flohhhh on peut fermer ici suite à https://github.com/cozy/cozy-ui/commit/04ad6d9c2bd03c3bfc939c1ecedaef2c3734bccb ou c'était un autre sujet ?
