### ISSUE TITLE
Hero style

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#171]
I think it would be good to standardize the way we do onboarding screens. We have several screens like that in labs apps. Do you also have that in Photos, Drive ?

Introducing `.hero`, `.hero__icon`, `.hero__title`, `.hero__subtitle` could be a good way to do that.

![image](https://user-images.githubusercontent.com/465582/30155104-432818e8-93bc-11e7-92b2-9b15d6eafa23.png)

**Comment by GoOz** [comment]
Why not. If it's used a lot it makes sense.

**Comment by ptbrowne** [comment]
We can start from https://gitlab.cozycloud.cc/labs/cozy-bank/commit/c44faac73a499d0dbe43839033d4976b26b523d3
