### ISSUE TITLE
Stack - "m" missing

### ISSUE THREAD

**Issue by joel-costa** [cozy/cozy-ui#1712]
Sur le composant "stack" : https://docs.cozy.io/cozy-ui/react/#/Basics?id=stack

La liste d'exemples n'est pas exhaustive. Est-ce qu'on pourrait rajouter l'option "m" ?

**Comment by ptbrowne** [comment]
C'est l'option par défaut montré au dessus, ca pourrait être plus clair sur l'exemple.
