### ISSUE TITLE
AppIcon & getIconURL

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1723]
ATM, AppIcon use its own implementation of `fetchIcon` https://github.com/cozy/cozy-ui/blob/master/react/AppIcon/index.jsx#L60 through `Preload`

But this Preload method constructs the image's url here : https://github.com/cozy/cozy-ui/blob/master/react/AppIcon/Preloader.js#L36-L42

It works great on a web environnement since the request will be : foo.mycozy.cloud/registry/slug/icon and in that case, if you are connected to your cozy, the cookie is send with the request so the stack accepts it.

But when using AppIcon in a mobile application, we don't have any cookie. So we need to use a custom fetchIcon. We can use the one from Cozy-Client https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/getIconURL.js and I'm wondering if we should not use this one as the default? WDTY ?

**Comment by ptbrowne** [comment]
Yes, the getIconURL seems more complete in stackClient.

The getIconURL from cozy-stack-client is the one used by harvest. And we use the KonnectorIcon from harvest in banks to show account icons. 🥴. It would sure be simpler if the defualt getIconURL was the one from cozy-stack-client.
