### ISSUE TITLE
Should all the components be given any property ?

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#1730]
Afin de passer par exemple la prop `data-testid` ? Ce qui éviterait de devoir wrapper le composant autours d'un span/div

**Comment by ptbrowne** [comment]
I suggest to refocus the issue on "component" testability. I am not sure that enlarging this to "any property" has much sense.
I have to check on mui side, but I think that it depends on the type of components.

AMHA the generic thing to do would be:

- Atomic components should forward their props to underlying component
- Molecule components should have "innerComponentProps" style props that allow to pass props to child components

For example here for AppIcon, that has a loading state and a default state, I think we should have a way to pass props to the loading state as well as the loaded state. I am not sure if it makes sense to have loadingProps or loadedProps through, forwarding props directly in the case of this simple components seems to make more sense.
