### ISSUE TITLE
Erreur avec Material-UI

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1731]
Bonjour,
Après une mise à jour de cozy-ui `44.7.0` depuis la version `35.45.0`, nous rencontrons cette erreur: 
![Erreur cozy-ui](https://image.noelshack.com/fichiers/2021/05/4/1612456799-erreur.png)

Le problème vient bien d'ici : https://github.com/cozy/cozy-ui/blob/master/react/MuiCozyTheme/theme.js#L90
Plus précisément du faite que certaines variables CSS récupérées via https://github.com/cozy/cozy-ui/blob/master/react/utils/color.js#L5, ne doivent pas être initialisées lors de cette exécution et de ce faite certaines valeur de `normalPalette` sont vide (`''`), ce qui provoque une erreur dans la version de `Material-UI` qui est actuellement sur `cozy-ui`

Je pense que le fix le plus important est déjà de bien récupérer toutes les valeurs CSS, je n'ai pas de solution viable à cet instant.
Pour information, pas forcément très utile, voici les variables non récupérées:
```
primaryColorDark
errorColor
secondaryColorLight
secondaryColor
secondaryColorDark
secondaryContrastTextColor
primaryTextColor
secondaryTextColor
```

**Comment by ptbrowne** [comment]
Bonjour, avez vous bien inséré la stylesheet cozy-ui ?

Voir :

https://github.com/cozy/cozy-banks/blob/75badc481b9ec813c451b36f6e5712b291f4d52f/src/main.jsx#L7

Cette feuille de style injecte les variables CSS dont a besoin le thème.

**Comment by Merkur39** [comment]
Nous avons bien cet import, mais ce dernier est dans le composant App...
Nous avons du le changer de place lorsque nous avions créé un nouvel Index (public), il y a quelques mois.
Je n'y pensais plus du tout, tout marche bien en le remettant dans les 2 index

Merci pour votre aide!

**Comment by Crash--** [comment]
Et si jamais tu rencontres la même dans tes TU (genre)
```
Material-UI: the color provided to augmentColor(color) is invalid.
    The color object needs to have a `main` property or a `500` property.
```

Hésite pas à mocker comme ceci : 
```
jest.mock('cozy-ui/transpiled/react/utils/color', () => ({
  getCssVariableValue: () => '#fff'
}))
```

**Comment by Merkur39** [comment]
@Crash-- Oui j'ai pu le voir durant mes recherches.. :)
Merci!
