### ISSUE TITLE
Undefined colors in MUI theme

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1774]
:wave:

I just bootstrapped an app using create-cozy-app. Since the cozy-ui version was outdated (v37.8.0), I upgraded it by running `yarn upgrade cozy-ui@latest --exact`. It upgraded cozy-ui to v47.3.0, which is the latest version as of today.

Then I tried to start my app with hot reload by running `yarn start` (which runs `cs start --browser`). It built with success, but when I opened the app in my browser, I got the following error:

```
Uncaught Error: Material-UI: The color provided to augmentColor(color) is invalid.
The color object needs to have a `main` property or a `A400` property.
```

I then tried to build the app for production, and there was no problem at all.

By commenting out stuff, I found that the problem is in these lines : https://github.com/cozy/cozy-ui/blob/master/react/MuiCozyTheme/theme.jsx#L100-L108

If I add the following `console.log` before:

```jsx
console.log({
  errorColor: getCssVariableValue('errorColor'),
  secondaryColor: getCssVariableValue('secondaryColor'),
  secondaryColorLight: getCssVariableValue('secondaryColorLight'),
  secondaryColorDark: getCssVariableValue('secondaryColorDark'),
  secondaryContrastTextColor: getCssVariableValue('secondaryContrastTextColor'),
})
```

When I build for development, all these colors are empty strings. But when I build for production, the colors are correctly set.

I looked changelogs [from v37.8.0 to v47.3.0](https://github.com/cozy/cozy-ui/compare/v37.8.0...v47.3.0) but I didn't see any breaking change related to this. I hope I didn't miss anything :crossed_fingers:

**Comment by ptbrowne** [comment]
Hey 👋 Mmh, this is unfortunate that this happens after bootstrapping an app. In the generated app, is there an import of the cozy-ui CSS files ?

```
import 'cozy-ui/transpiled/react/stylesheet.css'
```

Try to add this line the earliest possible. We should find a way not to have this problem, it is not the first time that we have this kind of problems.

**Comment by drazik** [comment]
Yes there was ah import of the CSS files. But it was after the import of some cozy-ui react components. Moving it before all other imports fixes the problem.

**Comment by ptbrowne** [comment]
I am closing as the original issue has been fixed in cozy-scripts, thanks for reporting 🎾 !
