### ISSUE TITLE
Use Snackbar instead of Alerter + AppProvider

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1797]
Material-UI already provides a way to show {success,warning,info} alerts, it would remove code from cozy-ui if the Alerter system used it.

https://material-ui.com/components/snackbars/#snackbar

The examples in the material-ui documentation show declarative code, but at the end of the page, notistack is shown that uses an imperative API. We could use notistack to replace Alerter.

https://material-ui.com/components/snackbars/#notistack

We would need to wrap our apps into a SnackbarProvider. At this point we start to have a lot of providers in our apps, it would maybe be a good time to export an AppProvider in cozy-ui that provides all the providers we use in our apps.

```
const AppProvider = ({ children, client, locales, lang }) => {

	  return <BreakpointsProvider>
	    <I18n dictRequire={() => locales} lang={lang}>
	      <ThemeProvider>
            <SnackbarProvider>
	          <ClientProvider client={client}>
               { children }
	          </ClientProvider>
            </SnackbarProvider>
	      </ThemeProvider>
	    </I18n>
	  </BreakpointsProvider>
}
```

What do you think ?

**Comment by JF-Cozy** [comment]
fait dans la 70.3.0 https://github.com/cozy/cozy-ui/releases/tag/v70.3.0
