### ISSUE TITLE
Travis timeout

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#1842]
Il est de plus en plus difficile de faire aboutir un build du premier coup : 

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself`

**Comment by Ldoppea** [comment]
Cela semble être lié à la génération des screenshots. Si on prend l'historique tous les builds en fail qui durent 15min (contre 8 pour les success) sont des builds où la génération des screenshots n'affiche que quelques lignes jusqu'à `Extracting links`.

![image](https://user-images.githubusercontent.com/1884255/124961765-28052a80-e01e-11eb-91fd-ff82c82cbe0f.png)

**Comment by Crash--** [comment]
Oui c'est notre script `screenshot.js`. Je pense que pour creuser un peu plus, il faudrait mettre un peu plus de log après ça https://github.com/cozy/cozy-ui/blob/master/scripts/screenshots.js#L105 pour essayer de voir où ça part en sucette.
