### ISSUE TITLE
`Inverted` theme is not correctly handled by some components

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#1846]
Issue liée à https://github.com/cozy/cozy-ui/issues/1692

Listing in progress (only `Basics` and `Special` has been checked)

- ButtonClient
  - Text stays gray
![image](https://user-images.githubusercontent.com/1884255/124948172-c094ae00-e010-11eb-9645-12bc5b534862.png)

- Banner
  - White text on grey background
  - Blue buttons on blue background
![image](https://user-images.githubusercontent.com/1884255/124948498-06ea0d00-e011-11eb-88e8-987d0d95912c.png)

- PasswordExample
 - Numbers are displayed with blue color even with inverted theme
![image](https://user-images.githubusercontent.com/1884255/124948915-69dba400-e011-11eb-950e-b433cd44cf9d.png)

- Double badges and InfosBadges and GhostFileBadge
  - 2nd icon disapears
![image](https://user-images.githubusercontent.com/1884255/124949201-a27b7d80-e011-11eb-9e69-71c8ce77e2fc.png)
![image](https://user-images.githubusercontent.com/1884255/124949217-a6a79b00-e011-11eb-90c0-e717d93bce3a.png)

- Button
  - Some buttons are invisibles in both themes
![image](https://user-images.githubusercontent.com/1884255/124949566-f7b78f00-e011-11eb-98a7-8a6280a7d0db.png)
![image](https://user-images.githubusercontent.com/1884255/124949590-fd14d980-e011-11eb-80f9-1c4f29286a58.png)

- Subtle Buttons
  - cozy icon disappear in inverted
![image](https://user-images.githubusercontent.com/1884255/124949808-2df50e80-e012-11eb-853e-9e1d665d56dd.png)
![image](https://user-images.githubusercontent.com/1884255/124949839-33525900-e012-11eb-96be-df1fcfdfc2f7.png)

- Buttons
  - Primary contained buttons have their icons disappearing
  - Secondary contained buttons have their text disappearing
![image](https://user-images.githubusercontent.com/1884255/124949961-4c5b0a00-e012-11eb-81d3-bc6f47fa0877.png)
![image](https://user-images.githubusercontent.com/1884255/124949978-511fbe00-e012-11eb-8a27-410f866a4fad.png)

- Chip (all categories)
  - Text becomes white
  - Primary has no border
  - Icons become white
![image](https://user-images.githubusercontent.com/1884255/124950252-888e6a80-e012-11eb-8b71-6c3b6dd8cdec.png)
![image](https://user-images.githubusercontent.com/1884255/124950314-9512c300-e012-11eb-9ef3-2a9e402dc011.png)
![image](https://user-images.githubusercontent.com/1884255/124950415-aeb40a80-e012-11eb-90be-5961fa8d06e0.png)
![image](https://user-images.githubusercontent.com/1884255/124950441-b5428200-e012-11eb-89ca-1cfc8275610a.png)

- Fab
  - Icon becomes white
![image](https://user-images.githubusercontent.com/1884255/124950565-cf7c6000-e012-11eb-80ec-1c2a7add81bc.png)

Also some dialogs reflect calling `button`'s parent theme, some doesn't

**Comment by JF-Cozy** [comment]
Pour les `Button` et `Buttons` j'ai commencé une branche `feat/buttons` pour coller au spec de @joel-costa . J'attends la finalisation des specs pour terminer.

**Comment by JF-Cozy** [comment]
Lié à https://github.com/cozy/cozy-ui/issues/1692

**Comment by JF-Cozy** [comment]
Pour la Banner c'est corrigé avec https://github.com/cozy/cozy-ui/pull/1857 . Pour le souci `Blue buttons on blue background` c'est dû aux boutons, pas au Banner.

**Comment by Ldoppea** [comment]
Some new diffs.

Modal list spacing is no the same between normal and inverted
![image](https://user-images.githubusercontent.com/1884255/132659386-d24482b4-a587-4b9d-be5f-1f9b7e38eb52.png) ![image](https://user-images.githubusercontent.com/1884255/132659407-65fa652f-7a65-4eef-b9e6-b936c9a6081e.png)

Modal buttons alignment and title size are differents
![image](https://user-images.githubusercontent.com/1884255/132659614-0d560c17-2945-421c-9d56-61e655e3d7d5.png) ![image](https://user-images.githubusercontent.com/1884255/132659638-ee51ea09-4dae-45aa-82ef-2999c753a58b.png)

**Comment by Ldoppea** [comment]
Inverted theme on ContactsListModal use light theme for close button:
![image](https://user-images.githubusercontent.com/1884255/135121000-5282c5c3-2128-49bd-a6e5-dd8ee4d4675f.png)

**Comment by Ldoppea** [comment]
Not that this commit fixes some of previous examples : 85c90267ff2287f25fd3c48909283e08db6c865f

**Comment by JF-Cozy** [comment]
Je close, tous les composants listés ici ont été corrigés. De plus nous le faisons plus systématiquement au fil de l'eau maintenant, grâce à une meilleure visibilité des différents thèmes directement en dev
