### ISSUE TITLE
Additional informations in the BottomDrawer README

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1847]
Après échange sur cette PR https://github.com/cozy/mespapiers/pull/6#discussion_r666410241, il serait plus clair je pense d'ajouter dans le README du [BottomDrawer](https://github.com/cozy/cozy-ui/tree/master/react/BottomDrawer) que si l'on souhaite faire un menu, il serait préférable de passer par le composant [ActionMenu](https://github.com/cozy/cozy-ui/tree/master/react/ActionMenu).
Des avis ? :)

**Comment by Ldoppea** [comment]
De manière plus générale la doc indique plutôt techniquement ce que les composants permettent de faire mais pas quand on doit être amené à le faire.

Par exemple est-ce qu'on a une convention interne pour définir dans quel cas on favorise un `Progress` linéaire, ou plutôt un circulaire?

Est ce que ça aurait de la valeur de rajouter une catégorie `when/when not` pour chaque composant? en mode :
```
When to use:
- A choice has to be done by the user
- This choice is mandatory

When not to use:
- To display multiple optional actions to the user (instead use ActionMenu)
- To display complex choices (instead use Dialog)
```

cc @joel-costa qui pourra nous dire si c'est quelque chose de facile à résumer dans une doc, voir s'il y a déjà un document (figma?) qui décrit ces cas d'utilisation.

**Comment by joel-costa** [comment]
@Ldoppea c'est pas quelque chose que je suis habitué à faire mais je veux bien essayer. Sur figma j'ai 2 petits champs associés à chaque composant que je peux remplir : un champs de description et un champs pour linker vers une doc
![image](https://user-images.githubusercontent.com/36403934/125074594-ca281f80-e0bd-11eb-9d0a-302c752ca9c6.png)
C'est des infos que vous pourrez retrouver après en inspectant les maquettes.
Pour le lien vers la doc, vous préférez quoi, un lien vers le composant dans https://docs.cozy.io/cozy-ui/react/ ? Un lien vers le README ?

**Comment by joel-costa** [comment]
@Merkur39 Il ne me semble pas que le composant ActionMenu utilise un vrai BottomDrawer, si ?
Moi, de ce que j'avais en tête :
- On avait un faux BottomDrawer (qu'on ne pouvait pas vraiment scroller)
- On a mis en place un vrai BottomDrawer pour le viewer augmenté
- Dès qu'on est content du vrai BottomDrawer, il est sensé remplacer le faux BottomDrawer et donc être utilisé par le composant ActionMenu

Après tout ça a peut-être déjà été mis en place ou le plan a peut-être changé. Je suis pas au courant.

**Comment by Crash--** [comment]
> Dès qu'on est content du vrai BottomDrawer, il est sensé remplacer le faux BottomDrawer et donc être utilisé par le composant ActionMenu

C'est pas un truc qu'on avait dans le viseur. L'API du `BottomSheet` utilisé dans Drive pour le Viewer Augmenté https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/viewer/Footer/BottomSheet.jsx diffère pas mal de l'API de l'ActionMenu. À voir si on arrive à rester compatible avec la bascule automatique entre un Menu et un BottomSheet en fonction du format à partir duquel on consulte. On va regarder ça de plus près https://github.com/cozy/cozy-ui/issues/1848 

Ceci dit, @Merkur39 ça ne change rien à ta problématique. Que ce soit `BottomSheet` plus tard ou le `BottomDrawer` actuel, il faut réussir à faire comprendre au développeur qu'il doit passer majoritairement par un `ActionMenu` qui gère et le web et le mobile. 

@joel-costa le `ActionMenu` d'aujourd'hui utilise un `BottomDrawer`. Ce que tu mets derrière "vrai" est propre à ton interprétation. C'est un bottom drawer qui gère l'inertie du scroll, que tu peux fermer grâce à ça. Par contre, il ne gère pas les snap points ni le scroll à l'intérieur, mais ça reste un bottom drawer ^^'.  

J'aime bien ton idée @Ldoppea de when to use / when not to use. Ça va demander d'être bien attentif quand on supprimera des composants / renommer ou autre, mais ça devrait bien se faire. @joel-costa un lien vers le composant en fullscreen https://docs.cozy.io/cozy-ui/react/#!/Badge serait top !

**Comment by joel-costa** [comment]
@Crash-- OK mais notre `BottomDrawer` est actuellement inutilisable avec des listes trop longue car non scrollable. Dans le cas d'une recatégorisation bancaire par exemple, on ne pourrait actuellement pas l'utiliser :
![image](https://user-images.githubusercontent.com/36403934/125081960-ea101100-e0c6-11eb-97ba-9a2431b5842b.png)

Qu'on utilise ou non `BottomSheet`, moi ça m'importe peu, ce qui m'importe c'est d'avoir un `bottomDrawer` utilisable en cas de liste trop longue (liste de catégories bancaire, liste de comptes bancaires, liste d'actions sur un fichier dans drive...)
Actuellement la liste d'actions sur un fichier dans drive n'a pas besoin d'être scrollée, mais le jour où on voudra ajouter de nouvelles actions ou 
![image](https://user-images.githubusercontent.com/36403934/125083678-f8f7c300-e0c8-11eb-8475-81770005c99b.png)
corriger la hauteur des items en les passant à 48dp, on pourra être embetté :/

**Comment by Crash--** [comment]
@joel-costa On est bien d'accord sur le besoin. Mais aujourd'hui ce composant n'existe pas dans UI et on ne sait pas le convertir à la volée depuis un ActionMenu sur nos menus déjà existants. D'où l'issue #1848 qui sera traitée à l'occasion / opportunité. J'ai bien le sujet en tête maintenant ;).

Ne dévions pas trop du sujet initial de cette issue qui est important et qui ne mérite pas d'être noyé dans cette discussion. On a besoin d'aiguiller nos dév sur les composants à utiliser et à quel moment et quand ne pas les utiliser.

**Comment by Merkur39** [comment]
> Est ce que ça aurait de la valeur de rajouter une catégorie `when/when not` pour chaque composant?

J'aime bien cette idée également 👍

**Comment by JF-Cozy** [comment]
Concernant le sujet initial, @Merkur39 peux-tu faire une PR pour modifier la doc si tu sens que c'est nécessaire stp ?

Concernant l'autre sujet, il y a effectivement une autre issue, qui sera adressée prochainement maintenant que le BottomSheet est fonctionnel.
