### ISSUE TITLE
Make DialogActions optional for CozyDialogs

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#1861]
When using CozyDialogs, if no action is provided then the `<DialogActions>` is empty but is still rendered.

This produce a blank space (for `Dialog`) or en empty bordered container (for `FixedDialog`).

Example for `Dialog`
![image](https://user-images.githubusercontent.com/1884255/128490979-072beff9-52c2-4083-abed-8e24a2bea241.png)
![image](https://user-images.githubusercontent.com/1884255/128490990-79bc7e56-f0a7-4853-b4fb-1ade5f0db8e4.png)

Example for `FixedDialog`
![image](https://user-images.githubusercontent.com/1884255/128491021-5c598291-8caa-43c8-a0f3-acec256135e2.png)

Proposal : 
Render the `<DialogActions>` only when the `actions` prop is defined and non-empty.

**Comment by Merkur39** [comment]
J'en profite pour signaler un autre point sur le `DialogActions`, lorsque les boutons sont affichés en colonne, celui du haut garde une marge à gauche de 4px, ce qui le décentre légèrement.

![Capture d’écran 2021-08-06 à 11 40 24](https://user-images.githubusercontent.com/14182143/128492484-055dab81-d53b-4ce1-aa81-9c81daf15229.png)
