### ISSUE TITLE
Fix the margin on a DialogActions button

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1864]
Lorsque les boutons sont affichés en colonne, celui du haut garde une marge à gauche de 4px, ce qui le décentre légèrement.

![Capture d’écran 2021-08-06 à 11 40 24](https://user-images.githubusercontent.com/14182143/128492484-055dab81-d53b-4ce1-aa81-9c81daf15229.png)

**Comment by Ldoppea** [comment]
Ignore those Github warnings, I linked the wrong issue in my PR

**Comment by JF-Cozy** [comment]
fix https://github.com/cozy/cozy-ui/pull/2159
