### ISSUE TITLE
Direct dep to material-ui

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1865]
Aujourd'hui Cozy-UI n'a qu'une peerDep et devDep sur Material-UI. Ce qui fait que les applications qui consomment Cozy-UI pour ses composants basés sur M-UI doivent installer material-ui par elle-même.

Contexte: 
Cozy-UI a d'abord était une lib CSS puis a ensuite migré vers fournir des composants React et CSS/stylus puis et maintenant une lib fortement basée sur material-ui pour tous les composants React. 

Sur Cozy-UI nous sommes dans la démarche de supprimer le code écrit pour les composants non basés sur material-ui pour ré-utiliser leur composant mais en les thémant à la sauce Cozy. 

Nous avons aussi décidé que Cozy-UI n'assurait plus le fait de fournir les classes stylus correspondants aux composants et que seules les applications React étaient maintenant supportées. À la base, des applications comme la stack ou la nuagerie utilisaient les CSS de cozy-ui pour recréer des composants d'UI sans avoir besoin d'utiliser React. Maintenant ces applications utilisent cozy-bootstrap https://github.com/cozy/cozy-bootstrap

Vu que Cozy-UI était utilisé dans des applications non react, nous ne voulions pas grossir la taille du bundle pour elles, et donc les applications qui voulaient les composants "mui" devaient installer par elles-mêmes m-ui. 

Il est grand temps de mettre m-ui en dépendance directe de cozy-ui. Qu'en dites-vous ? Des avis contraires ? 

@Merkur39 Ton avis m'intéresse fortement car tu as bossé sur une app non Cozy qui n'utilisait pas les composants de Cozy-UI mais qui l'importait quand même. C'était pour quoi ?

**Comment by JF-Cozy** [comment]
Je suis pour, cozy-ui devrait être autonome et suffisant, lorsqu'on l'importe dans les app.

Je sors un peu du sujet mais je pense aussi que cozy-ui est compliqué aujourd'hui avec différentes approches : MUI, stylus, variable css, styleguide.

@joel-costa travaille de son côté en ce moment sur la mise au propre des bases (palette, thème) de la partie MUI, on devrait voir arriver prochainement des specs claires à ce sujet. On pourra donc refaire une passe côté cozy-ui pour mettre en cohérence (aujourd'hui par exemple on n'utilise pas la bonne palette de couleur).

MUI étant la référence maintenant, on devrait baser notre stylus dessus.

**Comment by Crash--** [comment]
> MUI, stylus, variable css, styleguide.

Si on mélange les torchons et les serviettes, ça fait pas une bonne soupe. On parle de plein de choses différentes là. 

Styleguidist n'a rien à voir dans l'histoire. C'est pas une approche différente. Styleguidist c'est juste un outil pour afficher les composants. Je vais pas m'étaler sur les autres, mais c'est pareil 

> MUI étant la référence maintenant, on devrait baser notre stylus dessus.

On en rediscutera au moment opportun, aujourd'hui notre thème MUI se base exclusivement sur nos variables CSS. Idem pour nos fichiers stylus. Si y a des endroits ou c'est pas le cas, c'est certainement ça qu'il faudrait changer ;)

**Comment by nono** [comment]
> notre thème MUI se base exclusivement sur nos variables CSS. Si y a des endroits ou c'est pas le cas, c'est certainement ça qu'il faudrait changer ;)

Ce n'est pas le cas pour le thème inversé : https://github.com/cozy/cozy-ui/blob/master/react/MuiCozyTheme/theme.jsx#L656-L681

**Comment by Merkur39** [comment]
> @Merkur39 Ton avis m'intéresse fortement car tu as bossé sur une app non Cozy qui n'utilisait pas les composants de Cozy-UI mais qui l'importait quand même. C'était pour quoi ?

En effet, nous l'utilisions principalement pour `useI18n` & `Icon`, puis sur la fin pour le `Viewer`/`IconSprite`/`Overlay`
