### ISSUE TITLE
Screenshots should be able to handle variants

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#1867]
Screenshots testing does not handle all CozyDialogs preview

Also we are now using Variants for many components and it would be great to find a way to easily screenshots all variants.

**Comment by Ldoppea** [comment]
Maybe related to https://github.com/cozy/cozy-ui/pull/1551 ?

**Comment by JF-Cozy** [comment]
Doublons avec https://github.com/cozy/cozy-ui/issues/1738, je close
