### ISSUE TITLE
CozyDialog/Dialog ActionButtons does not display correctly on mobile

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1868]
La modale `Dialog` de `CozyDialog` s'affiche actuellement sur mobile(fullscreen) avec les ActionsButtons collés au contenu, de cette manière:
![Capture d’écran 2021-08-10 à 15 04 34](https://user-images.githubusercontent.com/14182143/128871959-ab7e907a-92d5-4eb4-8e56-39aa3b5eb40c.png)

D'après les specs, et avec confirmation de @joel-costa, elle devrait plutôt :
- En cas de contenu court, garder les boutons d'actions fixé en bas
- En cas de contenu long, les boutons d'actions sont collés au contenu (comme actuellement)

**NB: La maquette n'est plus à jour pour le header, ne pas tenir compte des différences à ce niveau**

![Capture d’écran 2021-08-06 à 17 26 52](https://user-images.githubusercontent.com/14182143/128534799-8d57193c-0110-46cf-b459-a7a901dc4152.png)

**Comment by JF-Cozy** [comment]
@Merkur39 tu fais références à l'espace qu'il devrait y avoir entre le contenu et les actions buttons ?

Attention en revanche il n'est pas censé y avoir un croix de fermeture et une flèche back dans le titre. Les maquettes sur Zeplin sont un peu ancienne, il y a eu un paper de référence entre temps, dans lequel on spécifie bien qu'il y a le back button (flèche back) et pas le close button (croix de fermeture).

Qu'en est-il ?

**Comment by Merkur39** [comment]
>tu fais références à l'espace qu'il devrait y avoir entre le contenu et les actions buttons ?

C'est bien ça, j'ai clarifier l'issue :)

**Comment by JF-Cozy** [comment]
Ok on ne parle donc que des actions buttons. J'ajoute quelques éléments dans la description pour clarifier également.
