### ISSUE TITLE
Upgrade Empty component

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1871]
Il faudrait rendre possible le choix de la taille de l'illustration dans le composant `Empty`
Le besoin se fait sentir sur l'app Mes papiers mais pourra être utile à d'autres..

Je pense qu'ajouter une prop `iconSize` où l'on pourrait définir la hauteur et la largeur serait bien et de faire varier ces props en fonction (https://github.com/cozy/cozy-ui/blob/master/react/Empty/index.jsx#L40)

**Comment by Crash--** [comment]
Est-ce qu'on a les tailles prédéfinies ? Genre small / medium / large ? Ou est-ce qu'on va avoir des choses différentes à chaque fois ? cc @joel-costa

**Comment by joel-costa** [comment]
Bonne question, je peux vous fournir des tailles prédéfinies (S, M et L) mais à condition que ces tailles prédéfinies ne s'appliquent qu'à la hauteur de l'image. La largeur, elle, serait calculée par conservation du ratio hauteur/largeur de l'image (c'est peut-être ce qui est déjà fait partout mais je préfère le préciser au cas où).

Exemple : 
- S : 96 dp
- M : 128 dp
- L : 160 dp

- J'ai un svg qui fait de base 32x32 => Je le passe en S donc sa hauteur va passer à 96 dp et donc sa largeur à 96 dp
- J'ai un svg qui fait de base 48x32 => Je le passe en S donc sa hauteur va passer à 96 dp et donc sa largeur à 144 dp

Est-ce que ce serait OK pour vous ?

**Comment by Merkur39** [comment]
Pas de soucis, on s'occupe du changement dès qu'on a ton feu vert avec les specs 👍

**Comment by joel-costa** [comment]
Top

Nouvelle spec : https://www.figma.com/file/7e3nYZkJUGZ7SLqy8xWbqx/Cozy-UI?node-id=741%3A27455

**Comment by joel-costa** [comment]
La size par defaut est `small`
C'est la size qui sera utilisée pour tous les composants `empty` qui sont déjà utilisés dans nos apps. Ça produira une légère variation de taille par rapport à l'existant (passage de 105 à 96 en mobile et de 140 à 128 en desktop) mais cette variation devrait être trop légère pour se faire ressentir.
