### ISSUE TITLE
Add a new semantic color for dividers

### ISSUE THREAD

**Issue by acezard** [cozy/cozy-ui#1895]
The following color is required in new designs: `#D6D8Da` / `var(--silver)`. At this moment it does not exist in usable semantic var, but only in legacy button variables. It is suggested to add something following this pattern `--dividerColor: #1D212A1F // grey[900] with 12% opacity`, maybe `dividerColorLight`? Not sure, it opens the door to a lot of variations (lighter, lightest...)

**Comment by Crash--** [comment]
cc @joel-costa

**Comment by Crash--** [comment]
@acezard we can close this issue right? Since dividerColor exists? https://github.com/cozy/cozy-ui/blob/9d1faedb053fae2285141b11124990a2f116ee37/stylus/settings/palette.styl#L201
