### ISSUE TITLE
[Empty] Remove layout property

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1896]
La prop `layout` du composant `Empty` est dépréciée depuis bientôt un an, ce dernier sert à "centrer" le composant en affichage Mobile via https://github.com/cozy/cozy-ui/blob/1a2d0ffb345c590b62aec6c3974a163446470644/stylus/components/empty.styl#L17-L19

Ce type de "centrage", n'est pas très viable et cause des soucis avec Argos où l'on ne retrouve pas du tout les mêmes résultats (issue relevant déjà le problème https://github.com/cozy/cozy-ui/issues/1386)

Actuellement la prop `layout` est à `true` par défaut, je pense qu'il faudrait la supprimer et que les apps qui feront l'upgrade devront gérer la position de ce composant sur un composant parent (via `flex` ou autre)

**Comment by Crash--** [comment]
Faisons la passer à false par défaut en créant un BC et en disant que si besoin faut passer layout à true? Comme ça, on migre doucement ?

**Comment by Merkur39** [comment]
Que penses-tu de simplement l'enlever des `defaultProps` ?
- Si défini à `true` => `warning: "layout" prop on Empty component is deprecated. Please add a style to the parent component for manage the position of the empty component and remain compatible with future major versions of cozy-ui`

- Si défini à `false` => Aucun warning, puisque qu'il n'y aura aucuns changements dans ce cas là, et le jour ou `layout` sera supprimé du composant, il y aura un warning de React.

- Si non défini => `warning: "layout" prop on Empty component is deprecated. For keep the margin top of Empty component (on Mobile), you can set "layout" prop to "true" but prefer add a style to the parent component for manage the position of the empty component and remain compatible with future major versions of cozy-ui`

**Comment by Merkur39** [comment]
Voici une PR dans cette idée => https://github.com/cozy/cozy-ui/pull/1898
