### ISSUE TITLE
Back button should close dialogs

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#1903]
Browser's back button doesn't close dialogs. Navigation occurs with dialog staying open.

On desktop:
https://user-images.githubusercontent.com/1884255/133454118-389f3512-49df-4df0-bc49-69aa6fe86220.mp4

On mobile:
https://user-images.githubusercontent.com/1884255/133454187-2b55b3b0-193a-4b6a-9fa3-3581495b06ae.mp4

Ideally back button should close the dialog without navigating back. Bonus point if it is able to navigate back on multi steps dialogs.
If not possible, it should navigate back AND close the dialog.

**Comment by JF-Cozy** [comment]
C'est un sujet complexe qu'on est en train d'adresser en ce moment, cela touche le router principalement et pas tellement les Dialogs
