### ISSUE TITLE
ListSubheader : mobile style

### ISSUE THREAD

**Issue by Merkur39** [cozy/cozy-ui#1931]
Le composant `ListSubheader` à la propriété `text-indent` dans sont style qui est fixée à `2rem`.

Après échange avec @joel-costa, il faudrait changer cette valeur à `1rem` en version mobile

Actuellement : 
![Capture d’écran 2021-10-26 à 17 11 01](https://user-images.githubusercontent.com/14182143/138908216-edef58cb-d429-428d-af4e-e20d5e7bc543.png)

Attendu :
![Capture d’écran 2021-10-26 à 17 10 11](https://user-images.githubusercontent.com/14182143/138908301-9e17bea2-e9ab-47bd-8d26-12d416f68242.png)

**Comment by JF-Cozy** [comment]
C'est corrigé, la doc est à jour. Attention il y avait à l'époque une mauvaise compréhension de l'utilisation des List. Bien relire la doc pour se mettre à jour si nécessaire.
