### ISSUE TITLE
margin-bottom sur les actions d'un dialog en mobile

### ISSUE THREAD

**Issue by joel-costa** [cozy/cozy-ui#1937]
Sur l'application mes papiers, dans le parcours d'ajout d'un papier, nous avons les boutons du bas trop près du bord :

![image](https://user-images.githubusercontent.com/36403934/139292182-bad77443-a802-4ecd-8c32-575ccb18cba6.png)

Ils sont sensés être espacés de 16dp par rapport au bas de l'écran.
Exemple : https://www.figma.com/file/8y78G7PcOVtdvesULHda6d/Mes-Papiers---Specs?node-id=4%3A45503

**Comment by Crash--** [comment]
Cette modale est implémentée de 0 dans Mes Papiers car la CozyDialog n'a pas les actions collées en bas par défaut. 

Donc on va corriger le souci là-bas et quand on mettra à jour la CozyDialog ici on en tiendra compte
