### ISSUE TITLE
property withCross of the Modal

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#198]
I open this issue to discuss about this property which is currently badly implemented for me according to these points:

* The naming, `withCross` just means nothing for me, it would be preferable to have something named like `withClosingButton` IMHO
* The behaviour. For me, this property should just decide if the modal should display a closing button or not and THAT'S ALL. I really think that this property should not affect the key listener and the click outside listener used to close the modal. For this specific need, we could use a better property named `disallowClosing` which is more appropriate for here to my mind.

#my2cents

**Comment by gregorylegarec** [comment]
👍 
I made this branch a long time ago but I never pull-requested it. Please take all you need from it. https://github.com/gregorylegarec/cozy-ui/commits/feat/deprecate-modal-withcross

**Comment by ptbrowne** [comment]
I agree that the naming is bad.

To me a modal should be `closable=true` by default. The `closable` property would also control that the close button is shown and that the modal can be closed by clicking outside.

**Comment by ptbrowne** [comment]
On your properties `withClosingButton` and `disallowClosing` : I do not understand the interaction between your properties and am generally in favor of reducing the API of a component.

For example with your names, what happens when `disallowClosing=true` and `withClosingButton=true` ?

**Comment by ptbrowne** [comment]
@enguerran It seems to me by looking at the history that you added the `withCross` property.  What do you think ?

**Comment by CPatchane** [comment]
> On your properties withClosingButton and disallowClosing : I do not understand the interaction between your properties and am generally in favor of reducing the API of a component.

@ptbrowne I agree but I could need the clickoutside without the cross button if the cross button is already handled by the intent itself.

**Comment by enguerran** [comment]
I think THERE IS NO NEED for uppercase in issue content.
Nevertheless, I can remember I added that when I was working on very short deadline (https://github.com/cozy/cozy-ui/pull/78) and it was good enough in those dark times.
But usage and experience may teach different conclusions and I guess it would be good to upgrade this API.

Let write down a standalone version in the styleguide and see/expose the different and exhaustive wanted usages.

**Comment by gregorylegarec** [comment]
@ptbrowne It is old stuff, but I remember having identified a case where a modal should not be closeable in other way than choosing for two options. But if it's not needed right now let's remove this feature and focus on renaming this prop while keeping retro-compatibility. Go for a pull-request @CPatchane :)

**Comment by ptbrowne** [comment]
> @ptbrowne It is old stuff, but I remember having identified a case where a modal should not be closeable in other way than choosing for two options.

So it is `closable=false` right ?

**Comment by gregorylegarec** [comment]
@ptbrowne Yep

**Comment by ptbrowne** [comment]
Closed via https://github.com/cozy/cozy-ui/pull/237
