### ISSUE TITLE
Using mixins and default stylesheet, not just default stylesheet

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-ui#2]
Bootstrap comes with two versions: a CSS stylesheet and a LESS version. There are also port for other CSS pre-processor.

I think it's a good practice to build first a bunch of mixins, then to build a default stylesheet based on them: you can use the default style, and customize your own style with the mixins.

Also it makes HTMl easier to read, because you use semantic class names (your own) rather than ".cozy-btn", and so on.

**Comment by m4dz** [comment]
We can provide a bunch of various mixins (rather a (maybe) huge and partially useless CSS) that can be used by developers.

We can also provide mixin in jade templates to easily build Ui components effortless.

Can it be a good way?

**Comment by jsilvestre** [comment]
I'm not fond of mixins for jade templates, for the reason that I dream of dropping it (+Backbone.View) in favor of React ;-)
In a more objective (realistic) point of view, it's rather hard to build generic UI components. So if those mixins can be easily customized, why not, otherwise I'd stick to a nice set of tools in stylus, rather than trying to have something that won't be that useful in the end.

To be complete about stylus and mixins, stylus uses "import" like a node's require so it'd be good to split the "css" (stylus) into various files, to avoid having a fat CSS file with many useless stuff, like you said.

An example would be clearer:
- styles/cozy/mixins.styl: set a of stylus mixins 
- styles/cozy/buttons/_button.styl: set of stylus rules that uses mixins and default cozy stuff to build a default CSS
- no actual cozy.css
- (optional, nice to have, I haven't thought about it too much yet) export that to NPM so we can open it with browserify: we don't version the file themselves in Git.

**Comment by m4dz** [comment]
Ok for jade mixins. About React + Backbone.Views (something like this: http://www.thomasboyt.com/2013/12/17/using-reactjs-as-a-backbone-view.html ?), for complex components markups, we could stick to external templates (using jade?) used by the React engine easily.

About a NPM module for the Ui SDK (can it be a good name?), I take it !

**Comment by jsilvestre** [comment]
About React, don't actually think about it. I was just mentioning that I don't like Backbone.View and Jade and I would like to replace them both by React. But we won't drop Backbone.View+Jade like this because that would be too much work. Also, I'm still unsure about the Flux things, I haven't found yet an implementation that I like.

**Comment by m4dz** [comment]
I agree… definitely. And I also think that some apps don't really need to rely on React, which can be too much powered for their use.

**Comment by jsilvestre** [comment]
You are right, but most of our apps could use its magic. Sync doesn't need React, for instance (it's basically a classic HTML page with a bit of JavaScript, so Jade + jQuery is perfectly fine for it), but for bigger applications (basically other Cozy applications), it could be beneficial, theoretically speaking (too much work to rewrite everything, you know^^). Emails is fully powered by React + Flux, but that's the only application (well Tasky is too, but that's my side project).
