### ISSUE TITLE
BottomSheet argos test seems to be flaky

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#2023]
BottomSheet has an entrance animation that should be disabled during argos tests.

Actual behavior:

![image](https://user-images.githubusercontent.com/1884255/150393276-c837dac7-bf3c-4902-ae06-3a7af1aad49f.png)

![image](https://user-images.githubusercontent.com/1884255/150393291-1cefb8ad-e282-4d17-b4d7-a149aef8798c.png)

![image](https://user-images.githubusercontent.com/1884255/150393315-9ce517d1-332d-49a0-9c0c-5ae379e3a552.png)

Example of commit disabling animations on another component. Fix for BottomSheet may be similar: https://github.com/cozy/cozy-ui/commit/6c3f32e7f1f2aa534e11330ca64dd4cf301889eb

**Comment by trollepierre** [comment]
I suggest to play with React Spring Settings to slow the animation: https://docs.pmnd.rs/react-spring/common/configs
