### ISSUE TITLE
Un bout de doc pour la largeur minimale des modales / iframe ?

### ISSUE THREAD

**Issue by Narkfr** [cozy/cozy-ui#205]
Hello !

J'ai recontré un soucis sur l'app "Mon logis", un intent est chargé dans une modale, qui a été fixée a 700px de large par le développeur. Le contenu passe donc systématiquement en mode mobile dans cette modale.

Est-ce qu'on pourrait ajouter à la doc les recommandations pour des modales qui seraient en accord avec nos breakpoints, pour éviter ce genre de soucis ?

Merci !

**Comment by Narkfr** [comment]
Après investigation, le problème vient des iframes, auquelles chaque app / dev passe des width / height différent.

Ça pourrait être utile d'avoir un composant <Iframe /> prêt à l'emploi auquel il suffit de passer une url, et on pourrait dans le même temps améliorer leur accessibilité, pour le moment elles n'ont ni `title` ni role ARIA

**Comment by ptbrowne** [comment]
@Narkfr est ce que tu pourrais donner des exemples des problèmes et montrer comment un composant <IFrame /> les résoudrait ?

**Comment by ptbrowne** [comment]
Est ce que https://github.com/cozy/cozy-ui/issues/235 conviendrait à tes besoins @Narkfr ?

**Comment by Narkfr** [comment]
@ptbrowne parfait ! Je pense que l'issue n'a plus vraiment de sens, je n'avais pas une bonne vision des intents et de leur fonctionnement à ce moment, on peut la fermer
