### ISSUE TITLE
2 small bugs on the storybook

### ISSUE THREAD

**Issue by nono** [cozy/cozy-ui#210]
- [ ] the paperplane icon is not shown
- [x] the grey and white spinners are blue

**Comment by enguerran** [comment]
We don't use storybook, but [styleguidist](https://github.com/styleguidist/react-styleguidist). Comment stay relevant.

**Comment by nono** [comment]
It's called the storybook in the README: https://github.com/cozy/cozy-ui#react-components

**Comment by ptbrowne** [comment]
Spinner problems are duplicate of https://github.com/cozy/cozy-ui/issues/197

**Comment by ptbrowne** [comment]
Thanks @nono for the report. Both bugs are fixed
