### ISSUE TITLE
IconButton component should be 48px by default

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#2107]
Actuellement le composant IconButton est en 40px et devrait être en 48px.

- [x] ajouter la size 48px à IconButton => https://github.com/cozy/cozy-ui/pull/2125
- [ ] setter la size 48px par défaut sur IconButton => https://github.com/cozy/cozy-ui/pull/2136
- [x] ajouter un codemods permettant de gérer le BC du set de la size 48px par défaut => https://github.com/cozy/cozy-libs/pull/1562

---

Composants impactés : 

Utilisation : https://github.com/search?q=org%3Acozy+react%2FIconButton&type=code

**CCO2**

- SelectDate : 
![image](https://user-images.githubusercontent.com/67680939/164675398-88de73c7-66ed-4987-aab4-78c4d4f6f392.png)
- header des dialogs
![image](https://user-images.githubusercontent.com/67680939/164675592-7a26d8fa-b0f9-4465-aa1c-af13d8cceea2.png)
![image](https://user-images.githubusercontent.com/67680939/164675733-20227eae-3834-477a-b41b-724a085bd654.png)

**Comment by JF-Cozy** [comment]
@joel-costa il est potentiellement question d'avoir des tailles différentes pour ce IconButton, peux-tu regarder ça stp ?

**Comment by joel-costa** [comment]
- Oui pour ajouter des cas de size dans le composant
- Te donner lesquelles maintenant => Pas le temps, mets juste ce dont tu as besoin pour l'instant
- 40px par défaut pour éviter les BC => Ca me ferait vraiment chier parce que si on utilise déjà du 40px à des endroits, c'est parce qu'on n'a pas géré correctement le composant tout de suite en le mettant en 48px. Et quand on sera emmené à importer de nouveaux composant de MUI qui utilisent l'icon button, on devra corriger la taille de l'icon button à chaque fois

**Comment by JF-Cozy** [comment]
On va donc garder les `small` et `medium` déjà présent, et laisser `medium` par défaut. On va rajouter `large` pour le 48px, et plus tard on le passera par défaut en ajoutant un codemods (qui rajoutera un `size="medium"` si la prop était manquante, et supprimera la prop si on avait déjà un `size="large"`) pour gérer le BC.
