### ISSUE TITLE
Modals in mobile mode

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#215]
Par défaut les boutons sur la modale en mode mobile ne sont pas optimaux : 

![image](https://user-images.githubusercontent.com/465582/33118747-09e1c966-cf6d-11e7-9d0d-bf151c60513a.png)

Je propose de les rendre comme ça  : 

![image](https://user-images.githubusercontent.com/465582/33118723-f771c6d2-cf6c-11e7-974a-c5d5c4502344.png)

Des remarques ? @Claiw @GoOz ?

**Comment by GoOz** [comment]
Seems legit. J'attends l'avis de @Claiw mais ça me parait une bonne solution.

**Comment by ptbrowne** [comment]
Fixed in https://github.com/cozy/cozy-ui/pull/221
