### ISSUE TITLE
<Dialog /> component seems to have a padding issue in some cases

### ISSUE THREAD

**Issue by acezard** [cozy/cozy-ui#2165]
Cf this 
![image](https://user-images.githubusercontent.com/12577784/173223474-b7d14b9e-a3a5-4b50-b417-4ca8ac6b2f68.png)
The .dialogTitleWithBack has a 12 16 16 48 padding, instead of (probably) a 16 everywhere. I didn't find a way to change this from outside cozy-ui, as I can't input className or ID to the component, and useCozyDialog didn't help me neither.
My modal is `fullScreen `and has `onClose`

Cf this comment in cozy-home that solves temporarily the issue:
```
    /*
    * @HACK
    * The <Dialog /> `cozy-ui` component used by Harvest has a flaw in its design
    * In small screens, it will display (probably by error) the modal title in a padding 12/16/16/48 setting
    * This is highly undesired and unfortunately we can't add class or any styling props to this part of <Dialog />
    * At the time of this commit, the simplest way to handle the issue is to override `.dialogTitleWithBack` class
    * This way we can apply our desired design in a limited scope: only Home, only Mobile
    */
    .dialogTitleWithBack
        padding spacing_values.xl spacing_values.m spacing_values.m !important // @stylint ignore

```

**Comment by JF-Cozy** [comment]
Dialog à proprement (import from cozy-ui/transpiled/react/Dialog) parlé n'est pas censé être utilisée, il faut préférer les CozyDialogs (import from cozy-ui/transpiled/react/CozyDialogs). Dans ton cas, je pense que le plus approprié serait même une IllutrationDialog.

Par ailleurs il est maintenant possible de passer des props à dialogTitle via `componentsProps={{ dialogTitle: { className: "" } }}` cf https://github.com/cozy/cozy-ui/pull/2283 ce qui devrait résoudre le souci.
