### ISSUE TITLE
Put a Spinner in a Button

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#234]
Hi,

I would like to put a Spinner in a Button.
My first guess was to add it directly as `children`:

```jsx
<Button onClick={onClick}>
  <div>Load More {isLoading && <Spinner color="white" />}</div>
</Button>
```

But the `children` props is defined as a `string`. Should it be changed? Or should I changed my way of working?

cf. https://github.com/cozy/cozy-ui/blob/master/react/Button/index.jsx#L18

**Comment by ptbrowne** [comment]
It should be changed to `PropTypes.node`

**Comment by GoOz** [comment]
A spinner instead of the text or next to the text? `aria="busy"` doesn't fit your needs?

**Comment by enguerran** [comment]
Les deux, mon capitaine : 

![](https://i.imgur.com/QFtScWz.png)

or

![](https://i.imgur.com/kDCEIdy.png)

I didn't see anything about `aria="busy"` in https://cozy.github.io/cozy-ui/react/#button
Do you confirm that adding this will render a spinner?

**Comment by GoOz** [comment]
@enguerran It will add a spinner next to the text yes.

**Comment by GoOz** [comment]
CF https://github.com/cozy/cozy-ui/blob/master/stylus/components/button.styl#L45-L50

**Comment by enguerran** [comment]
We should add the example (a spinner in a button with and without the text) in styleguidist.
This done, we will be able to fix a margin problem I faced in my application:

![](https://i.imgur.com/e95Me04.png)

**Comment by ptbrowne** [comment]
![image](https://user-images.githubusercontent.com/465582/33711496-835a4614-db44-11e7-8bde-d54674744095.png)

I edited the code in the styleguide to test and it's working 👍 , I did not know that, adding this to the styleguide seems good.

>  This done, we will be able to fix a margin problem I faced in my application:

It seems a bit weird to me for UX to have the text of the button disappear when you click on it :/

**Comment by GoOz** [comment]
@ptbrowne I tend to agree, although I'm not personally shocked by this (maybe cause I've seen this elsewhere and kinda used to) I think that It may confuse some non-power users. But maybe I'm wrong.
I'm curious to know what @Claiw thinks.

**Comment by ptbrowne** [comment]
> We should add the example (a spinner in a button with and without the text) in styleguidist.

Do you have time to do the PR ?

**Comment by enguerran** [comment]
I'll do it

**Comment by Claiw** [comment]
@GoOz @enguerran @ptbrowne 
hello, j arrive apres un peu apres la bataille ; pour le coup en tout cas en termes de design existant on est plutot sur le screenshot qu a montré Patrick
<img width="563" alt="screen shot 2017-12-07 at 18 01 50" src="https://user-images.githubusercontent.com/31621610/33727584-c19c655e-db78-11e7-9a9a-52db4a64474e.png">
Et pour repondre la question de GoOz, dans la mesure du possible je trouve que c'est mieux de conserver le label du bouton quand il y a un chargement :)

**Comment by enguerran** [comment]
@Claiw J'ai fait une PR pour reprendre les différentes possibilités https://github.com/cozy/cozy-ui/pull/241, j'ai mis des captures d'écran pour que tu te rendes compte.
@GoOz @CPatchane @ptbrowne je vous laisse voir si vous voulez merger tout ça et fermer l'issue.

**Comment by Claiw** [comment]
ça me semble cool 👍

**Comment by CPatchane** [comment]
Bien joué @enguerran 👍 , pour infos on utilise pas mal `aria-busy` de notre côté pour tout ce qui est spinner dans les boutons, c'est plus simple à gérer que des classes.

**Comment by ptbrowne** [comment]
Closed in https://github.com/cozy/cozy-ui/pull/241
