### ISSUE TITLE
SquareAppIcon : glitch with spinner

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#2434]
Le spinner qui tourne lorsqu'un connecteur tourne, continue de tourner derrière l'icone lorsque le connecteur est fini. C'est caché donc logiquement pas génant (à part les perfs?), mais ça dépasse de 1px sur les bords, donc sur fond blanc et au hover on voit des petits artefacts liés à la rotation

**Comment by acezard** [comment]
@JF-Cozy proposition de fix en PR en faisant disparaitre le spinner lorsqu'il n'est plus nécessaire https://github.com/cozy/cozy-ui/pull/2436
