### ISSUE TITLE
ModalCross can take a class as props to override default style

### ISSUE THREAD

**Issue by Narkfr** [cozy/cozy-ui#248]
ModalTitle, ModalContent, ModalSection can take a `classname` props to override default style, but not the ModalCross.

It can be usefull to have this pros in the ModalCross too.to avoid this kind of trick to adjust styles of this cross.

```css
    [class*="coz-btn-modal-close"]
        top: 4px
        right: 4px
```

**Comment by ptbrowne** [comment]
Closed by #249
