### ISSUE TITLE
doc for Alerter + easier usage

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#263]
There is no doc for the Alerter component in styleguidist.

**Comment by enguerran** [comment]
We must see with @goldoraf if we rewrite the `cozy-ui/react/Alerter` with `cozy-drive/photos/Alerter`. I think the later has a better API.

**Comment by ptbrowne** [comment]
Yes, it seems you have a bit of debt there :/

```
 drive master  rg 'Alerter' | grep import | sort
src/drive/components/Layout.jsx:import Alerter from 'photos/components/Alerter'
src/drive/components/Layout.jsx:import { Alerter as OldAlerter } from 'cozy-ui/react/Alerter'
src/drive/components/PublicLayout.jsx:import { Alerter } from 'cozy-ui/react/Alerter'
src/drive/ducks/files/Toolbar.jsx:import { alertShow } from 'cozy-ui/react/Alerter'
src/drive/reducers/index.js:import alerterReducer from 'cozy-ui/react/Alerter'
src/photos/components/Layout.jsx:import Alerter from './Alerter'
src/photos/containers/AddToAlbumModal.jsx:import Alerter from '../components/Alerter'
src/photos/containers/AlbumPhotos.jsx:import Alerter from '../components/Alerter'
src/photos/containers/SelectionBarWithActions.jsx:import Alerter from '../components/Alerter'
src/photos/ducks/albums/components/AlbumToolbar.jsx:import Alerter from '../../../components/Alerter'
src/photos/ducks/albums/components/PhotosPicker.jsx:import Alerter from '../../../components/Alerter'
src/photos/ducks/upload/index.js:import Alerter from '../../components/Alerter'
src/photos/reducers/index.js:import alerterReducer from 'cozy-ui/react/Alerter'
src/sharing/components/ShareByEmail.jsx:import Alerter from 'photos/components/Alerter'
```

We have to implement some Alerts in our sprint so I guess it will be a good time for us to take the Alerter from Photos and put it in cozy-ui. It's true that the API from photos/Alerter is nicer.

To me the old `Alerter` should not be used as it needs the user to install a custom state slice in his redux reducer. I guess this is why you refactored it in Photos.

What do you think if I import photos' Alerter in cozy-ui as Flasher and then deprecate Alerter ? I guess the action creators from cozy-ui/Alerter could even call `Flasher.{success,info,error}` for a smoother transition path.

**Comment by goldoraf** [comment]
@ptbrowne yeah, I prefer `cozy-drive/photos/Alerter`'s API too. :+1: for your proposition

**Comment by enguerran** [comment]
@ptbrowne once cozy-ui is ready with the new alerter, could you ping me to update our code in cozy-drive?

**Comment by GoOz** [comment]
So basically it's more a planned refactoring than an update of the documentation?

**Comment by enguerran** [comment]
not a refactoring, a rewriting.
and with the rewriting will come the documentation.

**Comment by GoOz** [comment]
Rewriting, true.

**Comment by ptbrowne** [comment]
> @ptbrowne once cozy-ui is ready with the new alerter, could you ping me to update our code in cozy-drive?

OK @enguerran, I will ping you. I will try to not break your existing code though and display deprecation warnings if it is not too much work.

**Comment by enguerran** [comment]
You can remove completly the old Alerter without any warning but a major version increment. As this when we will be warn to update cozy-ui version used by our app, we will read the breaking changes and adapt the code.

**Comment by ptbrowne** [comment]
I found that breaking compatibility was a reason for us at Gangsters to stop contributing to cozy-ui since we were not at the latest version because of breaking changes and thus we could not benefit from our contributions right away. This is why I prefer to have a transition period.

**Comment by enguerran** [comment]
That is the daily lot of using external libs. And like the `état d'urgence` in France, transition period may stay for ever! ;-)

**Comment by ptbrowne** [comment]
> transition period may stay for ever!

I plan to remove the deprecation warning in the next major version. I really like how the React project is handling this. They clearly state their goals and the migrations paths. https://reactjs.org/docs/design-principles.html#stability

**Comment by GoOz** [comment]
So basically, the Alerter shouldn't need redux store.
A merge of [Photos' Alerter component](https://github.com/cozy/cozy-drive/blob/master/src/photos/components/Alerter.jsx) and UI's seems like a good plan.

**Comment by y-lohse** [comment]
Whlle we're there, it would be good to use portals for `Alerts` as well.

**Comment by enguerran** [comment]
Are `<Portals />` supported by `preact` and `preact-compat`?

**Comment by y-lohse** [comment]
There's a `preact-portal` module that we already use for Modals !

**Comment by ptbrowne** [comment]
A doc is now available here : https://cozy.github.io/cozy-ui/react/#!/Alerter
