### ISSUE TITLE
Add a styleguist link for components

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#282]
Add a direct link to the component styleguidist page in the component readme.

**Comment by ptbrowne** [comment]
![image](https://user-images.githubusercontent.com/465582/37104659-9023183c-222d-11e8-8d59-8cd01fe54e4f.png)

**Comment by CPatchane** [comment]
I was talking about adding a link directly in the component readme like [here](https://github.com/cozy/cozy-ui/tree/master/react/Button) for the Button component, I used to go directly to the component folder to check the files so it could useful. But I guess that will duplicated informations since these readme files are used to build the styleguidist.
