### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-ui#3]
I started to read about managing CSS properly, but I haven't pushed it yet. I heard of "BEM" methodology, and siblings. Do you have any opinion on that kind of methodology? Do you think it would be worth it to learn and use one?

**Comment by m4dz** [comment]
BEM can be a good starting point, but I'm not especially fan of long and over-verbose class names like:
```html
<div class="toolbar toolbar--active">
    <a class="toolbar__search--button">search</a>
</div>
```
I prefer to use ARIA to describe properly roles and states:
```html
<div class="toolbar" aria-disabled="false">
    <a class="search" role="button">search</a>
</div>
```
and which can be targeted in Stylus via:
```stylus
[role=button]
    // buttons display style rules

.search[role=button]
    // search button specific rules

.toolbar
    // toolbar specific rules
    [aria-disabled=true]
        // inactive state style rules
    [aria-disabled=false]
        // active state style rules

    .search[role=button] &
        // search button in toolbar specific rules
```

Simpler to maintain, IMHO :smile:.

**Comment by jsilvestre** [comment]
Ok, I follow your lead!
