### ISSUE TITLE
Mount Modal in a portal

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#301]
Currently, Modal is mounted in the DOM tree just where we declare it. But it can lead to positionning problems. It would be great to mount it in a portal at the root of the `body`, so it is completly isolated from the rest.

The thing is that even if you use preact-compat, it doesn't add `ReactDOM.createPortal` API. But there is [preact-portal](https://github.com/developit/preact-portal) to use portals in preact.

**Comment by ptbrowne** [comment]
"Your wish is my command" : https://github.com/cozy/cozy-ui/pull/303
