### ISSUE TITLE
Remove cozy-client-js

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#308]
For now, in IntentOpener we use cozy.client that is provided or by the stack or via webpack. Since cozy-client-js will no longer be used, we should use cozy-intents when it is ready.

**Comment by GoOz** [comment]
@ptbrowne I didn't follow this, where are we on this point? Are we still using cozy-client-js in Cozy-UI for intents.

**Comment by gregorylegarec** [comment]
Actually, we are very likely to provide a `cozy-interapp` library which will provide intents logic AND dedicated react components, like IntentOpener for example.

**Comment by y-lohse** [comment]
The dependency is no mo'.
