### ISSUE TITLE
Fixed header/footer for IntentModal

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#309]
For [cozy/cozy-contacts](https://github.com/cozy/cozy-contacts) I needed to create an intent modal with:
- fixed header
- fixed footer
- scrollable main content

The actual code is referenced in the commits from this PR: https://github.com/cozy/cozy-contacts/pull/26

I think it could be very useful to add those CSS rules and create adequat preact components in cozy-ui as every apps could use them.

![screenshot-2018-1-30 cozy-contacts](https://user-images.githubusercontent.com/701648/35555869-db850366-05a0-11e8-911b-897ec2e29890.png)

**Comment by GoOz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mini-layout fixed & scroll](https://trello.com/c/WOkefKL3/90-mini-layout-fixed-scroll)

**Comment by GoOz** [comment]
Fixed #364
