### ISSUE TITLE
Buttons, flexbox and safari 10

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#310]
[Our buttons use `display inline-flex`](https://github.com/cozy/cozy-ui/blob/master/stylus/components/button.styl#L11) to center their content.

Unfortunately, using `flexbox` on certain elements like `button` is not very well supported in older browser, most notably safari 10, which is still used in the wild. In those cases, the content of the button is aligned to the left.

i've created a [pen](https://codepen.io/anon/pen/oENePQ) with the minimal issue reproduced.

Possible fixes i've found:

- don't use flexbox at all on buttons
- use `display -webkit-inline-box` instead of `display inline-flex` — actually `-webkit-inline-box` is inserted in our code, but safari supports `inline-flex` too so that rule takes precedence
- [using pseudo-elements](https://stackoverflow.com/a/40483475) — seems to work well, but of course if the button `actually` uses pseudo-elements things might very well break

I really have no idea what the consequences of any of these fixes would be, but I'm afraid none of them is backwards compatible.

**Comment by GoOz** [comment]
> use display -webkit-inline-box instead of display inline-flex — actually -webkit-inline-box is inserted in our code, but safari supports inline-flex too so that rule takes precedence

Safari… t(°^°t)

We don't use `::before` or `::after` pseudo-elements in our buttons (so far) so I guess this would do the trick. Thank you for your thorough investigation. 🙏

I'll implement this solution asap.

**Comment by y-lohse** [comment]
Great, thanks!

**Comment by y-lohse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) 🐛📱 Libellé des boutons alignés à gauche dans l'app iOS](https://trello.com/c/EhgqPVkX/769-1-%F0%9F%90%9B%F0%9F%93%B1-libell%C3%A9-des-boutons-align%C3%A9s-%C3%A0-gauche-dans-lapp-ios)

**Comment by GoOz** [comment]
Fixed by #311

**Comment by y-lohse** [comment]
@GoOz Welp, it *did* break something. When a button has the `busy` prop, we insert the spinner with an `after`, and it really doesn't like the flex display.
<img width="329" alt="capture d ecran 2018-02-01 09 06 39" src="https://user-images.githubusercontent.com/2261445/35667936-bcfc3a1e-072f-11e8-8463-cbc76c88cc5a.png">

**Comment by GoOz** [comment]
damn I forgot this…

**Comment by y-lohse** [comment]
Fixed in #315, probably. i'll reopen if the problem is still there but should be good now, thanks!

**Comment by GoOz** [comment]
Well, It's fixed on Styleguidist, so I'm pretty confident but yeah let me know if you encounter any other issue on this.
