### ISSUE TITLE
Modal scrolling

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#320]
Since a few versions, modal are now using a scroll bar when the modal content is taller than the viewport, and it feels a little bit weird.

![capture d ecran 2018-02-06 a 09 37 34](https://user-images.githubusercontent.com/776764/35854986-302d6200-0b32-11e8-8fdb-8dc674a7dfa7.png)

I think we should match the classic modal behavior, i.e. the modal is sliding in the viewport and does not provides scrollbar unless the developer enable it.

The goal of this issue is to decide what is the default behavior of our modal, and how we enable/disable scrollbars. My guess is that it should be an optional property, but it could also be customized with CSS every time it's needed (I personnaly don't like this solution).

**Comment by ptbrowne** [comment]
For information : on material-ui.com, they have an attribute to make the body of a modal be scrollable automatically: http://www.material-ui.com/#/components/dialog. To me it would be weird to have a modal be taller than the viewport, do you have any example of modals that behave like that @gregorylegarec  ?

**Comment by GoOz** [comment]
> I personnaly don't like this solution for modal where the user needs to take an action. It means that the user does not the possible actions right away.

I may not understand well what you meant but, either way, whether it's the actual modal layout or the one @gregorylegarec suggets, the user needs to take an action and scroll down to see the actions available (if any). 
Unless we do, as I thought at first, a new kind of layout inside the modal, with a fixed header (as @Claiw wanted), a scrollable content and a fixed footer with action (if any). This kind of layout would take as max-height the viewport's height an make the content scrollable if needed. 
That's more the way I thought it and like it. 
But maybe it's just what you meant and we're juste on the same page 😄

**Comment by GoOz** [comment]
OK sorry I forgot to open the material UI page, this is what you meant. So yeah I'm up for this.

**Comment by GoOz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mini-layout fixed & scroll](https://trello.com/c/WOkefKL3/90-mini-layout-fixed-scroll)

**Comment by Claiw** [comment]
Hi all, 

I think it's better to have a dialog modal similar to the Material-UI's one. 
It's really more easier to navigate, there are less frictions when you read/consult the modal, and it fits better to the way we build modal for cozy platform.
Boostrap modal is more indicated when you have actions on a sidebar in the modal like in Trello, which is not our case :)

**Comment by ptbrowne** [comment]
@Claiw In this case what does collect needs to do ? It seems that it cannot have the trainline logo in the modal header as it is too tall. No header but a footer with the actions ? No header and no footer ?

@gregorylegarec I think you should put at least a ` overflowHidden={true}` for the scrollbar to have the border-radius.

**Comment by Claiw** [comment]
sorry, i'll continue in french to explain faster the behaviour, if you want i'll translate later

je ne vois pas en quoi la taille du logo devrait l'empecher d 'etre ds le header. 
S'il est trop gros, peut etre faut-il en reduire la hauteur ( sur zeplin, on est plus sur une hauteur de 32px que sur une hauteur de 48 px comme sur la capture suivante )

pour la modale de configuration ( qd on veut connecter un compte ), j aurais vu qqe chose de ce style: 
![configuration_modal](https://user-images.githubusercontent.com/31621610/36028446-454c22ec-0d9f-11e8-933e-9e563fe43778.png)

pour la modale de gestion de compte (ou adminstration modal en EN ), le comportement le plus naturel serait que tu puisses scroller en dessous des onglets (donc header + onglets fixes) : 
![administration_modal](https://user-images.githubusercontent.com/31621610/36028541-afc9faae-0d9f-11e8-9dbc-b0db7c05f434.png)

Cependant si ds un 1er temps on a le meme comportement que pour la modale de configuration, pourquoi pas, mais je pense qu'il faudra ameliorer ce comportement là par la suite

**Comment by ptbrowne** [comment]
Ah oui parfait, j'avais pas pensé au fait que la scrollbar pouvait commencer après les tabs. Ca me semble nickel !

**Comment by ptbrowne** [comment]
Personnellement je trouve la mention : 

![image](https://user-images.githubusercontent.com/465582/36028978-817c8eb2-0da1-11e8-835c-073bd74a8f9c.png)

un peu bizarre. Je lis ça, j'ai envie de dire "et alors, qu'est ce que je dois faire ?".

J'aurais plus vu un message un avertissement lorsqu'on re-ouvre une modale de configuration "Vous avez déjà ce compte connecté, voulez vous continuer à en ajouter un autre". En mode wizard.

**Comment by y-lohse** [comment]
Juste un petit état des lieux sur ce qui se fait ailleurs:

#### Modales qui grandissent a l'infini, et on scroll la page:

- Trello : voir une carte
- Twitter : afficher un thread

#### Modales à taille fixe le contenu scroll

- Gmail : rédiger un message
- Brackets : installer une extension
- Dropbox Paper : consulter l'historique d'un document

A noter que je trouve quand meme peu d'exemples, dans un sens ou dans l'autre. J'ai l'impression que le plus souvent, c'est une page dédiée qui est utilisée.

**Comment by GoOz** [comment]
> J'ai l'impression que le plus souvent, c'est une page dédiée qui est utilisée.

À juste titre d'ailleurs 😄

**Comment by ptbrowne** [comment]
Voyant qu'il y a plusieurs options, je n'aurais personnellement pas d'objection à laisser le choix d'une scrollbar au développeur de l'application.

**Comment by Claiw** [comment]
Effectivement, quand tu commences à avoir beaucoup de contenu dans une modale, c'est souvent le moment pour se poser la question de si on consacre une page.
Pour revenir au scroll de contenu dans la modale, et pour ajouter ma pierre aux exemples proposés par yannick, voici quelques exemples qui me viennent en tête immédiatement : 
dropbox : 
<img width="1038" alt="screen shot 2018-02-28 at 06 40 35" src="https://user-images.githubusercontent.com/31621610/36771959-9654cdd4-1c53-11e8-88a4-461573a74979.png">
google contacts : 
<img width="1105" alt="screen shot 2018-02-28 at 06 35 11" src="https://user-images.githubusercontent.com/31621610/36771971-9ff04ae4-1c53-11e8-8c0c-1f2a78830915.png">
google drive : 
<img width="1064" alt="screen shot 2018-02-28 at 06 48 39" src="https://user-images.githubusercontent.com/31621610/36772005-bcc997a6-1c53-11e8-8490-4d91886f2b8b.png">

Considérant qu'on va s'adresser à des utilisateurs qui ont besoin de repères de navigation pour se répérer, les modales où tu scrolles le contenu après avoir atteint la taille maximale disponible dans la page sont à mon sens plus indiquées : tu perturbes moins la lecture parce que le haut de la modale reste fixe, d'autant plus si tu as un système d'onglets à l'intérieur ce qui est le cas ds les modales Cozy Collect.

**Comment by gregorylegarec** [comment]
Approved today: a modal without header nor footer must fit vertically into the viewport. Its content is scrollable if it's taller than the modal.
