### ISSUE TITLE
Modal is inserted in the DOM twice

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#334]
I found a super weird bug in Cozy Drive, that I worked around [here](https://github.com/cozy/cozy-drive/pull/766).

Under certain conditions, it can happen that the `Modal` is duplicated in the DOM. I haven't found the exact cause and I don't have a minimal repro, but here's what I found out:

- it happens when using Portals, otherwise not
- The `Modal`'s `render` function is called more than 2 times, but there are only 2 modals in the DOM
- It's related to using `cozy-connect` — if the component isn't connected, it works fine

it would be easy to point to either portals or cozy-connect as the source, but both individually work well. Just not together.
I *suspect* that the problem has something to do with the re-rendering when the props change, but not sure.

Here's a simplified version of the buggy code:

```jsx
const MyModal = ({ title }) => (
  <Modal into="body">
    <h3>{title}</h3>
  </Modal>
)

export default cozyConnect({ title: someSelector() })(MyModal)
```

And the one without the problem:

```jsx
const Title = ({title}) => <h3>{title}</h3>
const ConnectedTitle = cozyConnect({ title: someSelector() })(Title)

const MyModal = () => (
  <Modal into="body">
    <ConnectedTitle />
  </Modal>
)

export default MyModal
```

**Comment by GoOz** [comment]
ping @ptbrowne

**Comment by ptbrowne** [comment]
Thanks for the explanation @y-lohse , I'll try to reproduce.

**Comment by ptbrowne** [comment]
Do you have a case to reproduce ?

**Comment by GoOz** [comment]
For the alerts: https://gooz.github.io/cozy-ui/react/#alerter

**Comment by ptbrowne** [comment]
Should be solved by https://github.com/developit/preact-portal/pull/8

**Comment by ptbrowne** [comment]
Fix has been released, unfortunately I've updated but can still the two DOM nodes being added in the styleguide :/ 

Updated branch : cozy/cozy-ui#update-preact

**Comment by y-lohse** [comment]
I'll go ahead and close this issue. I don't think we've had the problem since over a year, and we've mostly moved away from preact now.
