### ISSUE TITLE
Organisation des demandes et développements

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#336]
On a pris un peu de temps avec @enguerran  et @GoOz  pour discuter un peu plus en meta du problème de l'implémentation de l'Avatar. Les conclusions :

* passer par les issues  pour faire des demandes à cozy-ui permet de communiquer de manière impersonnelle ses besoins et d'avoir une discussion sur l'API
* si besoin urgent, le composant peut être fait dans l'application avec possiblement l'aide de gooz concernant le css. -> tout de suite faire une issue sur cozy-ui si le composant a l'air d'être possiblement transposable sur ui.
* on affinera avec gooz le backlog d'issue de manière hebdomadaire pour prioriser les demandes. @CPatchane on aura sûrement besoin de ton aide aussi :)

Est ce que ca vous va ?

**Comment by GoOz** [comment]
J'ajoute qu'un atelier est dans la liste de la journée d'équipe, histoire d'avoir le point de vue et les idées d'autres comme des PO ou Eric. 
Mais que cela n'empêche pas de commencer comme ça en attendant, on fera évoluer si de bonnes idées en ressortent.
Bref, j'aime l'idée d'organiser un peu de process dans cette histoire. 😄

**Comment by drazik** [comment]
Bonne organisation je pense.

**Comment by CPatchane** [comment]
Je pense aussi que c'est une bonne organisation pour les demandes liés à cozy-ui, complètement chaud pour avancer dans ce sens.
On pourrait aussi discuter des critères qui fait qu'un composant devrait être transposé ou pas. Il faut quand même garder à l'esprit que pas tous les composants d'une app a forcément sa place dans cozy-ui (je ne remets pas en cause l'Avatar ici hein). Rien que ce matin j'ai vu un tweet dans ce sens ["You haven't mastered a tool until you understand when it should not be used."](https://twitter.com/kelseyhightower/status/963428093292457984)
