### ISSUE TITLE
Modal: layout when not using ModalTitle

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#337]
In the https://github.com/cozy/cozy-contacts app, we use a modal without modaltitle and the closing cross is covered by our menu button:

![screenshot-2018-2-14 cozy-contacts](https://user-images.githubusercontent.com/701648/36200427-e36e50a4-117c-11e8-9ebe-4c9244a1cd89.png)

Here is the code: https://github.com/cozy/cozy-contacts/blob/ec741a5a7550190d748e0c50ea6ffd1db3460511/src/components/ContactsApp.jsx#L69-L87

_note: those are not real user data, just fake data._

**Comment by enguerran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) ETU je peux supprimer un contact depuis sa fiche](https://trello.com/c/eD8KjGbM/724-2-etu-je-peux-supprimer-un-contact-depuis-sa-fiche)

**Comment by GoOz** [comment]
So Modals should have a ModalHeader which is exactly the same as ModalTitle but renamed.
In your case, the avatar, name and more menu should be in a header.
You still have the possibility to not use ModalHeader but this won't behave the same. A modal without header have a top padding to secure the close button position.
