### ISSUE TITLE
Menu: customize menu items 

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#339]
In order to implement a delete action in a Menu, I need to colorize the menu item in red like in https://github.com/cozy/cozy-drive:

![](https://i.imgur.com/VVqeHCP.png)

I don't see anything about it in `cozy/cozy-ui` react documentation, how to do it?

My actual code is
```jsx
  <Menu
    position="right"
    component={
      <Button theme="secondary" extension="narrow" class="fix-c-btn">
        <Icon icon="dots" />
      </Button>
    }
  >
    <MenuItem icon={<Icon icon="delete" />} onSelect={deleteAction.action}>
      {deleteAction.label}
    </MenuItem>
  </Menu>
```

What I want to be red is 
```jsx
    <MenuItem icon={<Icon icon="delete" />} onSelect={deleteAction.action}>
      {deleteAction.label}
    </MenuItem>
```

**Comment by enguerran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) ETU je peux supprimer un contact depuis sa fiche](https://trello.com/c/eD8KjGbM/724-2-etu-je-peux-supprimer-un-contact-depuis-sa-fiche)

**Comment by ptbrowne** [comment]
Yes the class is the way to go here. I think a way to do that in UI would be to give `u-color-` to apply to have the color. Would it satisfy your need @enguerran ?

`MenuItem` could have its section in the styleguide so that its props (`className` here) are visible. I guess, it should be written somewhere than every component in cozy-ui can take className and style.

**Comment by GoOz** [comment]
I forgot but there's already a utility class that changes the text color to red (pomegranate), it's `u-error`. Didn't connect the dots :/

**Comment by ptbrowne** [comment]
Semantically here it would be a bit weird to add `u-error` when here it should be something akin to `u-important`. Since colors can have different significations depending on the context of the app, I suggest to duplicate `u-error` in `u-red`, and more generally to have utility classes for colors.

**Comment by GoOz** [comment]
I agree, that would be weird. I'll figure something out.

**Comment by ptbrowne** [comment]
I think we can close, maybe this can be done under an issue "Add text classes to Cozy-ui" ?
