### ISSUE TITLE
Use palette.styl

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#342]
How can I use variable set in `palette.styl`?

See the screenshot, I `require` the file and the property value is undefined:
![](https://i.imgur.com/bKzprqL.png)

**Comment by y-lohse** [comment]
It's `pomegranate`, not `pomagranate`.

**Comment by enguerran** [comment]
😕 well done! But I think I copied/pasted the value from somewhere (I can't remember from where). Sorry and close it!
