### ISSUE TITLE
import components within ESModules in ES2018

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#344]
I don't know how to import components.

I use
```jsx
import Icon from "cozy-ui/react";

const MyIcon = () => <Icon icon="dots" />
```

but I get
```html
<undefined icon="dots"></undefined>
```
with no error neither in the console nor in the webpack build.

But if I use

```jsx
import { Icon } from "cozy-ui/react";

const MyIcon = () => <Icon icon="dots" />
```

I get
```html
<svg class="icon--2kaoz" width="16" height="16"><use xlink:href="#cozyuicon-dots"></use></svg>
```

I think there is some misusage in https://github.com/cozy/cozy-ui/blob/master/react/index.js
https://github.com/cozy/cozy-ui/blob/1f2c5edee507539e608a263ad17ac0b3416437da/react/index.js#L4

**Comment by y-lohse** [comment]
Unless I misunderstood something, this is the intended behavior. `cozy-ui/react` doesn't export a `default` module, so you must specify what you want to import from it, by using `import { WhatIWant } from 'cozy-ui/react'`.

` export {default as Icon} from './Icon' ` means "Export the default module of `./Icon` under the name `Icon`".

**Comment by GoOz** [comment]
That's how I understood it too but I'm no expert in this field.

**Comment by enguerran** [comment]
What is the default module exported from `"cozy-ui/react"`, then? And Why is there a default module exported? (_note: the `import` statement was auto-added by one of my editor plugin called https://marketplace.visualstudio.com/items?itemName=capaj.vscode-exports-autocomplete)

**Comment by ptbrowne** [comment]
> What is the default module exported from "cozy-ui/react", then?

Nothing. What would it be ?

> Why is there a default module exported?

What do you mean ? There is no default module exported from ui/react/index.js.

`export { default as Toto } from './Toto'` !== `export default`

**Comment by enguerran** [comment]
Ok, it appears that there is always a `export default` even if not declared, then its value is `undefined`.

So in `cozy-ui/react/index.js`, as there is no `export default`, I imported `undefined` and there was no error anywhere:

https://github.com/cozy/cozy-ui/blob/1f2c5edee507539e608a263ad17ac0b3416437da/react/index.js#L1-L23

I close this as there is nothing more to do, except remove `cozy-ui/react/index.js` and accept all imports are made like this `import Icon from "cozy-ui/react/Icon"` (in any case, it's hard to maintain a binding file without forgetting anything)

**Comment by ptbrowne** [comment]
Yes it is very annoying that preact does not tell you that it is rendering an undefined component :/
