### ISSUE TITLE
Modal: create a ModalFooter to handle the modal footer layout

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#350]
In the case I want to display a form in a modal, I want a submission button, I can't just use the `primaryAction` attribute.

So it could be good to have something to handle the footer layout inside which I could put my submission and cancelation buttons.

---

In case someone would like to contribute, here are some of the work that has already been done:

We already have something similar in the intent modal that let user pick a contact in https://github.com/cozy/cozy-contacts:

the css
https://github.com/cozy/cozy-contacts/blob/c6ad35f6fa2439340bdd4cb14533dac3013fe06d/src/styles/intent.styl#L7-L28
```stylus
.intent-layout
    height 100%
    display flex
    align-items stretch
    flex-direction column


.intent-footer
    height 4.5rem
    background-color paleGrey
    box-shadow inset 0 -1px 0 0 silver
    display flex
    align-items center
    padding .5rem 1rem

    .intent-footer-label
        flex 1

.intent-main
    flex 1
    overflow-y scroll
width 100%
```

the pseudo-html markup (jsx)
https://github.com/cozy/cozy-contacts/blob/c6ad35f6fa2439340bdd4cb14533dac3013fe06d/src/components/PickContacts.jsx#L11-L19
```jsx
const IntentFooter = ({ label, onSubmit, onCancel, t }) => (
  <div className="intent-footer">
    <div className="intent-footer-label">{label}</div>
    <Button theme="secondary" onClick={onCancel}>
      {t("cancel")}
    </Button>
    <Button onClick={onSubmit}>{t("confirm")}</Button>
  </div>
);
```

**Comment by GoOz** [comment]
Kinda the same concern that #320 for fixed header & footer
Already in the todo-list, just need to figure out the smartest way to do it.

**Comment by ptbrowne** [comment]
@GoOz Is it closable now that we have the new layout for the modal ?

**Comment by GoOz** [comment]
well, not really, if I understood correctly what @enguerran needed, you still can't pass children and build you own footer. But I'm wondering why you wouldn't be able to right now.

**Comment by enguerran** [comment]
I managed my needs in cozy-contacts, and will check later to change the code and use the new modal's layout.
