### ISSUE TITLE
Refactoring of Alerter component

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-ui#352]
The Alerter shouldn't need redux store.
A merge of [Photos' Alerter component](https://github.com/cozy/cozy-drive/blob/master/src/photos/components/Alerter.jsx) and UI's seems like a good plan.

**Comment by ptbrowne** [comment]
There is already https://github.com/cozy/cozy-ui/issues/263, I think it has more context, could you comment there ?

**Comment by GoOz** [comment]
Oh right, forgot about this one :/
