### ISSUE TITLE
Single column layout centering

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#355]
When using [a single column layout](https://github.com/cozy/cozy-ui/blob/88137c23e97065dd5d8988f379636fb870a1cc48/stylus/objects/layouts.styl#L60), the main content is not aligned to the top of the page, for example:

<img width="1280" alt="capture d ecran 2018-02-20 09 53 54" src="https://user-images.githubusercontent.com/2261445/36414917-492eaec4-1624-11e8-8d10-d996b9debe5f.png">

Is this intended? If not I can provide a fix.

**Comment by GoOz** [comment]
It's definitely not intended. PR is welcome if you already have the fix. 😄

**Comment by y-lohse** [comment]
Sorry, I jumped the trigger too quickly — the default behavior is actually to align the content to the top, but we had a `margin auto` on our end that messed it up.

**Comment by GoOz** [comment]
👍
