### ISSUE TITLE
Section margins

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#358]
In banks, I had to override the default margins of a section title (h3) to better separate sections. Is this the right way to do that ? 

https://gitlab.cozycloud.cc/labs/cozy-bank/merge_requests/309

Should cozy-ui have helpers for vertical rhythm, maybe a `<Section />` element ? Is there something I am missing ?

**Comment by GoOz** [comment]
Vertical rythmn is definitely something to discuss with @Claiw first.
Although I agree with you, I suggest you to keep your override style until we came with a plan.
We need clear specifications that may be slightly different with what we have now in all our apps and could "break" every app at once.

**Comment by ptbrowne** [comment]
What is the status of cozy-ui regarding vertical rhythm, is there a spec that we can implement. I regularly have trouble with spacing and margins. For example the default paragraph never seems to work.

**Comment by Claiw** [comment]
Hello, 

We don't have general specs on that for the moment.
However on Cozy Store, we've done some work about it, to have vertical spaces which evolves on desktop and mobile (cf screenshot).
Unfortunately we don't have global vertical rhythm guidelines for the moment but I keep in mind what I've done on Cozy Store for over designs (as Cozy Home for example).
<img width="969" alt="screen shot 2018-10-23 at 11 52 13" src="https://user-images.githubusercontent.com/31621610/47352431-294d6800-d6ba-11e8-9e81-85c8299606bb.png">
<img width="2012" alt="screen shot 2018-10-23 at 11 58 06" src="https://user-images.githubusercontent.com/31621610/47352790-f3f54a00-d6ba-11e8-96ed-02cc4a66cfbd.png">

**Comment by y-lohse** [comment]
I think we have the `Stack` and `Row` components now that should be enough for most use cases? The other part of the problem is #1033 (title margins).

**Comment by ptbrowne** [comment]
OK for closing.
