### ISSUE TITLE
Hidden content on medium screens

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#359]
[On medium screens, cozy-ui switches the cozy-bar to `position fixed`](https://github.com/cozy/cozy-ui/blob/b5f0aa6b72af911d9ed8c0690da60460cf13bfc8/stylus/objects/layouts.styl#L11). Why is that?

It's a problem because suddenly the content of the app is *behind* the cozy-bar, so the first 50 pixels or so are invisible.

<img width="1278" alt="capture d ecran 2018-02-23 11 45 48" src="https://user-images.githubusercontent.com/2261445/36590525-3715ac20-188f-11e8-8ef1-8dfb14742017.png">

**Comment by GoOz** [comment]
Ok found it. It's because I forgot something for the one column layout. It's just missing the ghost element replacing the cozy-bar in the layout.
