### ISSUE TITLE
Multiple problems with the new Button API

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#376]
I tried to transition the Cozy Drive codebase to the new button API, and it did not go well.

In no particular order:

- There's a bug with `ButtonLink` labels [here](https://github.com/cozy/cozy-ui/blob/master/react/Button/index.jsx#L50). It should be `{label}` and not `label`.
- We had a few instances of buttons containing an icon with other props than just the name of the icon. For example `<Icon icon="cross" width="18" color="kaki" />`. This isn't possible in the new API anymore.
- Just to be sure — using `children` is still ok and will stay so, yes? It's not deprecated?
- `label` is supposed to be a [string](https://github.com/cozy/cozy-ui/blob/master/react/Button/index.jsx#L60). Would it be possible (and would it make sense) to pass a JSX object too? Some of our buttons contain a spinner sometimes, so I don't know if it's better to use `label` or `children` for that.

**Comment by edas** [comment]
Manually passing children should be reserved to when you don't have other solutions. If something is provided for you: use it.

**Comment by y-lohse** [comment]
Alright, seems good to me 👍 thanks for the fixes.
