### ISSUE TITLE
ModalHeader font size

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#387]
Since `ModalHeader` is a `<h2>`, elements in it inherit rules like `font-size` or `font-weight`. This is good when there's only text, but when there are buttons for example, it's not great.
Not sure what the solution is (and I managed to override what I wanted), but maybe someone can come up with a fix !

**Comment by GoOz** [comment]
True, I didn't think about that when I transformed this component.
Tell me if you think I'm right but I'm guessing something like that:
* If `title` props is defined we put a `h2`with the `title` string in it.
* If  just `children` then we just got a div and you have to, as a developer, put yourself your title in a heading through the `children` (if needed).

**Comment by y-lohse** [comment]
I think that would mostly work. The one situation where it wouldn't is `<ModalHeader>My Title</ModalHeader>`, but not sure that's a big problem..?

**Comment by GoOz** [comment]
Well… that would be a regression indeed, the text would lose its size & weight but I can't see how to avoid this collateral damage.

**Comment by ptbrowne** [comment]
I don't understand : the majority of the properties of `<Button/>` are defined absolutely in rems.

https://github.com/cozy/cozy-ui/blob/master/stylus/components/button.styl#L12

If I replace the `h2` by a `div` via the inspector the result is like that : 

![image](https://user-images.githubusercontent.com/465582/37613868-6a4d3144-2ba9-11e8-9670-28f6bff6bd98.png)

So apart from the horizontal margin which is a bit bigger (and which could be dealt with by setting an absolute size), I do not see the problem :/

Are you using elements other than Buttons that have the problem ?

**Comment by y-lohse** [comment]
Mh right, maybe `Button` was a bad example. I had the problem with a [`MenuItem`](https://github.com/cozy/cozy-contacts/blob/master/src/components/Modals/ContactCardModal.jsx#L18) element.

But I don't think it's safe to assume that everything inside a `ModalHeader` will have an absolute font-size defined. Or if an element used `em` for sizing I think it would be impacted too.

**Comment by GoOz** [comment]
Still, h2 tag is not supposed to have any tag as children, at least as a semantic point of view, so there's something to do here anyway.

**Comment by ptbrowne** [comment]
OK I see.

To avoid breaking backward compatibility, typeof could be used to check if children is a string, and in this case wrap it in a h2. This way we have the butter and the money of the butter ;)

**Comment by GoOz** [comment]
Oh yeah I didn't think of that. good call 🎉
