### ISSUE TITLE
Base CSS framework?

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-ui#4]
Should we use a base CSS framework? If yes, there is only one good candidate: http://www.knacss.com/

**Comment by m4dz** [comment]
For this time, I'm thinking about them. If we select a base framework, we should want a Stylus flavour of this one to improve inclusion (see #2).

Use this issue to list candidates:
* Knacss | http://www.knacss.com/
* RöCSSti | http://rocssti.net/
* Base | http://matthewhartman.github.io/base/
* Kube | http://imperavi.com/kube/

**Comment by m4dz** [comment]
Another point of attention is to use (and abuse?) of aria-* attributes to defines components behaviours and their default styles (visibility, descriptors, buttons, etc)

**Comment by GoOz** [comment]
Is this still a relevant topic?
