### ISSUE TITLE
Contacts' layout has a minor issue

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-ui#405]
![buglayoutcalendar](https://user-images.githubusercontent.com/568111/38019248-5df30066-3277-11e8-86f1-2e7d498fb534.png)

As shown on the screenshot above, there is an issue regarding the top corners of the layout. They look "round" and like there is some sort of shadow. It is only visible on larger screens.

I would expect a straight connection to the cozy bar with the same feeling there is at the bottom.

Let me know if it's not clear or you disagree!

**Comment by GoOz** [comment]
Well, this is not a bug, this is a feature. https://zpl.io/2yJXqkL
Although the content and the cozy-bar shouldn't be that close.

**Comment by jsilvestre** [comment]
Oh well, I forgot we don't have the action buttons yet. I'll talk to Claire about it then! If no change is planned, I'll close here.
Thank you!

**Comment by jsilvestre** [comment]
Ok, I talked to Claire, there is nothing to worry about. I close, sorry for the noise!
