### ISSUE TITLE
Add snapshots

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#424]
- [x] Check out [snapguidist](https://github.com/styleguidist/snapguidist) to see if it could be useful.

- [ ] Add snapshots to existing components

- [x] ActionMenu ⚠️ Not shown in styleguidist so not tested properly
- [ ] Alerter
- [x] Avatar
- [x] Badge
- [x] Button
- [x] ButtonAction
- [x] Checkbox
- [x] Field
- [x] Hero
- [ ] I18n
- [x] Icon
- [ ] Input
- [ ] IntentHeader
- [ ] IntentIframe
- [ ] IntentModal
- [ ] IntentOpener
- [x] Label
- [x] ListItemText
- [ ] Media
- [x] Menu
- [ ] MidEllipsis
- [ ] Modal
- [ ] Nav
- [ ] Overlay
- [ ] Panel
- [x] Radio
- [x] SelectBox
- [ ] SelectionBar
- [x] Sidebar
- [x] Spinner
- [ ] Tabs
- [x] Text
- [x] Textarea
- [x] Toggle

**Comment by gregorylegarec** [comment]
Actually, the main idea of Snapgitdist is to show snapshot in Styleguide.

It does not allow to run automated tests or snapshot comparisons, and cannot be set up to be used for Continuous Integration.

See https://github.com/styleguidist/snapguidist/issues/16 ans https://github.com/styleguidist/react-styleguidist/issues/877

**Comment by ptbrowne** [comment]
Adding snapshots could still be useful no ?

**Comment by gregorylegarec** [comment]
@ptbrowne You mean, in styleguidist ?

**Comment by ptbrowne** [comment]
No, in general, to components

**Comment by ptbrowne** [comment]
related https://github.com/cozy/cozy-ui/pull/452

**Comment by GoOz** [comment]
Is this issue still relevent since #452 has been done & merged?

**Comment by ptbrowne** [comment]
I think we can close
