### ISSUE TITLE
span on ButtomAction is truncate

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-ui#447]
On peut voir sur https://cozy.github.io/cozy-ui/react/#buttonaction que la version longue est tronqué en bas

![capture d ecran 2018-04-23 a 17 19 29](https://user-images.githubusercontent.com/1135513/39136226-0858d97e-471b-11e8-9cff-b021fb95eecd.png)

**Comment by GoOz** [comment]
ooooh good catch, I didn't see it. Thanks.
