### ISSUE TITLE
Modal don't show anymore after ActionMenu has been opened

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#453]
There is a very strange bug with Modal and ActionMenu. Here are the steps to reproduce : 

1. Open an ActionMenu
2. Close it
3. Open a Modal

The Overlay is shown, but the Modal is not present. Actually it is rendered but outside the viewport.

You can reproduce in the styleguide : https://cozy.github.io/cozy-ui/react/

**Comment by ptbrowne** [comment]
It's no longer the case, may have been fixed in #602
