### ISSUE TITLE
Closing a Modal invoke `secondaryAction`

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#458]
When closing, a Modal should call an `onClose` callback instead of a `secondaryAction` callback.

A secondary action could be anything, and should not be restricted to a closing action.

**Comment by GoOz** [comment]
seems legit.

**Comment by ptbrowne** [comment]
The way to solve this issues as I see it : 

- Add an `onClose` prop to the modal. This would be used instead of secondaryAction if both are there.
- Add a deprecation message to the secondaryAction callback
- In 2 major versions we deprecate completely this behavior

**Comment by gregorylegarec** [comment]
[Looks like it is some kind of legacy already handled](https://github.com/cozy/cozy-ui/blob/master/react/Modal/index.jsx#L268), but not the right way. It needs a `console.warn()`.

**Comment by ptbrowne** [comment]
A warning is shown in development: 

![image](https://user-images.githubusercontent.com/465582/39570658-4eb3c324-4ec9-11e8-8797-6b1a52cfb5d9.png)
