### ISSUE TITLE
Should mobileFullscreen be the default for Modals

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#462]
It seems we use a lot of `mobileFullscren`. This raises the question whether this argument should be by default on `Modal`. This would be a breaking change.

Advantage

- Less code

Drawbacks

- Less explicit
- A bit surprising behavior (at least to me)

[Previous discussion](https://github.com/cozy/cozy-ui/pull/461#issuecomment-385885298
) 

| with mobileFullscreen        |without mobileFullscreen           | 
| ------------- |:-------------:| 
| ![image](https://user-images.githubusercontent.com/465582/39510527-4779d920-4dea-11e8-821d-dc90ac437816.png)     | ![image](https://user-images.githubusercontent.com/465582/39510539-4eebae4a-4dea-11e8-853d-f50fdc443c56.png) |

**Comment by Claiw** [comment]
suite au precedent commentaire de @ptbrowne sur l'issue #461, en fait c'est plutôt une question d'usage. :/ 
Sur desktop où on a de la place, il s'avère qu'effectivement les modales remplissent deux rôles : 
- alerter/ confirmer une action, qui correspondrait plutôt du coup à <Modal/> : 
- présenter du contenu -> <Page /> ou <Activity />
Visuellement on a le même composant
Sur mobile, c'est différent : 
avoir une alerte/confirmation en full screen serait effectivement surprenant, il vaut mieux avoir une taille et un style qui correspondent à ce contenu là (donc non full screen)

**Comment by gregorylegarec** [comment]
As I originally asked for passing this prop to true by default, I now understand much the reasons it is not. And I am totally ok with those reasons.

**Comment by ptbrowne** [comment]
Great, closing :)
