### ISSUE TITLE
Badge example in styleguide seems broken

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#471]
It seems the margin between the badge and the icon is too big. Does ButtonAction works with Badge ?

http://localhost:6161/#badge

ping @drazik 

![image](https://user-images.githubusercontent.com/465582/39565948-2d1dccf0-4eba-11e8-9896-2cd9f09bbaa0.png)

**Comment by drazik** [comment]
Actually it's because we introduced minimum width/height on ButtonAction. Maybe a more visual/effective example would be better. But there is no bug here.

**Comment by ptbrowne** [comment]
Thanks !
