### ISSUE TITLE
Utility classes for cursors

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#478]
It would be nice to have

```
.u-c-help {
  cursor: help
}

.u-c-pointer {
  cursor: pointer
}
```

What do you think ?

**Comment by GoOz** [comment]
why not. :)

**Comment by ptbrowne** [comment]
I've only ever used `help` and `pointer`, so I think we can stick with only those two and wait if the need arise of others :)

**Comment by GoOz** [comment]
Cool, I was more inclined to do that too :)
