### ISSUE TITLE
Modal width coherence between different media width

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-ui#490]
When we choose a xxlarge size, this means we need almost the full width, especialy if the screen is narrow, But here the width percentage of the screen is smaller for a small screen than for a wider screen, what is I think the opposite of the need of someone specifiying `size='xxlarge'`.
in the exemple bellow, the second window is a bit smaller and the modal is much smaller what leads to a width percentage much smaller than on a wider window... 
![image](https://user-images.githubusercontent.com/1266420/39956301-e604ccf8-55dd-11e8-98c4-fe51d53b5a62.png)
I suggest the the width of "xxlarge" modal is a fix percentage of the width whatever the media width and bellow a certain width it turns into a fullscreen modal.

**Comment by ptbrowne** [comment]
@Claiw @gooz What do you think ?

**Comment by GoOz** [comment]
Not sure… I'd rather wait for @Claiw 's opinion

**Comment by Claiw** [comment]
Hi, I saw the case, I need to think a bit about it before, can we discuss about it tomorrow or on friday?

**Comment by ptbrowne** [comment]
Have you had time to discuss about this ?

**Comment by GoOz** [comment]
Nope.
