### ISSUE TITLE
top right close button in modal overlaps title

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-ui#491]
it happens for any width (here size='xxlarge')
![image](https://user-images.githubusercontent.com/1266420/39957131-c3876ff4-55ed-11e8-829f-2e2b56a8e386.png)
![image](https://user-images.githubusercontent.com/1266420/39957132-c7cd5e0c-55ed-11e8-8243-ce6022d9a89f.png)

**Comment by ptbrowne** [comment]
I fixed : it will be available in the next version of Cozy-UI.
