### ISSUE TITLE
Moment scrolling on iOS

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#493]
`-webkit-overflow: scrolling` should be used.

https://github.com/cozy/cozy-banks/blob/68bf622beaf1bfbf6e8ca198118764f98165abbf/src/styles/main.styl#L12-L14

```
html, body
    +small-screen()
        overflow-y scroll // necessary for momentum scroll on ios
        -webkit-overflow-scrolling touch // necessary for momentum scroll on ios
```

**Comment by GoOz** [comment]
@ptbrowne Based on what we talked about with @kosssi, I guess we can close this one, can't we?
