### ISSUE TITLE
Modal semantic

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#494]
Some little semantic concerns about the Modal, no emergency at all:

* As we _close_ the modal, in the README we should try to always name our flag `modalOpened` instead of `modalDisplayed`. It could also be a good practice to do so in our apps codebases.
* The close button is still called `cross` in the comment and README, I think it should be updated to `close button` (same remark for properties `crossClassName` and `crossColor`, those names make me remind me concepts like _cross-platform_).

![](http://europeanjournalists.org/fr/wp-content/uploads/sites/2/2015/08/Camus-800x400.jpg)

**Comment by ptbrowne** [comment]
Nice.

Related article: https://m.signalvnoise.com/hunting-for-great-names-in-programming-16f624c8fc03

> The close button is still called cross in the comment and README, I think it should be updated to close button (same remark for properties crossClassName and crossColor, those names make me remind me concepts like cross-platform).

So `closeBtnClassName`, `closeBtnColor` ?
