### ISSUE TITLE
Need a logo?

### ISSUE THREAD

**Issue by nunojesus** [cozy/cozy-ui#503]
I think this project is really good, so I would like to contribute with something, so as a graphic designer I could design a logo if you want.

Greetings and congrats for this project.

**Comment by Claiw** [comment]
Hi @nunojesus !
Thank you so much for your encouragement. :) 
I'm Claiw, product designer at Cozy Cloud !
If you have some time, would you like to test some ideas for the cozy-ui logo ? 
You can find some exemples of our visual identity below : 
- create-cozy-app logo : https://github.com/CPatchane/create-cozy-app

identity of cozy cloud : we tend to have some flat identity with subtle gradiants
type of illustrations we have : 
- exemple on the banner: https://twitter.com/cozycloud
- characters : 
ex people style:
<img width="703" alt="screen shot 2018-05-17 at 12 06 20" src="https://user-images.githubusercontent.com/31621610/40171328-37fb967c-59cb-11e8-9389-eaf85d0cfa10.png">
ex features style :
<img width="403" alt="screen shot 2018-05-17 at 12 10 48" src="https://user-images.githubusercontent.com/31621610/40171388-65fb6502-59cb-11e8-9fb2-97d1abb31b04.png">

you can find some branding on this page : https://cozy.io/fr/press/
and for the illustrations, the colors we use : 
<img width="565" alt="screen shot 2018-05-17 at 12 04 53" src="https://user-images.githubusercontent.com/31621610/40171514-bfabae4a-59cb-11e8-941a-cc0e8491d06c.png">

If you have any questions, don't hesitate :) 

Best regards,
Claiw

**Comment by nunojesus** [comment]
I think the cloud its really good, do you have something in mind?

**Comment by ptbrowne** [comment]
Closing since there is no more activity.
