### ISSUE TITLE
Remove duplication from `build.styl` and the stylus files in each React component

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#514]
In each React component, there is a stylus file that is "instantiating" the stylus placeholders. The `build.styl` also does that. Maybe we could use the react component stylus files to generate the build.css (compile each stylus file and concatenate the result). This would remove a lot of code that is in `build.styl`. Some code would still need to be there to instantiate global classes (utility classes for example).

**Comment by GoOz** [comment]
Good idea 👍
