### ISSUE TITLE
<Icon /> with undefined icon property make the application crash

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#528]
If an `undefined` value is provided for the `icon` attribute of the `<Icon />`, the following error occurs and the whole application crashes (At least it is the case for Collect).
```error
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
```
I think we should prevent contributor for making their own app crash when an icon is missing or not defined. At least we could log an error to warn him.

**Comment by ptbrowne** [comment]
I think the rationale behind this was that you should discover your error as soon as possible. Why would you pass a undefined `Icon` ? Is it not an error on your side ?

**Comment by ptbrowne** [comment]
Seems a warning could be sufficient here.

**Comment by ptbrowne** [comment]
Is #533 ok with you @gregorylegarec  ?

**Comment by gregorylegarec** [comment]
Yes, thanks @ptbrowne.

Sorry I did not take time to reply since last week but I was pretty busy on Collect and Store publication stuff.

To reply to your first comment, in my opinion an application should never ever crash in production. By the way, I agree with you in the fact that a lib should throw errors when unexpected configuration, variables or states are happening, to detect them in the development stage.

However, in the case of the `<Icon />`, it's a little bit tricky because the `icon` attributes is often something coming from the file system, like `const icon = require('assets/myicon.svg')`, and the file system is a pretty sensitive part of the application. File system errors may occurs in production and not in development. It could be due to network issues, case issues, or missing file issues.
I created this Github issue because I forgotten to `git add` in a commit the fallback icon for our data types in Collect. So the whole thing was working perfectly well in my development environment.

As our release workflow is a little bit weak, I cherry-picked the commit into the `prod` branch (a merge would have been the same effect). And five minutes later the missing icon was in production, making the `<Icon />` component throw an error and the whole application crash. Netflix modal was inaccessible and it did cost us a user which deleted this account immediately.

I am perfectly aware that the first cause of the problem was coming for our weak release workflow, however I think that variables potentailly coming from File System should be always try/catched and should not cause an Exception.

**Comment by ptbrowne** [comment]
I understand your point.

> I think that variables potentailly coming from File System should be always try/catched and should not cause an Exception.

If the icon is coming from the filesystem and is not there, it will crash at build time, so we already have a security here.

> I created this Github issue because I forgotten to git add in a commit the fallback icon for our data types in Collect.

For the record, this can be catched by a test.

> This offers us an additional security to keep our applications working, even when we fail in other ways.

Yes I agree :) Furthemore, I think since the Icon is purely cosmetic the balance advantage/inconvenient of its presence/absence is clearly in favor of not crashing even if absent, you are right :)
