### ISSUE TITLE
Font fighting on some elements

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#54]
normalize.css sets the `font-family`of certain elements, for example [buttons](https://github.com/necolas/normalize.css/blob/master/normalize.css#L257). In cozy-ui, we [rely on inheritance](https://github.com/cozy/cozy-ui/blob/v3/stylus/cozy-ui/defaults.styl#L42) to propagate the default font.

This means that buttons with no extra font-declaration get the default sans-serif instead of our Lato. There are actually a few places in our v3 UIs where the wrong font is used, most notably the selection bar in files.

Not sure of the best way to fix this. Should we just declare the `font-family` on a lot more elements in the default styles? Ping @GoOz and @m4dz for input.

**Comment by GoOz** [comment]
Good catch. I guess we could just force the use of Lato on buttons, select, etc using the .coz-btn class and such. As we don't really care about what looks like an unstyled element.
Any thought @m4dz?

**Comment by y-lohse** [comment]
Well, the default `coz-btn` carries quite a bit of extra style with it (backgroud, paddings, etc). Again, I'm mostly thinking about the buttons in the selection bar in files (which, to be fair, could be `a`'s instead of `button`'s), but I'm sure there are others out there.

**Comment by GoOz** [comment]
Fixed in #72
