### ISSUE TITLE
😱 Close button is misplaced in intent modal

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#545]
Looks like a regression

![capture d ecran 2018-06-15 a 12 07 23](https://user-images.githubusercontent.com/776764/41462943-ee17e80e-7094-11e8-98b7-c9f06f8a3778.png)

**Comment by GoOz** [comment]
really? I can't see it on styleguidist. :/

**Comment by ptbrowne** [comment]
Can you give use more information on how to reproduce the problem ?

**Comment by gregorylegarec** [comment]
@ptbrowne You can have a look at http://recette-interapp-sandbox.cozy.works

**Comment by GoOz** [comment]
Ok I found the issue. It's related to #335. Giving more weight to the selector should fix this, temporarily at least.

**Comment by ptbrowne** [comment]
Has been fixed by https://github.com/cozy/cozy-ui/pull/546
