### ISSUE TITLE
iPhoneX layout

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#549]
Some minor tweaks need to be done.

See https://github.com/cozy/cozy-drive/pull/992/files

**Comment by GoOz** [comment]
I'm wondering if it's useful at all. This chunk of code is meant to be used within an app. 
Our webapp is already working well on iPhone X in Safari.

**Comment by y-lohse** [comment]
I'm afraid that's not always the case no. I think the safe-margin especially would be a good addition to cozy-ui. Typically the menu has problems:

<img width="332" alt="capture d ecran 2018-06-19 09 55 12" src="https://user-images.githubusercontent.com/2261445/41584205-faca8e84-73a6-11e8-80a3-4c77aaa2fed7.png">

In landscape everything works but we don't use the whole screen:

<img width="664" alt="capture d ecran 2018-06-19 09 57 28" src="https://user-images.githubusercontent.com/2261445/41584317-47622af4-73a7-11e8-8a62-cf714f289a07.png">

**Comment by GoOz** [comment]
How the hell all our apps have different rendering on iPhone X? There's no consistency at all… This is voodoo!
