### ISSUE TITLE
A button icon

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#554]
![screenshot-20180627-1743](https://user-images.githubusercontent.com/701648/41984772-ccf41b56-7a31-11e8-86b5-5ac0b47beafe.png)

Hi,
I have several use cases when we need small button icon.
I checked with @GoOz if `<Chip.Button>` could fit my needs (https://docs.cozy.io/cozy-ui/react/#chip) and it could not.

So I would like a `<Button.Icon>` to render thing like above or below:

![screenshot-20180627-1748](https://user-images.githubusercontent.com/701648/41984987-5eff0a6a-7a32-11e8-89f9-1930f9bb601d.png)

**Comment by ptbrowne** [comment]
Do you have a component already in cozy-contacts or does it need to be developed from scratch ?

**Comment by GoOz** [comment]
As far as I remember @enguerran "built" it with available option and added some styles.
I didn't dive into the subject yet but I'm not sure there's really a need for a new separated component.

**Comment by enguerran** [comment]
The code I was refering to
https://github.com/cozy/cozy-contacts/blob/2427939d4722b4f557ee4d80fea50e8827c30f16/src/components/ContactCard/ContactFormField.jsx#L67-L78

As it seems that I am the only one with this needs since 27th june, I can conclude that I have a special use-case that can't be handled by the components library.

**Comment by GoOz** [comment]
> As it seems that I am the only one with this needs since 27th june…

Yet! I believe that most the time, @Claiw tries to reuse UI components, I'll ask her.
