### ISSUE TITLE
impossible to disconnect from mobile on safari

### ISSUE THREAD

**Issue by Claiw** [cozy/cozy-ui#567]
Hi, 

When you go on the platform navigation, when the view adapt from minimal UI to default UI you can't access the disconnect entry in the menu, it's going under the bottom bar of safari

**Comment by GoOz** [comment]
I guess this is more a cozy-bar issue but I'll look into it.

**Comment by GoOz** [comment]
That's what I thought, it's a bug from Cozy-bar. 
I created an new issue there https://github.com/cozy/cozy-bar/issues/216 and closing this one.
