### ISSUE TITLE
Avatar when contact name is too long

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#572]
Described here: https://github.com/cozy/cozy-contacts/issues/212

with `"SELARL ANQUETIL-LELIEVRE & ASSOCIES"`

![](https://user-images.githubusercontent.com/1107936/42925587-f9749684-8b2e-11e8-92b4-7df150fbfc64.png)

**Comment by ptbrowne** [comment]
Can you please point us to the relevant code ?

**Comment by ptbrowne** [comment]
I see that in https://github.com/cozy/cozy-contacts/blob/master/src/styles/contacts.styl#L57 , the container of the Avatar is in flex-mode which cancels the width of the Avatar. I would investigate in this direction.

**Comment by ptbrowne** [comment]
@enguerran I think it is a problem of the application code and not of the Avatar itself. I would close if you agree.

**Comment by enguerran** [comment]
:+1:
