### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#582]
The `input[type=date]` is not supported by Internet Explorer and Safari. It would be good to have one. It should not be coded manually.

- internationalization
- only choose year
- only choose time
- choose date and time

**Comment by y-lohse** [comment]
@ptbrowne  do we have date pickers somewhere in cozy?

**Comment by ptbrowne** [comment]
We have one for the transfer flow in Banks. We could have one in contacts to choose the birth date of someone ?

**Comment by ptbrowne** [comment]
Related: components/DateMonthPicker recently added

**Comment by JF-Cozy** [comment]
Les specs sont maintenant sur Figma, je ferme ici pour nettoyer les issues
