### ISSUE TITLE
Alerts are displayed under Modals 

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-ui#585]
I stumbled upon a complex use case.

On desktop alerts are above everything but that's not the case on mobile. The alerter comes from under the nav and stops just above it.
That's the default behaviour. 

But in my case I have a fullscreen modal that triggers alerts and obviously that alerts pops under the modal so it's unfortunately not visible. The rendering I want is this:

<img width="322" alt="screenshot 2018-08-03 16 09 58" src="https://user-images.githubusercontent.com/1280069/43647533-280766ba-9738-11e8-9d92-c197000c194d.png">

So I was wondering if there would be a way to get the alert popping **inside** the modal instead of a direct children of the `body` whilst the original Alerter stays in the `body`.
That way It could be styled because we would know the context from within.

Pinging @goldoraf @y-lohse because it's for your sharing modal. ;)

**Comment by ptbrowne** [comment]
Discussed with GoOz : I think it would be simpler if the z-index behaved correctly from the start. Since the z-index must change depending on if a modal is displayed (I let GoOz explain, I forgot why), one solution would be to add a class to the body when a modal is displayed to change the z-index of the different layers.

**Comment by GoOz** [comment]
Indeed, setting a class on the `body` when a modal is displayed should do the trick.

And yes I'll explain better and try to be concise.

**Normal behaviour (mobile only): Alert -> Nav -> Modal**
*Alert* is under *Nav* because, when it pops, in comes from behind the *Nav*, goes up and stops above.
*Modal* is over *Nav* because, well, it must be over the *Nav* since it covers the screen.

**Exception behaviour: Nav -> Modal -> Alert**
When a *Modal* triggers an Alert, this must be over the *Modal* so it can be viewed.
And since the *Modal* is already over the *Nav*, there's no issue having the *Alert* over the *Modal* AND the *Nav*

**Comment by ptbrowne** [comment]
Thanks GoOz for the explanation :) I've edited the title of the issue to state the problem in a neutral way since we have departed from the original problem / feature.
