### ISSUE TITLE
Button PropTypes

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-ui#586]
`Button` component is waiting a `ReactNode` as a prop-type for `icon` props:  
https://github.com/cozy/cozy-ui/blob/8dba1b914eca7945e3f6e3295b714de128300b99/react/Button/index.jsx#L99

But in an application of mine, I get this warning in the console:
```
Warning: Failed prop type: Invalid prop `icon` supplied to `Button`, expected a ReactNode.
```

The `icon` object value I pass as a props is either a `string` or a svg loaded by a webpack loader.
Nevertheless, `Button` is defined in `cozy/cozy-ui` with https://github.com/cozy/cozy-ui/blob/8dba1b914eca7945e3f6e3295b714de128300b99/react/Button/index.jsx#L75

But `BaseButton` is https://github.com/cozy/cozy-ui/blob/8dba1b914eca7945e3f6e3295b714de128300b99/react/Button/index.jsx#L67

So in `BaseButton`, the icon variable could contain a `string` ([as shown here](https://docs.cozy.io/cozy-ui/react/#!/Button/14)) or a `ReactNode` ([as shown here](https://docs.cozy.io/cozy-ui/react/#!/Button/16)).

But when I pass an `icon` variable with a `svg` loaded by a webpack loader, everything works fine.

What could we do to enhance the API and PropTypes definition?

**Comment by ptbrowne** [comment]
```
icon: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.node,
    PropTypes.string
  ])
```

Do you think this could work ?

**Comment by enguerran** [comment]
Why `PropTypes.object`?
How should we use the icon props in a `Button` usage?

Here is a list:
```js
<Button icon="plus" />
<Button icon={<Icon icon='delete' color='yellow' />} />
// or with a full svg react component
<Button theme="danger" icon={<svg width="16" height="16"><circle cx="8" cy="8" r="4" stroke="green" stroke-width="2" fill="yellow" /></svg>} label='delete' />
// or with the webpack svg-loader which I don't know how it works
```

**Comment by ptbrowne** [comment]
The object is for the SvgLodader object.

It could be improved into: 

```js
const svgLoaderLikeObject = PropTypes.shape({
  id: PropTypes.string.required
})

PropTypes.oneOfType([
    svgLoaderLikeObject,
    PropTypes.node,
    PropTypes.string
  ])
```

**Comment by ptbrowne** [comment]
> What could we do to enhance the API ?

I personally like the fact that it can handle various ways of loading an icon. Do you think it makes the API confusing ?

> How should we use the icon props in a Button usage?

I don't understand the question.

**Comment by ptbrowne** [comment]
> The API is ok, but the documentation and the code are not synchronised.

You're right, the proptypes are missing the svgLoader way.

> Do we have to give a React svg Element or an Cozy-UI Icon element ?

You can do both.

I think that the PropTypes for the icon prop in Button should reflect that it is a union of 

* what is accepted by `Icon`
* A node

I think we could have something like : 

Icon.jsx

```
export const iconPropType = PropTypes.oneOf([
    svgLoaderLikeObject,
    PropTypes.string
])
```

In Button.jsx

```
import { iconPropType } from '../Icon'

Button.PropTypes = {
  icon: PropTypes.oneOf([ iconPropType, PropTypes.node ])
}
```

IMHO, it would correctly reflect that if passed something usable by `Icon`, Button will use the `Icon` otherwise it will directly render the node passed.

> Documentation and code are not clear about it.

In the React documentation, it is written "You can also pass an Icon directly if you need more flexibility.", I thought that was clear, do you see anyway to enhance the doc ?

**Comment by enguerran** [comment]
I will make a summary:

- [ ] Documentation are not clear about svg loader → add an example for it
- [ ] PropTypes need an update → update the proptypes like explained above

If I forget something, tell me I'll add it.

**Comment by ptbrowne** [comment]
That looks good, do you want to make a PR ?

**Comment by enguerran** [comment]
Hi,

As it is non blocking I don't know when or if I will make changes.
If someone wants to improve the library ([a good summary is above](https://github.com/cozy/cozy-ui/issues/586#issuecomment-410749670)) and wants to become a contributor, feel free as it is an easy pick.
