### ISSUE TITLE
Add SelectionBar in documentation

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#589]
These components are missing in the documentation:

- [x] Text components
- [x] Tabs
- [ ] Selection Bar

**Comment by GoOz** [comment]
Also, it's missing `SelectionBar` & `Tabs` components.

**Comment by Crash--** [comment]
SelectionBar has been added https://docs.cozy.io/cozy-ui/react/#/Layout%20components?id=selectionbar
