### ISSUE TITLE
Sentry issues : cozy-ui/react/ActionMenu/index in options errorCannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#618]
Currently taking a look at our Sentry issues and this one appears & affect a lot of users. I don't know exactly if it breaks something or not but if I can clean up our logs... ;)

```
TypeError
Cannot read property 'addEventListener' of null
./node_modules/cozy-ui/react/ActionMenu/index.jsx in options at line 115:18
    const close = once(() => {
      this.menuNode.removeEventListener('transitionend', close)
      this.close()
    })
    this.menuNode.addEventListener('transitionend', close, false)
    // in case transitionend is not called, for example if the element is removed
    setTimeout(close, TRANSITION_DURATION)
    this.applyTransformation(1.1)
  }
```

I don't know how it can happen, but I can add a simple check before adding the eventListener. What do you think ?

**Comment by y-lohse** [comment]
The check sounds like an ok solution to me, although I'd be curious to find out when and how `menuNode` can be undefined.
