### ISSUE TITLE
Pointer events on empty views

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#646]
In [this commit](https://github.com/cozy/cozy-ui/commit/1ca30cfe7b82c5947e41ea5a6cf98c98ab467016#diff-560bd4454f1e9db134430fe3f2da44a3R39), we removed pointer events from the `Empty` component. IIRC it was to avoid catching clicks in the cozy-bar.

But the problem is, some empty views can contain buttons, and those don't work on tablet/mobile. [The doc mentions this option](https://docs.cozy.io/cozy-ui/react/#empty), although the example don't render at the moment.

I'm not sure what the correct solution here, is, as removing the rule will create problems with the cozy-bar again..?

**Comment by GoOz** [comment]
The quickest way would be to set `pointer-events: auto;` to the clickable element I guess.

**Comment by ptbrowne** [comment]
Mmh, why should an empty view have no pointer events ? It is a very surprising behavior.

**Comment by GoOz** [comment]
Because it has a `position: fixed` on mobile to be sure it's well centered. Maybe it could be fixed more elegantly though.

**Comment by ptbrowne** [comment]
> Maybe it could be fixed more elegantly though.

Yes ;)

**Comment by GoOz** [comment]
yes we have a card to fix this in our backlog

**Comment by y-lohse** [comment]
Possibly solved by https://github.com/cozy/cozy-ui/pull/836

**Comment by y-lohse** [comment]
Yep!
