### ISSUE TITLE
Complex modal

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#653]
As discussed with @GoOz we need to do some work on our Modal component to deal with this kind of complexity. 

This modal has : 
- a "fixed" content 
- a scrollable (long) content 

<img width="1452" alt="capture d ecran 2018-10-19 a 18 10 30" src="https://user-images.githubusercontent.com/1107936/47230352-4dfbc400-d3ca-11e8-92b1-dee47ccf75e8.png">

(See https://github.com/cozy/cozy-drive/blob/master/src/sharing/ShareModal.jsx#L35 for details)

**Comment by ptbrowne** [comment]
What are the foreseen tasks ?

**Comment by Crash--** [comment]
I think we can imagine having our Modal (i don't know so much the current implementation yet) 
- supporting X ModalContent
- adding props to ModalContent in order to manage fixed content & scrollable ones 

I think @GoOz has a more precise idea of the work to do, right ? ;)

**Comment by Crash--** [comment]
@GoOz ? :)

**Comment by GoOz** [comment]
Sorry, yes that's pretty much the idea. It's in my todo list, but not in the first position. :|
