### ISSUE TITLE
barre de notifications en mobile - Assombrissement

### ISSUE THREAD

**Issue by joel-costa** [cozy/cozy-ui#660]
@Claiw faisait remarquer qu'on avait une barre de notifications tout en haut du smartphone qui conserve sa couleur de fond quand on assombri l'écran (pour une modale par exemple). Est-ce qu'on pourrait faire en sorte que la barre de notifications s'assombrisse en même temps que le reste de l'écran ?

**Comment by GoOz** [comment]
Je suis pas sûr de comprendre, t'aurais un screenshot parce que je vois pas de quoi tu parles :/

**Comment by Crash--** [comment]
![d1402d5d6aa49e63e591c495bfe275c0](https://user-images.githubusercontent.com/1107936/47551899-ab7c9d00-d903-11e8-8ca1-a14d9efa1673.png)

Y a des plugins cordova pour gérer ça... Mais est-ce que c'est à UI d'avoir des dépendances Native ou c'est à l'application de gérer ce genre de chose ? 

Je pencherai quand même pour la première

**Comment by GoOz** [comment]
Ok je vois mieux. Honnêtement je doute un peu sur le bien fondé d'avoir du code natif dans UI mais je suis pas trop au fait du natif donc…
J'invoque @ptbrowne dans la conversation qui aura à mon sens un avis plus éclairé que moi sur la question.

**Comment by Crash--** [comment]
Ou alors il faut un callback sur nos menu pour que l'app soit au courant ?

**Comment by ptbrowne** [comment]
> Ou alors il faut un callback sur nos menu pour que l'app soit au courant ?

👍

**Comment by Crash--** [comment]
In fact, we already have an `onClose` props. Should be enough to do it :). 

But... As cozy-ui is also used in our native applications,  having `native versions` of UI's components - if needed-  is not messy, right?
