### ISSUE TITLE
Translate & Context

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#662]
With `preact` context was passed to all children even if they didn't subscribe to it. 

Since the switch to `React`, if we want to use the current I18n implementation, we need to add `contextTypes` in every component that needs translation or we need to use `translate()` and change `const { t } = this.context` to `const { t } = this.props`  

See the diff between React & Preact : https://github.com/developit/preact-www/blob/master/content/guide/differences-to-react.md#whats-different 

Using the new React Context API should solve our issue?

**Comment by y-lohse** [comment]
At first I also thought the new Context API could help, but actually I don't think so. The new API would force is to us to wrap every component in a `I18nConsumer` or something like that, which is hardly more practical than the `translate()` HOC.
We can do more research on this but it appears using a HOC, a ContextConsumer or explicitly declaring the `contextTypes` are the recommended ways to go about doing this.

**Comment by Crash--** [comment]
If we use ` translate()` - which is fine by the way -, do we still need to wrap our applications with `<I18n>` ?

**Comment by ptbrowne** [comment]
Yes since I18n provides the context.

**Comment by ptbrowne** [comment]
Can we close ?

**Comment by Crash--** [comment]
Yep! Just something to keep in mind when migrating our Apps to React
