### ISSUE TITLE
Buttons on the same line in mobile modal 

### ISSUE THREAD

**Issue by Claiw** [cozy/cozy-ui#667]
I would like to improve this behaviour :
<img width="360" alt="screen shot 2018-10-30 at 15 04 20" src="https://user-images.githubusercontent.com/31621610/47723666-49020480-dc55-11e8-960c-066bfa4a1b45.png">

Behaviours I would like when button labels are sufficiently short : 
<img width="380" alt="screen shot 2018-10-30 at 14 56 47" src="https://user-images.githubusercontent.com/31621610/47723085-11df2380-dc54-11e8-900b-dcb2fd2fa1a1.png">
<img width="371" alt="screen shot 2018-10-30 at 14 58 23" src="https://user-images.githubusercontent.com/31621610/47723189-494dd000-dc54-11e8-802e-d4117dc89fb4.png">
When button labels are too long to fit correctly in the modal, we can return in the actual behaviour (the first screenshot in the beginning)

There is however an exception : when you are in a funnel : 
<img width="370" alt="screen shot 2018-10-30 at 15 09 12" src="https://user-images.githubusercontent.com/31621610/47723948-e5c4a200-dc55-11e8-8bf0-3023f3e1948b.png">

**Comment by GoOz** [comment]
Fixed by #854
