### ISSUE TITLE
Inconsistent height/width for modal with `mobileFullScreen` and `overflowHidden`

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#668]
In the store I have a modal with these props to fit all the screen on mobile. But on desktop I also pass a `height="35rem"` to avoid using all the height of the page. But passing this height is breaking the scroll behavior on mobile in the full screen modal. 
I was wondering if we should instead use the `height`/`width` only if we are not on a mobile breakpoint in the case we use `mobileFullScreen` and `overflowHidden`?
Here is the related store fix: https://github.com/cozy/cozy-store/pull/437

**Comment by CPatchane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[STO/HOME] Je n'ai pas de scroll sur la modale de connexion d'un connecteur](https://trello.com/c/TGHkbqQV/391-sto-home-je-nai-pas-de-scroll-sur-la-modale-de-connexion-dun-connecteur)

**Comment by GoOz** [comment]
To make sure I understand what you meant, you propose that if both `mobileFullscreen` and `width/height` props are set, then the modal by itself, cancel the `width/height` props on mobile so you don't have to do what you did in your PR on the store ?

If so, it seems legit.

**Comment by CPatchane** [comment]
Yes, that's my point exactly @GoOz

**Comment by ptbrowne** [comment]
I don't understand what you have to set the height to 35rem , where is this value coming from ?

**Comment by ptbrowne** [comment]
Seems weird to me that a property cancels another one, this is a recipe for bugs. The propery is not called `desktopOnlyHeight`.

**Comment by CPatchane** [comment]
Here is my modal without this height property @ptbrowne 
<img width="1104" alt="screenshot 2018-10-31 at 11 30 20" src="https://user-images.githubusercontent.com/10224453/47782348-4d372c00-dd00-11e8-93fb-0fb13e5a0489.png">
I have to use it to remove the bottom margin (this is an intent inside the modal)

**Comment by drazik** [comment]
Is it not possible for you to pass the `height` prop only on desktop viewport ?

**Comment by GoOz** [comment]
The more you have options & flexibility, the more you have risks of conflicts. Handling in advance conflicts seems the right idea to me.
Unless we can figure out ways to avoid those conflicts but in this case I don't see how.

**Comment by ptbrowne** [comment]
Why is the height not controlled by the content ?

**Comment by GoOz** [comment]
I guess because the intent is an iframe.

**Comment by ptbrowne** [comment]
I think the intent case is a very specific one and it may be better to fix the intent case. The intent should maybe send the height of the page so that the iframe can be resized ?

**Comment by CPatchane** [comment]
As you said it's maybe a specific behaviour due to the intent here, maybe we can do this job in the [`IntentModal`](https://github.com/cozy/cozy-ui/blob/master/react/IntentModal/IntentModal.jsx#L33) which is the one concerned here. If we have the `mobileFullScreen` we remove the `height/width`.
But, what is the interest of having the `height/width` inline on the wrapper if we have the full screen behaviour on mobile?

**Comment by ptbrowne** [comment]
> But, what is the interest of having the height/width inline on the wrapper if we have the full screen behaviour on mobile?

I am not a fan of the `mobileFullscreen` property. Tying together properties like this is [complecting](https://www.infoq.com/presentations/Simple-Made-Easy). You have to remember that when `mobileFullscreen` is set, `height` and `width` are ignored.

I think this issue is showing a bug in the initial implementation. Since the iframe does not have the height of its content, it puts the responsibility on its parent to have a height that is big enough. We don't know a priori the necessary height. This is why we have a magic value 35rem. IMHO, the intent should send the height information of its content to the app, and the app should take appropriate action to resize the container accordingly.

**Comment by drazik** [comment]
I also think that the best solution would be to get the height from the intent and then use it to show the modal the best way we can.

Also yes, maybe the `mobileFullScreen` prop should just be `fullscreen` and the app set it to `true` or `false` according to the viewport :thinking:

**Comment by gregorylegarec** [comment]
There is already a mechanism of setting the iframe dimensions from an intent service but I think that this existing solution shoukd be refined. IMHO the intent lib can handle transparently intent dimensions and set up client dimensions accordingly.

**Comment by ptbrowne** [comment]
I think we can close this ?

**Comment by y-lohse** [comment]
No updates since the last message, closing this. Prs are welcome to improve the `IntentModal` and making this integration easier fo course.
