### ISSUE TITLE
The place of the IconSprite

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#674]
With the last major cozy-ui version, the `<IconSprite />` must be included in the application in order to have it in the DOM and to use it.
The problem is that the `cozy-bar` also uses `cozy-ui` so needs that icon sprite but the `cozy-bar` must not rely on the application since it must be independent (must work for an application which doesn't use cozy-ui).
So I see many solutions to this issue (temporary or not):
- My preference will be to let the bar handle the cozy-ui sprite inclusion into the DOM tree. On the one hand the `cozy-bar` will have to be with the last version of cozy-ui to have the last sprite but on the other hand the sprite doesn't change a lot to be often blocking
- The bar have to include its own namespaced sprite, but each time we will have to use a new icon (or a component from cozy-ui needs a new icon) we will have to add it into this namespaced sprite manually (or add all cozy-ui icons in one shot)
- Let the stack handle the icon sprite as a placeholder `{{.UISprite}}` but it seems heavy and add more dependency to the stack
- Add also the sprite in the bar, make things twice but the priority in the app code will be the first sprite found which will be the bar one since it's before the application in the DOM tree.

**Comment by CPatchane** [comment]
For now, the bar will require the needed icons by itself in the sprite to be independant, see https://github.com/cozy/cozy-bar/pull/332/commits/d58bd1e5432b738bc5393936f8c354ee0fab7d0e

**Comment by ptbrowne** [comment]
I think it is possible to import the icons directly from cozy-ui : 

`import topIcon from 'cozy-ui/assets/icons/ui/top.svg'`

**Comment by y-lohse** [comment]
I actually think the current approach is the correct one.

I'd rather not let the apps rely on the bar to get their icons, it's not intuitive and would require bar updates to get new icons, which isn't always possible.

Is there a major problem with how things are done at the moment? I'm guessing you're not importing new icons very often in the bar?

**Comment by y-lohse** [comment]
Closing this since everything seems ok.
