### ISSUE TITLE
Utility classes

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#687]
We've previously decided we want to expose a collection of utility classes in cozy-ui. We want to be able to use them in components, both in cozy-ui and in our apps.

I think a good target is a collection like the one in [Tachyons](http://tachyons.io/docs/):

- Everything for typography — fonts, sizing, etc
- Spacing (padding, margin, width, height)
- Positioning (display, position, flexbox, grid, floats, …)
- Colors (background, borders, colors)
- Other (hovers, animations, shadows, opacity)
- Everything needs to be responsive

Right now we [have this](https://docs.cozy.io/cozy-ui/styleguide/section-utilities.html):

- Titles (but not font-size)
- Cursors
- Hide/show elements with media queries
- Spacing (non-responsive)
- Text color
- Ellipsis

_______

Most of it can be configured from a set of variable, for exemple [this one](https://github.com/tachyons-css/tachyons-custom#src_variablescss). We already have some if these in cozy-ui and it wouldn't be too much work to define the missing ones.

To actually generate the css classes, we can write the generator function ourselves ([we have one for spacers for example](https://github.com/cozy/cozy-ui/blob/master/stylus/utilities/spaces.styl)).

We could use [tachyons-custom](https://github.com/tachyons-css/tachyons-custom) as a base, but that would mean:

- rewriting everything related to the color palette as they are more or less hard-coded
- inheriting the class names, including those for responsive classes
- since we'd change the source code, it would be a fork and we would not get future updates

I think using tachyons-custom would mean copying over a lot of code in our repo, changing it and maintaining it, and I don't think we want to do that. On the other hand, defining all the important variables somewhere is something we need anyway (re. material-ui), and writing the generator functions off will take work, but should be achievable.

So I suggest the following next steps:

- Generate responsive spacing classes using our set of breakpoints
- Generate border and background color for our palette
- Add variables for all things typography related and generate custom, responsive classes of them
- Add responsive utility classes for positioning (display, position, flexbox)
- Add utility classes for the "other" things (hovers, animations, shadows, opacity)

This would take us about 90% of the way and it seems doable.

Any thoughts on this?

**Comment by y-lohse** [comment]
Just a quick "up" on this — if there are no comments then this will be the plan and I (or anyone who feels like it) can start working on the next actions.

**Comment by GoOz** [comment]
Yeah, I think so too. 👍

**Comment by y-lohse** [comment]
This is largely implemented now.
