### ISSUE TITLE
Remove delete-grey08, upload-grey08, share-08 icons

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#705]
These icons are available to be used by the component `<Icon />`, I would suggest to remove them from the `icons/ui` folder since those are icons with colors. At least, we can remove them from the `<IconSprite />` to not use them through `<Icon />`.

https://github.com/cozy/cozy-ui/commits/master/assets/icons/ui/delete-grey08.svg
https://github.com/cozy/cozy-ui/blob/master/assets/icons/ui/share-grey08.svg 
https://github.com/cozy/cozy-ui/blob/master/assets/icons/ui/upload-grey08.svg

**Comment by ptbrowne** [comment]
Go :)

**Comment by kosssi** [comment]
I propose that we list the places where we use its icons to delete them if it is no longer used?

- Cozy Banks don't use it

**Comment by y-lohse** [comment]
They have been removed.
