### ISSUE TITLE
Add "dual field" component

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-ui#710]
As it is used for [authentification](https://github.com/cozy/cozy-ui/pull/708).
<img width="504" alt="screenshot 2018-11-22 11 08 35" src="https://user-images.githubusercontent.com/1280069/48896113-1d82cc00-ee47-11e8-81a8-dfce01daeee5.png">
May need a little bit of Design specifications.

**Comment by y-lohse** [comment]
Before implementing this, we need to list the various use cases (editable domain, protocol or not, etc).

**Comment by ptbrowne** [comment]
What are the responsibilities of this component ?

**Comment by y-lohse** [comment]
Yes that's more or less the question. We have a chat scheduled with @joel-costa to clear things up :)
