### ISSUE TITLE
Remove old form styles

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-ui#752]
It requires to update all the apps still using those styles though.

I have special concerns about Settings & Drive but a thorough search in every apps must be done as well.

**Comment by GoOz** [comment]
As seen with @y-lohse there is 3 ways of using form elements (historically), 2 of them are obsolete but still in UI for retro compatibility.

### The very old checkbox + radio styles
https://github.com/cozy/cozy-ui/blob/master/stylus/elements/defaults.styl#L59-L108
This shouldn't be used anymore but there were still occurrences of `[data-input=checkbox]` & `[data-input=radio]
Every occurrences should be replaced by the new styles or you should simply use the React component. Once it's cleaned the entire chunk of code can be removed.

### The old Form styles
https://github.com/cozy/cozy-ui/blob/master/stylus/components/forms.styl#L13-L226
This is the old way of doing forms, deprecated & obsolete as well. It was replaced by the new styles below this chunk of code. But It is still used. Again, this should be cleaned by using either the new styles or the right React component.
Once it's cleaned, you can removed the whole chunk.

### The new form styles
https://github.com/cozy/cozy-ui/blob/master/stylus/components/forms.styl#L228-L543
This is the one to be used. This the one used by the React components. This is the current standard.
So do **not** remove this! 😝

**Comment by JF-Cozy** [comment]
On utilise maintenant Material Ui
