### ISSUE TITLE
Problème de duplication

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-ui#762]
Il y a un souci avec les `require` de stylus. A chaque fois que l'on fait un `@require 'settings/palette.styl'` cela duplique tous les `:root { ... }`.

~~Cela pose un énorme souci puisque par exemple le composant `cozy-authentication` surcharge le dernier `:root { ... }` du coup on doit forcément mettre à jour cozy-ui sur les dépendances que l'on importe avant de pouvoir utiliser une mise à jour de `cozy-ui`.~~

Je pense que l'on a besoin d'être éclairé (surtout de mon coté) sur :
- Comme fonctionne les `require` et est ce qu'ils sont indispensable ?
- Pourquoi il y a une duplication ?
~~- Comment ne pas être dépendant d'une librairie autre que `cozy-ui` ?~~

**Comment by kosssi** [comment]
Le problème avec cozy-authentication sera résolu avec la PR https://github.com/cozy/cozy-libs/pull/230 j'ai donc barré dans le descriptif cette partie

**Comment by ptbrowne** [comment]
Chaque `require` est fait dans un contexte différent vu que c'est une instance du stylus loader différent qui charge le fichier. Je vois 1 solution possible : 

- Faire en sorte que palette.styl n'output rien (pas de :root )
- Integrer un nouveau fichier qui s'occupe de setter les variables CSS, qui ne serait pas `require`d  par les composants mais qui serait rajouté au CSS transpilé, seulement une fois.

**Comment by JF-Cozy** [comment]
Cela me semble obsolète aujourd'hui
