### ISSUE TITLE
Empty > image margin 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#771]
Actuellement si un component `Empty` dispose d'une image, alors on ajoute automatiquement un `margin-bottom : 2rem` (https://github.com/cozy/cozy-ui/blob/master/stylus/components/empty.styl#L24) . Sauf que ça colle pas forcément avec l'espacement de certains designs. 

Est-ce volontaire de notre part ? Si oui pour quel cas ? Ou est-ce une petite incohérence dans des designs ? ping @Claiw / @GoOz ? 

<img width="402" alt="capture d ecran 2018-12-27 a 16 21 08" src="https://user-images.githubusercontent.com/1107936/50484967-8257b600-09f3-11e9-98b7-9c00235643d0.png">
<img width="408" alt="capture d ecran 2018-12-27 a 16 21 18" src="https://user-images.githubusercontent.com/1107936/50484968-8257b600-09f3-11e9-9df2-34724597f25f.png">

**Comment by GoOz** [comment]
Loin de moi l'idée de jeter la pierre mais je pense que c'est plutôt une incohérence côté design. :|

**Comment by Claiw** [comment]
c'est plutôt une adaptation qu'une incohérence à vrai dire ^^
comme on a plusieurs actions en plus de l'état vide, j'ai baissé le margin entre l'empty-img et le titre. 
j'ai discuté avec gooz dessus, je fais une carte sur le sujet derechef :)

**Comment by GoOz** [comment]
Fixed par #836
