### ISSUE TITLE
The button should not have margins

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#797]
https://github.com/cozy/cozy-ui/blob/2ea6c2aa02c45ad0e3dd2ce5b900db666badb1e3/stylus/components/button.styl#L60

I think we should remove this line, the button should not have margins since the application should handle its position with the possibility to give it margins or not.

**Comment by ptbrowne** [comment]
Can you open a PR with this ? Thanks :)

**Comment by GoOz** [comment]
I agree but beware, it will break stuff (and fix some others obviously)

**Comment by y-lohse** [comment]
Same goes for https://github.com/cozy/cozy-ui/blob/2ea6c2aa02c45ad0e3dd2ce5b900db666badb1e3/stylus/components/button.styl#L319 — buttons shouldn't actively cancel the margins that they may otherwise get.

**Comment by CPatchane** [comment]
Closing it, feel free to open a new issue if needed.
