### ISSUE TITLE
Bar App title on mobile : Need for a new style or component? 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#820]
In some Apps, we need to display its title in the CozyBar when we're on mobile. 

Currently it's done manually in some apps (Drive / Photos / Contacts) with some duplicate styles with something like : 

```jsx
<BarCenter>
      <Title>
          <span className={'fil-path-title'}>Contacts</span>
       </Title>
</BarCenter>
```

and 
```
.fil-path-title
    height 3rem
    display flex
    align-items center
    padding 0 .25rem
```

But I'm not very happy with this : 
- we have to duplicate style & component from app to app 
- we have a height fixed to 3rem because it's the height of the bar, but I tend to think this value should be stored in a variable somewhere 

I don't know if UI should provide a new component for that, like `<BarTitleOnMobile>` or just provide a css class ? What do you think?

**Comment by ptbrowne** [comment]
> I don't know if UI should provide a new component for that, like <BarTitleOnMobile> or just provide a css class ? What do you think?

I think we should provide a a new component for that. `AppTitle` ? I would not put `onMobile` since it's supposed to be responsive.
