### ISSUE TITLE
Ajouter un {...rest} sur tous les composants

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-ui#821]
De manière globale, tous les composants cozy-ui pourraient ajouter un `{...rest}` à leur élément racine ?

ça me parait bizarre que certaines props "standard" HTML (genre id) soient "filtrées" par nos composants. Je peux avoir besoin pour n'importe quelle raison de mettre un id sur un composant, sur la plupart ça fonctionnera pas.

Si je veux mettre un onClick, un onMouseEnter ou quoi que ce soit arbitrairement sur un élément, actuellement je dois aller ajouter la prop au composant de manière ciblée, alors qu'on pourrait théoriquement en avoir besoin sur n'importe lequel.

J'ai repris [cette article](https://hackernoon.com/the-coolest-react-ui-frameworks-for-your-new-react-app-ad699fffd651) qui parle de framework ui pour faire un comparatif sur le composant Button :
- Material-UI [utilise `{...other}`](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Button/Button.js#L279)
- react-desktop [utilise `{...props}`](https://github.com/gabrielbull/react-desktop/blob/master/src/Button/macOs/index.js#L68)
- Semantic-UI-React [utilise `{...rest}`](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Button/Button.js#L289)
- ant-design [utilise `{...otherProps as NativeButtonProps}`](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L264)
- blueprint [utilise `{...removeNonHTMLProps(this.props)}`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/buttons.tsx#L39)
- react-bootstrap [utilise `{...props}`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Button.js#L105)
- react-toolbox [utilise `{...props}`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/Button.js#L99)
- grommet [utilise `{...rest}`](https://github.com/grommet/grommet/blob/master/src/js/components/Button/Button.js#L97)
...

Je ne vois pas trop pourquoi on ne partirait pas sur cette façon de faire sur cozy-ui ;)

Voir la discussion https://mattermost.cozycloud.cc/test-team/pl/b9skhbq38tyapgjhiwubyotkxc

**Comment by y-lohse** [comment]
Je vais fermer cette issue — on est globalement d'accord que c'est une bonne pratique à suivre sur nos nouveaux composants, et qu'on peut l'ajouter aux anciens au fur et à mesure. Il faut juste se méfier de quelques cas plus spéciaux comme https://github.com/cozy/cozy-ui/issues/898 .
