### ISSUE TITLE
Selectbox disabled style differs

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#857]
In this screenshot, all fields are disabled but the SelectBox component style differs from the others.

![capture d ecran 2019-03-07 a 19 21 11](https://user-images.githubusercontent.com/776764/53979511-60269680-410e-11e9-8070-8facd6fe3ee2.png)

**Comment by gregorylegarec** [comment]
Fixed by #859

**Comment by ptbrowne** [comment]
Thanks !
