### ISSUE TITLE
How to use utility classes in our apps?

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#866]
The documentation doesn't really mention this.

In the latest [create-cozy-app](https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/template/app/src/styles/index.css#L1-L4), we import the cozy-ui complete build file, with *all* the classes in there, not just the utility classes.
We also import the transpiled stylesheet, needed by the transpiled react components. this stylesheet contains css-moduled classes, plus some utility classes.

1. Should the `transpiled/react/stylesheet.css` contain all utility classes, making them available to the app that wants them, even if not all of them are used by the transpiled components?
2. Should we expose a separate css file with *only* the utility classes?
3. Another approach?

cc @GoOz @CPatchane at least.

**Comment by y-lohse** [comment]
Personally I like the second solution. In my app, i'd like to do:

```
import 'cozy-ui/transpiled/react/stylesheet.css'
import 'cozy-ui/utilities.css'
```

And of course there shouldn't be duplicated styles between the two.

**Comment by GoOz** [comment]
The way I like it (or at least the way I think is the best) should be:
- a basic UI CSS file containing normalizer, default style for HTML elements, CSS custom properties & utilities
- the transpiled styles for every used components in the app, obviously without CSS custom properties & utilities used in those components (which is not what's happening right now).

**BUT** It should work the same even if you don't use transpilation.

That way, only one build for the basics and a different build for the components according to the config of the app.

For those using the whole CSS minified, we don't change anything, that's an exception.

**Comment by ptbrowne** [comment]
> BUT It should work the same even if you don't use transpilation.

Why ? To me, the way without transpiration is deprecated as it forces the host app to care about stylus. It also requires the host app to care on how cozy-ui files are coded and how they should be transpiled.

To me, the ergonomic way would be 1. I would be in favor of that.

I think 2 would be done in case of bundle size problem, I would like to test with or without utilities.

**Comment by GoOz** [comment]
Ok, I didn't know it was deprecated. I thought there were two official ways to use UI with JS.
In that case, I'm ok with both.

**Comment by CPatchane** [comment]
I would also prefer to have a css file with all utilities inside like @y-lohse suggested, it's better than to have all inside a file and the transpiled should be only for react components usage IMHO

**Comment by y-lohse** [comment]
This is now done, thre's a line in the readme about how to do this.
