### ISSUE TITLE
More utilities class

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#867]
Utilities classes are great but we're lacking classes for:
* border-radius
* background-color

**Comment by GoOz** [comment]
@gregorylegarec What are you expecting them to do actually?

A set of classes for several border radiuses (previously decided with designers) and one to cancel it?

Same question for background-color but maybe with already available colors ?

**Comment by gregorylegarec** [comment]
Exactly 👌

**Comment by y-lohse** [comment]
There's a longer wishlist [here](https://github.com/cozy/cozy-ui/issues/687), inspired by tachyons
