### ISSUE TITLE
[styleguidist] Use transpiled version 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#877]
In our styleguidist, we should use the transpiled version of the components and css since this is the way we recommend to use cozy-ui in our app. (we'll have the same "classes order" and so on)

**Comment by y-lohse** [comment]
I'm not quit sure how to do this right now, or if it's even possible.

The components are listed [here](https://github.com/cozy/cozy-ui/blob/master/docs/styleguide.config.js#L9). We can replace `'../react/Badge/index.jsx'` with `'../transpiled/react/Badge/index.js'`, but the transpiled JS file obviously lacks all the code annotations that styleguidist uses to generate the examples.
It also misses the `Readme.md` files, which are normally loaded by styleguidist's webpack.

I haven't thought much more about it but if anyone has ideas, feel free to mention them here :)
