### ISSUE TITLE
Spinner color is in SVG

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-ui#878]
Lors de la customisation de Banks, je viens de me rendre compte que dans cozy-ui nous avons plusieurs SVG avec seulement une couleur qui change.

![Capture d’écran 2019-03-21 à 15 56 27](https://user-images.githubusercontent.com/1135513/54761360-3da67a00-4bf2-11e9-8c97-3fa86f2757cf.png)

Nous devrions pouvoir avoir qu'un seul SVG et injecter la couleur en CSS, ce qui permettrait de facilement changer la couleur avec les variables CSS.

Différents liens:
- https://github.com/cozy/cozy-ui/tree/master/react/Spinner
- https://github.com/cozy/cozy-ui/blob/master/stylus/settings/icons.styl#L126-L144

**Comment by GoOz** [comment]
Ouais c'est du legacy… faudrait mettre à jour. 

En attendant tu peux utiliser directement le composant `<Icon />` avec une props `spin` comme sur [l'exemple *Transform properties*](https://docs.cozy.io/cozy-ui/react/#icon)
