### ISSUE TITLE
div in a p in Empty

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#879]
I see this warning in my console

<img width="583" alt="image" src="https://user-images.githubusercontent.com/465582/54763807-efe04080-4bf6-11e9-8092-35ac59d76851.png">

**Comment by GoOz** [comment]
Seems about right. 
The Empty text is `<p>` and you're giving it a `<div>` instead of a string maybe. Anyway the warning is right. `<div>` cannot be a child of `<p>`.

**Comment by ptbrowne** [comment]
It was a mistake on our part, fixed, thanks !
