### ISSUE TITLE
I18n context API

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-ui#881]
As @nono mentionned, I18n component is providing a [legacy React context](https://reactjs.org/docs/legacy-context.html). We should improve its mechanism to fit the [latest context specification](https://reactjs.org/docs/context.html)

**Comment by y-lohse** [comment]
Note:same issue with the `CozyClientProvider` of `cozy-client`.

**Comment by drazik** [comment]
As far as I know, there is no plan about a React major release that removes the legacy context API. And for now, Preact doesn't implement the latest API (Preact X, [currently alpha](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0), will). So I think we should not hurry to do this refactor, and better wait for Preact X to be released. This way we won't have to deal with legacy API for Preact and new API for React.

**Comment by Crash--** [comment]
@ptbrowne It's done now, right?

**Comment by ptbrowne** [comment]
Yep, thanks !
