### ISSUE TITLE
Size of built CSS and utilities

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#887]
Quelques tests avec les utilitaires, en rajoutant un fichier utilities.js qui est transpilé, on rajoute les classes utilitaires à la `stylesheet.css` transpilée, j ai fait plusieurs tests en rajoutant 1 à 1 les fichiers.

```
// Special file for utilities to be included in the transpiled stylesheet
// we start at 130k ( :'( )
import bgcolor from '../stylus/utilities/bgcolor.styl' // 130k
import cursor from '../stylus/utilities/cursor.styl' // 130k
import dimensions from '../stylus/utilities/dimensions.styl' // 157k (+27k)
import display from '../stylus/utilities/display.styl' // 157k
import effects from '../stylus/utilities/effects.styl' // 157k
import flexbox from '../stylus/utilities/flexbox.styl' // 178k (+21k)
import list from '../stylus/utilities/list.styl' // 178k
import opacity from '../stylus/utilities/opacity.styl' // 178k
import spaces from '../stylus/utilities/spaces.styl' // 178k

// En enlevant teeny tiny et extra-large on passe à 126k
```

J'en sors 2 questions: 

- a-t-on vraiment besoin des 7 breakpoints ?
- a-t-on vraiment besoin que les classes de flexbox et dimensions soient "breakpointées"

Pour l'équipe gangsters, je dirais non aux 2 questions (sous votre controle @drazik et @kosssi).

cc @edas @GoOz @y-lohse

**Comment by GoOz** [comment]
Tous les breakpoints ptête pas, en effet. on pourrait discuter de ça avec les enjoliveurs pour définir les plus importantes.
Mais pour les classes flexbox et dimensions je pense que oui y en a besoin.

**Comment by y-lohse** [comment]
Merci pour les tests!

> a-t-on vraiment besoin des 7 breakpoints ?

A vue de nez ca me parait beaucoup aussi, et au quotidien je ne pense pas en utiliser plus de 3. Faisons la liste des utilisations et voyons avec les enjoliveurs si tout est nécessaire.

> a-t-on vraiment besoin que les classes de flexbox et dimensions soient "breakpointées"

Dur à dire la tout de suite. Je pense aussi qu'elles vont servir, mais comme elles sont neuves c'est trop tôt pour en être sûr. Je propose de les laisser en place et de refaire un point d'ici 2-3 mois, et d'écremer a ce moment la.

**Comment by ptbrowne** [comment]
> Faisons la liste des utilisations 

Dans Banks on utilise : 

Mixins:

- small-screen (<768px), c'est le pendant de isMobile. 60 fois
- medium-screen (>768 <1024), 10 fois 

HOC

- isTiny (0 fois)
- isExtraLarge (4 fois, > 1200)
- isMobile (74 fois, <768px)
- isDesktop (21 fois, >1024px) via le HOC withBreakpoints
- isTablet (4 fois), pareil que isMedium (>768 <1024)

- On a un breakpoint à 480px pour un email mais c'est fait manuellement


```fish
for str in 'large-screen\(.*\)' 'medium-screen\(.*\)' 'small-screen\(.*\)' 'isTablet' 'isMobile' 'isDesktop';
  echo $str; rg $str | wc -l;
end
```

**Comment by y-lohse** [comment]
Je pense qu'on peut fermer cette issue:

- Il n'y a plus que 3 tailles de media-queries
- On a tranché sur la nécessité de rendre certaines classes utilitaires responsive ou non (seulement pour celles qui peuvent raisonnablement changer entre desktop et mobile)

Je vous laisse ré-ouvrir si vous pensez qu'il reste des actions à faire sur cette issue.
