### ISSUE TITLE
Styleguidist blank on Safari

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#896]
Blank page when opening Styleguidist on Safari 12.0.3

Here is the error found in console: `TypeError: undefined is not an object (evaluating 'vAPI.shutdown')`

**Comment by CPatchane** [comment]
Update: It seems to be due to an adBlocker enabled, at least uBlock Origin

**Comment by y-lohse** [comment]
So if disabling uBlock is a solution, I'll close this as we likely won't fix the issue on our end, if there even is one.
