### ISSUE TITLE
CSS shouldn't display svg icons in background, but only change their color, size, etc

### ISSUE THREAD

**Issue by GoOz** [cozy/cozy-ui#90]

**Comment by ptbrowne** [comment]
https://github.com/cozy/cozy-ui/issues/125 can help

In [MAIF's nav styl](https://gitlab.cozycloud.cc/labs/cozy-maif/blob/master/src/styles/nav.styl), the icon is red when the link is `.active`.

![image](https://cloud.githubusercontent.com/assets/465582/26638265/024149f4-4622-11e7-9021-7d578d32f205.png)

**Comment by GoOz** [comment]
Every icon should be in svg, in the DOM, not in css background.
This is issue is kinda fixed by the new `<Sidebar` /> component but since there's way more icon to implement, I'll juste rename the issue.

**Comment by GoOz** [comment]
Kinda duplicate of #121

**Comment by ptbrowne** [comment]
Let's close if this is a duplicate :)
