### ISSUE TITLE
UI export JSON translation file?

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#914]
> It is inconvenient for apps to ship with UI translation strings. Maybe cozy-ui could export JSON translation files that could extend the app translation strings ?
Something that could be used like this ?
import { translate } from 'cozy-ui/react'
import { fr, en } from 'cozy-ui/locales'
translate.extend(fr)
translate.extend(en)
Maybe the translation string could be namespaced under cozy-ui : cozy-ui.SelectionBar.close ? I think it would be clearer.

https://github.com/cozy/cozy-ui/pull/897#issuecomment-483245026

**Comment by GoOz** [comment]
I think it will be a more and more important thing to do. 
I stumbled upon some close button that needs a label and for now it's in english only (not visible but still readable by screen readers). If we want to do more high component we will definitely need it, very soon.

**Comment by y-lohse** [comment]
Plusieurs approches possibles:

### 1. Traductions dupliquées (aka. comme actuellement)

Les composants de cozy-ui appellent `t('composant.mot')`, et l'app doit avoir `composant.mot` dans ses sources anglaises, et donc dans son projet transifex.

Problème: tout est dupliqué.

### 2. Fusion avant le build

Les composants de cozy-ui appellent `t('composant.mot')`, et proposent un fichier `en.json` avec les chaines à traduire et leur version anglaise.
Avant le build, les apps fusionnent ce fichier `en.json` avec celui de leur projet, et c'est ca qui est envoyé vers transifex.

Problème: les traductions non-anglaises sont dupliquées, besoin d'un mécanisme de fusion avant le build.

### 3. Fusion au runtime

Les composants de cozy-ui appellent `t('composant.mot')` et fournissent des JSON de traduction pour toutes les langues. cozy-ui à son propre projet transifex avec ses traductions dedans.
Les apps doivent ajouter ces fichiers de traduction à leur dictionnaire au moment du boot (voir exemple de code dans le premier commentaire).

Problème: Possible conflits de clés de traductions, coder un mécanisme d'extension du dictionnaire ?

### 4. Traductions en props

Les composants cozy-ui reçoivent en prop les labels à utiliser, dans la bonne langue. Ils ne font pas appel à `t`.

Problème: traductions dupliquées partout

### 5. Transpilation complète

Les composants transpilés sont livrés avec leur propre contexte de traduction. Il n'y a pas besoin d'étendre le dictionnaire de l'app. Les traductions sont gérées dans un projet transifex dédié à cozy-ui.

Problème: ???

**Comment by y-lohse** [comment]
A noter que la dernière option est utilisée sur harvest et sur [authentication](https://github.com/cozy/cozy-libs/pull/411), et semble présenter le moins d'inconvénients… donc c'est bien possible que l'on parte la dessus.

**Comment by ptbrowne** [comment]
Problème rencontré : dans le cas de composants Wrapper il faut rétablir le context précédent sinon le t devient selui du composant UI et plus celui des composants wrappés.

**Comment by y-lohse** [comment]
Il ya maintenant un HOC `withLocales` dans la partie i18n qui permet de wrapper des composants dans leurs propres contextes de traduction. Voir le viewer pour un exemple d'utilisation.

**Comment by y-lohse** [comment]
Je pense qu'on peut fermer. Il reste le problème décrit [ici](https://github.com/cozy/cozy-ui/issues/914#issuecomment-487959521) mais ca semble assez rare et on a des solutions pour contourner, on n'a pas d'évolution prévue sur le `withLocales` pour ca.
