### ISSUE TITLE
Arrow-left and Arrow-right not correctly sized within a Button

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#987]
```jsx
<Button icon='arrow-left' label='delete' />
```

<img width="1044" alt="Screenshot 2019-05-16 at 14 21 04" src="https://user-images.githubusercontent.com/10224453/57853382-eda8f580-77e5-11e9-9d10-f12a495d3477.png">

**Comment by GoOz** [comment]
This is taken care of in the PR #983.
In the meantime, use `previous` & `next` instead because the `arrow-*` icons will be removed.

**Comment by Benibur** [comment]
if you remove `arrow-*` then how do you deal the classical "back arrow" such as : 
![image](https://user-images.githubusercontent.com/1266420/57864314-f5739480-77fb-11e9-8f7e-33eab5bcddbd.png) ?

**Comment by GoOz** [comment]
> if you remove `arrow-*` then how do you deal the classical "back arrow" such as :
> ![image](https://user-images.githubusercontent.com/1266420/57864314-f5739480-77fb-11e9-8f7e-33eab5bcddbd.png) ?

With `previous` instead of `arrow-left`. There is a duplication of those two icons.
`next`& `previous` will stay when `arrow-right` & `arrow-left` will be removed.

**Comment by Benibur** [comment]
excellent, thank you, here is the result !
![image](https://user-images.githubusercontent.com/1266420/57888669-10adc680-7833-11e9-9288-57de810ee9a7.png)

**Comment by y-lohse** [comment]
This has been fixed.
