### ISSUE TITLE
Inconsistencies on `Radio` tick placement

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#999]
We have a lot of inconsistencies on the `Radio` component's tick placement (the little white dot that should be centered in the blue circle, I don't know how to call it).

I screenshoted it on various configurations so we have a global view:

|Platform / Browser|Result|
|------------------|------|
|Windows 10 / Edge 18|![image](https://user-images.githubusercontent.com/1606068/58252337-2e64b980-7d66-11e9-839e-e5287a2f237a.png)|
|Windows 10 / Firefox 67|![image](https://user-images.githubusercontent.com/1606068/58252657-eb571600-7d66-11e9-9274-6f595c28a6d7.png)|
|Windows 10 / Chrome 74|![image](https://user-images.githubusercontent.com/1606068/58252781-2eb18480-7d67-11e9-8c5b-36f902b8a6e4.png)|
|MacOS / Safari 12|![image](https://user-images.githubusercontent.com/1606068/58252861-68828b00-7d67-11e9-964b-24cb6ee60d73.png)|
|MacOS / Firefox 67|![image](https://user-images.githubusercontent.com/1606068/58252930-8ea82b00-7d67-11e9-9b97-2a27f185cae5.png)|
|MacOS / Chrome 74|![image](https://user-images.githubusercontent.com/1606068/58252989-aa133600-7d67-11e9-8f58-c25655ab5009.png)|
|Ubuntu 19.04 / Firefox 67|![image](https://user-images.githubusercontent.com/1606068/58253073-e050b580-7d67-11e9-9692-74b67a0737a1.png)|
|Ubuntu 19.04 / Chrome 73|![image](https://user-images.githubusercontent.com/1606068/58253251-49d0c400-7d68-11e9-84d9-e3a0d6773ad0.png)|

**Comment by GoOz** [comment]
This is gonna be difficult… This is the results I got.


|Platform / Browser|Result|
|------------------|------|
|Windows 10 / Edge 18|![image](https://user-images.githubusercontent.com/1280069/58258535-3aa34380-7d73-11e9-9341-cf501777bed6.png)|
|Windows 10 / Firefox 67|![image](https://user-images.githubusercontent.com/1280069/58258604-53135e00-7d73-11e9-9fa8-300d1866f66d.png)|
|Windows 10 / Chrome 74|![image](https://user-images.githubusercontent.com/1280069/58258674-73dbb380-7d73-11e9-884c-2e0bf4a06d2c.png)|
|MacOS / Safari 12|![image](https://user-images.githubusercontent.com/1280069/58258787-ab4a6000-7d73-11e9-98f1-e0ec4881c286.png)|
|MacOS / Firefox 68|![image](https://user-images.githubusercontent.com/1280069/58258827-b8674f00-7d73-11e9-9865-1f4f5ec8c3e4.png)|
|MacOS / Chrome 74|![image](https://user-images.githubusercontent.com/1280069/58258759-9e2d7100-7d73-11e9-965d-3f835f097c39.png)|

**Comment by GoOz** [comment]
@drazik can you test that for me https://gooz.github.io/cozy-ui/react/#radio please?
I think this way should be me more stable but I can't be sure since I can't reproduce the rendering you get.

**Comment by drazik** [comment]
@GoOz that's perfect :tada:
